### ISSUE TITLE
Validation issue with short numbers (NO)

### ISSUE THREAD

**Issue by frapaa** [googlei18n/libphonenumber#1396] opened 2016-10-24 07:40 UTC
Background:
The 6-digit telephone number series from 116 000 to 116 999 has been set aside for certain services of social value in EU/EEA countries.

In particular, 116 117 is the number for non-emergency medical on-call services.

---

Details:
Country/region affected (e.g., "US"): NO, probably more

Example number(s) affected ("+1 555 555-1234"): 116117

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 116000-116999

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 6-digit EEA-harmonised numbers 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): toll-free (receiver pays)

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[Link to official documentation](http://eng.nkom.no/market/numbering/e.164-numbering-plan/6-digit-eea-harmonised-numbers-116xxx)

[Link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=116117&country=NO)

**Comment by kkeshava** [comment] 2016-10-25 04:38
Hi,

Thanks for the report! This is actually working as intended; 116117 is already marked by the demo as a valid *short* number. Please see third column "Short Number Results" in [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B919731745003&country=US)

For more information, check out [this FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-does-phonenumberutil-return-false-for-valid-short-numbers)

**Comment by kkeshava** [comment] 2016-10-25 04:38
I'll close this as it's not an issue with the library. Please consider joining
the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.

**Comment by frapaa** [comment] 2016-11-09 10:19
Thanks, I missed the point where this is actually a "short number". However, why is it handled different from another number in the same number range; 116123 ?

For 116117 `isValidShortNumber` and `isValidShortNumberForRegion` is `true`
But for 116123 the same methods return `false`

**Comment by lararennie** [comment] 2016-11-09 11:22
We need to add support for 116123 for Norway it seems ;)

http://www.mentalhelse.no/tjenester/hjelpetelefonen

9. nov. 2016 11.19 a.m. skrev "Frank Paaske" <notifications@github.com>:

**Comment by frapaa** [comment] 2016-11-09 11:36
Sorry I deleted my comment and created a discussion here: https://groups.google.com/forum/#!topic/libphonenumber-discuss/oIpbJ4YekJU

There are even more numbers allocated: 

116 000 the missing children hotline
116 006 the helpline for victims of crime
116 111 the children’s helpline (assigned)
116 117 for non-emergency medical on-call services (assigned)
116 123 the emotional support helpline (assigned)


http://eng.nkom.no/market/numbering/e.164-numbering-plan/6-digit-eea-harmonised-numbers-116xxx

**Comment by kkeshava** [comment] 2016-11-14 04:49
@frapaa,

Thanks for reporting the issue. We will support 116 111 and 116 123 short numbers as they are mentioned as assigned in nkom.no, however 116 000 and 116 006 might be allocated but are not yet assigned/functional.  Hence we won't add 116 000 and 116 006 unless you can provide sources to indicate they are actually in use.

**Comment by frapaa** [comment] 2016-11-14 07:30
Sure, no problem!

I have one question though; is the libphonenumber library only supposed to support numbers currently active/assigned? That might work for short numbers which usually are assigned more or less permanently, but it makes the library kind of inconsistent with regard to other number series.

Example of this inconsistency;
(these are not "short numbers")
02024, 02025, and 02026 are available, assigned and in quarantine respectively, but they all have the same output from libphonenumber.

**Comment by kkeshava** [comment] 2016-11-14 10:45
@frapaa,

Yes, libphonenumber only supports numbers which are currently active/assigned. We prefer not to add one-offs without enough authoritative evidence since it becomes unsustainable and data quality might go down if we lower the bar for entry

Please note that we are reaching out to the owners of eng.nkom.no to check the current status of numbers not listed as assigned.

**Comment by kkeshava** [comment] 2016-11-14 11:08
@frapaa ,
You can use our [ShortNumberInfo.isPossibleShortNumber()](
https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/ShortNumberInfo.java#L165) API for more lenient check. 
Ex: Check "Result from isPossibleShortNumber()" in http://libphonenumber.appspot.com/phonenumberparser?number=116000&country=NO

**Comment by penmetsaa** [comment] 2016-11-24 08:46
This is fixed in release 7.7.5:
https://libphonenumber.appspot.com/phonenumberparser?number=116111&country=NO (Check 'Short Number Results' section)

**Closed by penmetsaa** 2016-11-24 08:46 UTC
