### ISSUE TITLE
National format changes default number

### ISSUE THREAD

**Issue by ayaskevich** [googlei18n/libphonenumber#1695] opened 2017-04-17 14:01 UTC
When trying to format this number +3461211111111111119, it returns this:
`{
 "country_code":34,
 "national_number":61211111111111120,
 "raw_input":"+3461211111111111119",
 "country_code_source":1
}`
And the number is changed (last digits 19 transforms into 20). Similar when trying to format +3461211111111111111, +37529111111111111111, +37529666666666666666 and so on.

**Comment by kkeshava** [comment] 2017-04-18 06:29
@ayaskevich,
Thank you for using libphonenumber!

This is actually working as intended; when +3461211111111111119 is given as input it returns national_number: 61211111111111119 correctly. The last digits are not transforming. To check the latest behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B3461211111111111119)(instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by ayaskevich** [comment] 2017-04-18 08:35
@kkeshava oh, I forgot to mention that it was in js lib, [this demo](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html)

**Comment by kkeshava** [comment] 2017-04-19 09:29
Thank you for taking the time to improve libphonenumber!

This issue is a duplicate of #1474. Closing this issue.

**Closed by kkeshava** 2017-04-19 09:29 UTC
