### ISSUE TITLE
Support for 13 digit numbers in Sweden

### ISSUE THREAD

**Issue by havardk** [googlei18n/libphonenumber#1069] opened 2016-04-07 08:57 UTC
Sweden has a number series with 13 digits:
+46 71AXXXXXXXXXX (Only A=0,9 are in use)

These numbers currently fail also the isPossibleNumber() check because that is limited to 12 digits.  This number series is listed in the official Swedish number plan.

+46 710XXXXXXXXXX is used for mobile broadband subscriptions, so I believe it should be treated as a valid mobile number.

**Comment by penmetsaa** [comment] 2016-04-13 14:26
@havardk

Thanks for reporting this issue.

This is a duplicate of #910, please see that issue for our responses.

Please check our [FAQ page](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers) for the information we need to support these numbers.

This issue is currently infeasible. Please open a new issue with the requested information if applicable.

You can search for existing issues in below page. If you find any match, you can provide your inputs directly and help users.
https://github.com/search?utf8=%E2%9C%93&q=%22Sweden+71%22&type=Issues&ref=searchresults

**Closed by penmetsaa** 2016-04-13 14:26 UTC
