### ISSUE TITLE
Validation issue with 14911479837 (CN)

### ISSUE THREAD

**Issue by nullne** [googlei18n/libphonenumber#1976] opened 2017-10-19 06:01 UTC
Country/region affected (e.g., "US"): CN

Example number(s) affected ("+1 555 555-1234"): 14911479837, 14911479857, 14911479451

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

I can call these numbers, but there seems be some limitation to dial 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=14911479837&country=CN)

**Comment by keghani** [comment] 2017-10-19 08:51
We can't connect to +86 149 1147 9837, +86 149 1147 9857, or +86 149 1147 9451. Did you have a typo?

Closing this as working as intended; if you would like to reopen, please share
any working numbers or evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by nullne** [comment] 2017-10-20 04:17
you can try to dial 14911030512, please don't disturb this real person.
I found explanation about mobile prefixed with 149 on [wiki](https://zh.wikipedia.org/wiki/中国内地移动终端通讯号码) this page only shows in Chinese

**Comment by nullne** [comment] 2017-10-20 04:19
you can try to dial 14911030512, please don't disturb this real person.
I fond explanation about mobile prefixed with 149 on [wiki](https://zh.wikipedia.org/wiki/中国内地移动终端通讯号码). (only in Chinese)

@keghani   and I don't have permission to reopen

**Comment by keghani** [comment] 2017-10-20 09:12
Thanks for the new number @nullne !

Please don't share private information on GitHub, you can share these with us in our private list (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence). Public phone numbers e.g. of businesses found online are fine.

From what I gather from the Wikipedia link, 149 is not used to call or SMS, but for data only. We do not support such numbers in the library at the moment, see [our FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers).

Moreover, there's no reference linked from Wikipedia and I can't find *any* numbers online in this range. I'm afraid there's no evidence for this being a mobile range and I'll close as infeasible until we know better.

**Comment by keghani** [comment] 2017-10-20 09:12
I should add that even if we support M2M numbers - ranges that are explicitly unable to receive voice calls or SMS are not in scope of this library.

**Closed by keghani** 2017-10-20 09:12 UTC

**Comment by nullne** [comment] 2017-10-20 09:25
@keghani  thank you for you time 
but this number is really dialable. I don't know why 
I asked this person  but no reasonable explanations.
