### ISSUE TITLE
Netherlands M2M and OTT numbers not supported

### ISSUE THREAD

**Issue by jbwanted** [googlei18n/libphonenumber#1542] opened 2017-01-30 17:27 UTC
Number sample: 3197005030420 

Source: https://www.government.nl/documents/annual-plans/2016/02/16/numbering-policy

**Comment by bdewater** [comment] 2017-01-31 18:23
See #680

**Comment by penmetsaa** [comment] 2017-02-01 07:26
@bdewater,
Thanks so much for responding on this.

@Zehir,
Thank you for using libphonenumber and reporting this issue!

libphonenumber presently do not support M2M numbers. But we are checking on the options on how to support M2M numbers. Please take a look at our page [What about m2m machine to machine numbers](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers)

This is duplicate of issue #680 and similar to #1231.
Please contribute on the existing issue #680 to add to our understanding.

**Closed by penmetsaa** 2017-02-01 07:26 UTC

**Comment by penmetsaa** [comment] 2017-02-01 09:21
@jbwanted,
I am not able find any OTT numbers in government.nl website. We are not sure of what OTT numbers mean here. Are these 'Over the top content' numbers?
https://en.wikipedia.org/wiki/Over-the-top_content

Libphonenumber does not support any satellite television or data numbers. Please reopen the bug if this is not the case.

**Comment by jbwanted** [comment] 2017-02-01 10:32
@penmetsaa 
I am writing on behalf of onoff app and we are going to offer Netherlands M2M numbers as Mobile cloud numbers. These numbers would be used both for calling and SMS-ing. Unfortunately this is the law restriction and we can't get Netherlands real mobile numbers for our usage. Seems like M2M number usage allowance is specific per country, so for example in our case Netherlands offers them as mobile numbers. We are investigating this and when I have some documentation or specification regarding these Netherlands M2M numbers then I am coming back and submitting info to #680 also.

**Comment by jbogdanov** [comment] 2017-09-11 13:33
@penmetsaa 

SMS OTT Service
The SMS OTT Service solution allows OTT to get Mobile Isdn Number from a donor operator in order to exchange SMS traffic with other M( V)NO’s located in same country as donor via Bics SMSHUB solution .
