### ISSUE TITLE
As you type formatter breaks when add leading 0 for area code when typing the country code

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#366] opened 2014-12-03 20:25 UTC
Imported from [Google Code issue #366](https://code.google.com/p/libphonenumber/issues/detail?id=366) created by [tCheard](https://code.google.com/u/101682313161183350945/) on 2013-11-01T00:43:26.000Z:

----
<b>What steps will reproduce the problem?</b>
1. I have done this on my own system with my own copy of libphonenumber, but I can also replicate this on the demo host at http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html
2. Go to http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html
3. Enter the number '+64044567890'
4. Note that after the '0' of the area code is entered it will stop formatting in a similar manner that it does when the number is invalid.
5. Note 'Result from isValidNumber(): true'

<b>What is the expected output? What do you see instead?</b>
I expect the formatter to just ignore the leading zero (ie. strip it out), then continue formatting

<b>What version of the product are you using? On what operating system?</b>
r620 Javascript on my local copy. r603 with the online demo

<b>Please provide any additional information below.</b>

**Comment by keghani** [comment] 2016-09-23 12:47
As Lara mentioned this is working as intended, so closing the issue.

**Closed by keghani** 2016-09-23 12:47 UTC
Labels: priority-low, type-defect
