### ISSUE TITLE
miss 991: Trial of a proposed new international service, shared code,

### ISSUE THREAD

**Issue by jiafu1115** [googlei18n/libphonenumber#1631] opened 2017-03-14 07:17 UTC
miss 991: Trial of a proposed new international service, shared code,
refer to https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.164C-2011-PDF-E.pdf

**Comment by penmetsaa** [comment] 2017-03-14 09:37
Closing this as working as intended. More details in PR #1627.

**Closed by penmetsaa** 2017-03-14 09:37 UTC

**Comment by penmetsaa** [comment] 2017-03-14 09:53
@jiafu1115 ,
We do not support all the country codes mentioned in ITU documents unless there are numbers assigned under that country code / do have numbering plan. Please take a look at our 
[FAQ page #why-are-bouvet-island-bv-pitcairn-island-pn-antarctica-aq-etc-not-supported](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-are-bouvet-island-bv-pitcairn-island-pn-antarctica-aq-etc-not-supported). Please feel free to reopen this bug with supporting evidences.
