### ISSUE TITLE
Validation issue with Germany number +491590248445

### ISSUE THREAD

**Issue by lightbringer1991** [googlei18n/libphonenumber#1509] opened 2017-01-16 05:44 UTC
Validation Results:
****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: DE
Result from getNumberType(): UNKNOWN

****Formatting Results:**** 
E164 format: invalid
Original format: +491590248445
National format: 1590248445
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid

When validating with http://www.silverstreet.com/products/number-lookup/, it gives me this
![image](https://cloud.githubusercontent.com/assets/2588669/21972090/fbe52dfe-dc0a-11e6-866b-9990ff39414f.png)
Which basically confirm the validity of the number.

**Comment by penmetsaa** [comment] 2017-01-19 10:27
@lightbringer1991,

Thanks for using libphonenumber!

Indeed, 491590248445 is a valid number, but the 49 here is not the country calling code, but part of the national number. See in [demo](http://libphonenumber.appspot.com/phonenumberparser?number=491590248445&country=DE) that our library is working as intended here.

When parsing this number with the library, either use "[+49491590248445](http://libphonenumber.appspot.com/phonenumberparser?number=%2B49491590248445)" (with any region code), or "491590248445" with region code "DE".

We exhaustively searched for evidence for 1590248445 being valid and didn't find it.

I'll close this as it doesn't seem to be an issue. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss further.
If you feel we reasoned about this incorrectly, such as if you actually meant us to validate the national number 1590248445 in DE, please re-open the issue with more information (evidence + its type + probably range granularity). See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Closed by penmetsaa** 2017-01-19 10:27 UTC
