### ISSUE TITLE
Updated IR21 document for REliance Jio

### ISSUE THREAD

**Issue by DeepakGuptaRelianceJio** [googlei18n/libphonenumber#1614] opened 2017-03-07 11:59 UTC
Hi 

Please update the number series for Reliance jio to enable google customers to receive the OTPs and google SMSes

Regards

Deepak Gupta

**Comment by keghani** [comment] 2017-03-07 12:09
Please do not attach non-public information in issues.

See our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md). Specifically, for evidence that's not readily available via a publicly accessible URL, please sign the CLA and share it with libphonenumber-supporting-docs.

**Comment by DeepakGuptaRelianceJio** [comment] 2017-03-14 09:12
Hi 
I tried signing the CLA but it is giving me the following error

"You must be an owner of the contributors group in order to submit this CLA."

this is for the following group
libphonenumber-supporting-docs@googlegroups.com

please help

**Comment by lararennie** [comment] 2017-03-15 11:09
Did you read the guidelines that were linked? the CLA thing is *not* the libphonenumber-supporting-docs group. You also have to be whitelisted to share with that group: which will only happen once you've followed the instructions about CLA signing.

**Comment by DeepakGuptaRelianceJio** [comment] 2017-03-15 11:35
Hi

I could sign the CLA as an individual using my gmail id.
But I haven’t received any confirmation whether my email id dkg777@gmail.com<mailto:dkg777@gmail.com> is whitelisted now

Can you help checking the same

Regards


[Deepak_ Gupta]

**Comment by penmetsaa** [comment] 2017-03-20 06:58
@DeepakGuptaRelianceJio 
Thanks! You've been whitelisted!
Please email libphonenumber-supporting-docs@googlegroups.com with documentation
to support this request. It would help us if you mention the issue number in the
subject line. As a reminder, only the core libphonenumber team has access to
view emails sent to this address.

**Comment by DeepakGuptaRelianceJio** [comment] 2017-03-20 08:56
Hi

I tried writing to the below mentioned email id but it bounced. Please see the attached email

Regards

Deepak Gupta

**Comment by keghani** [comment] 2017-03-20 09:05
@DeepakGuptaRelianceJio 

Sorry for the trouble, we actually could not find a CLA signature for you.
Are you sure you signed with this account?
Please see our guidelines for [providing evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence) and follow all the instructions so we may find your signature and unblock this issue.

Copying the relevant sections:



If the evidence is not publicly available online, make sure that you have the
rights to share this with us, and confirm this by reading and signing the
appropriate Contributor License Agreement (CLA):

*   If you are contributing as an individual, sign the [individual
    CLA](http://cla.developers.google.com/about/google-individual?csw=1).
    **N.B. Use an email address associated with the GitHub username used to file
    the corresponding issue.**
*   If you are contributing as part of a corporation, sign the [corporate
    CLA](http://developers.google.com/open-source/cla/corporate?csw=1).

**By signing the CLA, you confirm that you have the rights to share the
information with us, and that we may use, modify, reproduce, publicly display,
and distribute the information in accordance with the library's [open source
license](http://github.com/googlei18n/libphonenumber/blob/master/LICENSE).**

Once you have signed the CLA:

*   Comment on the open issue, e.g. "I signed the CLA, please whitelist me to
    send private documentation to libphonenumber-supporting-docs".
*   Someone from the team will whitelist you and update you on the issue.

Once whitelisted, you will be able to email
libphonenumber-supporting-docs@googlegroups.com. Only the core libphonenumber
team has access to view emails sent to this address.

**Comment by DeepakGuptaRelianceJio** [comment] 2017-03-20 09:14
Hi

I am getting this error when I am trying to sign the CLA for corporate

Please help

Regards

Deepak Gupta

**Comment by DeepakGuptaRelianceJio** [comment] 2017-03-20 09:15
Hi
‘I am getting the following error when I  am trying to sign the CLA. Please help

[cid:image001.png@01D2A188.769B5040]

[Deepak_ Gupta]

**Comment by keghani** [comment] 2017-03-20 09:37
Hi @DeepakGuptaRelianceJio,

Thanks for your quick response! I do not see the image you attached, but I guess you saw something like, "A server error occurred, please try your request again." Is this correct?

If you're getting a server error, it is possible that you're already signed in with an account that's covered by a CLA.

Possible reasons for this inconsistent state:
*   I see a CLA signature for the @gmail.com account you shared, but the GitHub username is set to libphonenumber-supporting-docs@googlegroups.com. This is not good. We need the individual CLA signature to be for GitHub username DeepakGuptaRelianceJio.
*   If you'll sign the corporate CLA then we need to whitelist an email address from that corporation (not @gmail.com).

Did you already sign a corporate CLA earlier? If so, what was the name of the corporation?

**Comment by DeepakGuptaRelianceJio** [comment] 2017-03-20 10:08
Hi

Here is the picture with error

[cid:image001.png@01D2A18F.D05321B0]
Regards

Deepak Gupta

**Comment by keghani** [comment] 2017-03-20 10:13
Still don't see the picture. See https://github.com/googlei18n/libphonenumber/issues/1614#issuecomment-287718043 to see what I see.

Could you confirm verbally the error message you're seeing? Is it "A server error occurred, please try your request again"?

**Comment by DeepakGuptaRelianceJio** [comment] 2017-03-20 10:18
It says “ You must be an owner of the contributors group in order to submit this CLA.”

Regards

Deepak Gupta

**Comment by keghani** [comment] 2017-03-21 13:26
Hi @DeepakGuptaRelianceJio,

Thanks for your patience!

Looks like we already got access to this document elsewhere. So there's no need to sign the CLA anymore, we'll fix it in an upcoming release.

As for the error message, it is probably happening because you're not an owner of our mailing list (libphonenumber-supporting-docs@googlegroups.com). This is intended. You signed the CLA using this as your GitHub username, but it's not valid because your username is DeepakGuptaRelianceJio. If you would still like to sign an individual CLA (for example to use for later issues with libphonenumber), please go to https://cla.developers.google.com/clas and click on "Edit Contact Information", and use DeepakGuptaRelianceJio as the GitHub Username.

The corporate CLA is only to make contributions on behalf of your employer. Please see https://cla.developers.google.com/about to determine if this is a better fit for you.

**Comment by DeepakGuptaRelianceJio** [comment] 2017-03-21 14:34
Hi

This IR21 document is with current number series and this keeps on getting updated wit new number ranges being opened for Reliance Jio. So can we put this in a process so that everytime there is an update then  the document can be sent to someone for updation

Regards


[Deepak_ Gupta]

**Comment by mizuni** [comment] 2017-04-04 12:00
@DeepakGuptaRelianceJio 
In order to share your IR.21 documents privately with GSMA members (including
operators and other partners such as us), please upload IR.21 documents to the
RAEX (Roaming Agreement Exchange) repository at raextools.com/raextools.

This will help maximize the availability of data to others working with your
subscribers to ensure a better experience. Thank you!

**Comment by DeepakGuptaRelianceJio** [comment] 2017-04-04 13:56
Hi Mike

Thanks. We are already sharing the IR21 documents at GSMA however the Jio customers continue to face issues on OTPs delivery.

Can you help expediting the configuration at google atleast

Attached is the latest document

Regards

Deepak Gupta

**Comment by kkeshava** [comment] 2017-04-26 10:26
Fixed in release 8.4.2.

**Closed by kkeshava** 2017-04-26 10:26 UTC
