### ISSUE TITLE
Timezones missing for 8001 2345 (EE)

### ISSUE THREAD

**Issue by gemal** [googlei18n/libphonenumber#1763] opened 2017-05-31 09:37 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): EE

Example number(s) affected ("+1 555 555-1234"): 8001 2345

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): tollfree

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=8001+2345&country=EE)

https://libphonenumber.appspot.com/phonenumberparser?number=8001+2345&country=EE
Time zone(s)	[Europe/Bucharest]

Missing timezones
fx Europe/Riga

**Comment by mizuni** [comment] 2017-06-06 12:51
Thanks for taking the time to file a bug report!

We use CLDR data for timezone identifiers and this mapping is working as they
specify, so we kindly suggest you file an issue with the CLDR team here:

http://unicode.org/cldr/trac/newticket

Closing this as working as intended from our end.

**Closed by mizuni** 2017-06-06 12:51 UTC
