### ISSUE TITLE
Validation issue with 15648050100 (US)

### ISSUE THREAD

**Issue by jtteh** [googlei18n/libphonenumber#1878] opened 2017-08-01 16:28 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): US

Example number(s) affected ("+1 555 555-1234"): +1 564 805-0100

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +1 564 XXX-XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.):  All

The cost, if applicable ("toll-free", "premium rate", "shared cost"):  All

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 
https://en.wikipedia.org/wiki/Area_code_564
https://www.verizonwireless.com/support/area-code-overlay-360-faqs/

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=15648050100&country=US)

**Comment by penmetsaa** [comment] 2017-08-02 02:32
Thank you for taking the time to improve libphonenumber!

This issue is a duplicate of #1875 . Closing this issue.

**Closed by penmetsaa** 2017-08-02 02:32 UTC
