### ISSUE TITLE
Validation issue with +94197-3X-XXXX (LK)

### ISSUE THREAD

**Issue by rassvetdk** [googlei18n/libphonenumber#1843] opened 2017-07-10 12:11 UTC
Country/region affected (e.g., "US"): LK - Sri Lanka

Example number(s) affected ("+1 555 555-1234"): +94197335555

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +94197-3X-XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Supposedly a mobile number

The cost, if applicable ("toll-free", "premium rate", "shared cost"): mobile/national call

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): http://www.srilankan.com/en/flying-with-us/contact-us

**Comment by kkeshava** [comment] 2017-07-11 06:20
@rassvetdk,
Thank you for taking the time to improve libphonenumber! For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

We were able to connect to +94197335555, but we can't find official evidence for the actual ranges that are valid. We can't support single numbers, we need context about the prefix that makes them valid.

Range +94197-XX-XXXX looks like Fixedline number because Mobile numbers in SriLanka start with prefix 7 i.e 7[0125-8] XXX XXXX. 
Do you still feel this is a Mobile number? Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment] 2017-07-17 07:40
@rassvetdk,
This issue is blocked on your or other GitHub contributors' input. Please help us find evidence that 197 is valid Mobile or Fixedline number. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by kkeshava** [comment] 2017-07-17 10:46
We've accepted this issue and will fix this in an upcoming release. 

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by keghani** [comment] 2017-07-17 21:10
To be clear, we'll support it as a fixed-line number. This is consistent with the website's listing of such numbers under "Telephone" and "Fax".

**Comment by kkeshava** [comment] 2017-07-18 10:04
We will be supporting prefix 1973 as fixedline number.

**Comment by SumathiSundara** [comment] 2017-08-03 12:15
Fixed in release 8.7.1

**Closed by SumathiSundara** 2017-08-03 12:15 UTC
