### ISSUE TITLE
+1 539 NPA XXXX

### ISSUE THREAD

**Issue by kputland** [googlei18n/libphonenumber#1534] opened 2017-01-26 22:53 UTC
Country/region affected (e.g., "US"): US/Oklahoma
Example number(s) affected ("+1 555 555-1234"):+1 539 NPA XXXX
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):+1 539 NPA XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.):
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):
https://www.nationalnanpa.com/area_code_maps/display.html?ok
http://www.allareacodes.com/539
http://www.newson6.com/global/story.asp?s=11748362

**Comment by kkeshava** [comment] 2017-01-30 05:51
Duplicate of #1527.

**Closed by kkeshava** 2017-01-30 05:51 UTC
