### ISSUE TITLE
Validation issue with +249121961467

### ISSUE THREAD

**Issue by anas-aldrees** [googlei18n/libphonenumber#1827] opened 2017-07-02 09:55 UTC
I have the following mobile numbers:

+543513116713
+522226727438
+542944894250
+249129271988
+249121961467
+249114436643

These are valid mobile numbers, but the library shows that they are a landline!

**Comment by penmetsaa** [comment] 2017-07-03 08:50
@anas-aldrees 
Thank you for taking the time to improve libphonenumber!

1. For Argentina and Mexico  phone numbers: +543513116713, +542944894250
 and +522226727438:
This is a known issue. Please take a look at the below listed FAQ.
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-is-this-number-from-argentina-ar-or-mexico-mx-not-identified-as-the-right-number-type

2. Sudan numbers: +249129271988, +249121961467 and +249114436643
ITU doc says that 12 XXX XXXX phone numbers are landline numbers.
https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000C40002PDFE.pdf

We have considered 11 XXX XXXX as fixed-line range based on the user report. Wikipedia says the same. ITU do not mention this range. https://en.wikipedia.org/wiki/Telephone_numbers_in_Sudan

Closing this issue as working as intended. Please reopen the issue if you have any official evidence that says these Sudan are mobile numbers. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Closed by penmetsaa** 2017-07-03 08:50 UTC
