### ISSUE TITLE
New 11 digit numbers in Brazil to be added

### ISSUE THREAD

**Issue by rzaryan** [googlei18n/libphonenumber#939] opened 2016-01-04 18:32 UTC
Currently libphone marks 11 digit Brazilian phone numbers as valid only if the first digit after the country code is 9. Recently Brazlian carriers added numbers such as +5548490420375 where the overall number is 11 digits long and the first number after the country code is a 4.

Validation needs to accommodate 11 digits Brazlian phone numbers where the first number after country code is a 4, as those are now in use by carriers in Brazil.

**Comment by mateusmoura** [comment] 2016-01-05 17:29
+1

**Comment by penmetsaa** [comment] 2016-01-07 07:48
@rzaryan and mateusmoura

Thank you for taking the time to improve libphonenumber!

We are supporting other 11 digit numbers that start with [2378] as well. Ex: +5522990420375. Brazil has been migrating from 10 to 11 digits by inserting a 9 before the last 8 digits. But the number you have mentioned do not have 9 before last 8 digits.

We were not able to connect to +5548490420375, please provide some other valid numbers. We are not able to find official evidence  as well.  We can't support single numbers, we need context about the prefix that makes them valid. Please share any official evidence you may have. See our <a href="https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence">guidelines</a>.

Are these numbers mobile / landline?

**Comment by mateusmoura** [comment] 2016-01-07 19:25
Hello,

some valid numbers:

 - 5531994772712
 - 55031994772712
 - 5531998563256
 - 55031998563256

Changed only numbers mobile others continue normal.

Then the mask must accept 10 or 11 digits.

Thanks! ;)

**Comment by rzaryan** [comment] 2016-01-07 21:07
@penmetsaa  Thanks for responding... I have not activated any of these numbers as I can't validate them yet via the libphone. They are all for sale within Twilio and I plan on buying a bunch of them for my Brazilian clients once they are added to the libphone. See attached screenshot within Twilio's interface for buying phone numbers to use in your applications.
![new brazil numbers for sale in twilio](https://cloud.githubusercontent.com/assets/13039869/12182819/a9d604a4-b558-11e5-858f-33bb0e018caf.PNG)

**Comment by dlyongemallo** [comment] 2016-01-08 14:32
@mateusmoura Are you reporting an unrelated issue? Every single one of the numbers you supplied is already identified as valid and mobile by the library.

**Comment by mateusmoura** [comment] 2016-01-08 21:04
Sorry @dlyongemallo 

the version in my project is older! Now it is working!

Thanks!

**Comment by keghani** [comment] 2016-01-11 11:42
@rzaryan 

The library strives to reflect the real world. +5548490420375 is not connecting so the library is working as intended when it says it's "invalid".

Please give us 11-digit numbers that start with 4 and are already active. You mentioned in the first comment that "those are now in use by carriers in Brazil", can you give examples?

**Comment by rzaryan** [comment] 2016-01-11 16:23
@keghani Twilio is a cloud communications vendor that sells phone numbers and allows developers to program what those phone numbers do -- be it for a IVR type of setup or for uses such as Uber facilitating text messaging between a driver and a person. They only sell valid phone numbers that actually work, and I wanted to make sure you had a good example to draw on when making this update.

I bought one of the new phone numbers from Twilio and manually set it up. If you call this number it should direct to one of our clients (Sheraton hotel in Salvador, State of Bahia, Brazil) 

+5548490420386

**Comment by keghani** [comment] 2016-01-12 17:40
@rzaryan +5548490420386 does not connect either.

**Comment by keghani** [comment] 2016-04-21 15:50
Closing as none of the reported numbers were valid, the library is working as intended.
Please open a new issue following the [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) if there are valid Brazil numbers that we need to support.

**Closed by keghani** 2016-04-21 15:50 UTC
