### ISSUE TITLE
validation issue with +861750382****

### ISSUE THREAD

**Issue by jackzzhll** [googlei18n/libphonenumber#1464] opened 2016-12-06 07:42 UTC

**Comment by kkeshava** [comment] 2016-12-06 12:10
Hi,
Thank you for taking the time to improve libphonenumber!

Can you please provide some more information about the issue? Is +861750382**** a mobile number? if so can you provide carrier details for this range?
We can't find official evidence for the actual ranges that are valid. We can't support single numbers, we need context about the prefix that makes them valid.
Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by jokerlee** [comment] 2016-12-08 15:04
i encounter this problem too,
see this wiki page (Chinese version, not English version, English version is out of date) [中国内地移动终端通讯号码](https://zh.wikipedia.org/zh-hans/%E4%B8%AD%E5%9B%BD%E5%86%85%E5%9C%B0%E7%A7%BB%E5%8A%A8%E7%BB%88%E7%AB%AF%E9%80%9A%E8%AE%AF%E5%8F%B7%E7%A0%81)

175 is a new mobile phone segment for China Unicom, we have a lot user with 175 phone numbers in db.

**Comment by penmetsaa** [comment] 2016-12-12 06:40
@jokerlee ,
Thanks so much for pointing us to wikipedia page. As wikipedia page is not an official source for phone numbers in China, we would like to check online whether these numbers are existing or not.
I have searched online but not able to find them. Can you share any such numbers or online references?

**Comment by jokerlee** [comment] 2016-12-12 10:05
<img width="233" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1501465/21095069/d066c188-c094-11e6-80eb-c84b985a3aff.png">
i can only provide numbers with some digits hidden due to privacy concern. all of these phone numbers have passed sms verification.

**Comment by penmetsaa** [comment] 2016-12-20 07:15
@jokerlee 
Thanks for providing all the details we need! We've accepted this issue; however, we are now in a release freeze period and may not be able to release this until the second week of January.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment] 2017-01-17 05:15
Fixed in release 8.0.1.

**Closed by kkeshava** 2017-01-17 05:15 UTC

**Comment by jokerlee** [comment] 2017-01-23 12:15
👍
