### ISSUE TITLE
+1 762 NPA XXXX

### ISSUE THREAD

**Issue by kputland** [googlei18n/libphonenumber#1536] opened 2017-01-26 23:00 UTC
Country/region affected (e.g., "US"): US/Georgia
Example number(s) affected ("+1 555 555-1234"):+1 762 NPA XXXX
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):+1 762 NPA XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.):
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):
http://www.allareacodes.com/762
https://www.nationalnanpa.com/pdf/NRUF/October_2014_NPA_Exhaust_Projections.pdf
https://www.nationalnanpa.com/area_code_maps/display.html?ga
https://en.wikipedia.org/wiki/Area_codes_706_and_762

**Comment by kkeshava** [comment] 2017-01-30 05:51
Duplicate of #1527.

**Closed by kkeshava** 2017-01-30 05:51 UTC
