### ISSUE TITLE
Add new NDC +22785 for Atlantique Telecom Niger (Moov)

### ISSUE THREAD

**Issue by NERTL** [googlei18n/libphonenumber#1866] opened 2017-07-20 17:21 UTC
Dear Colleagues,

Please we request to implement our new NDC : +22785 as per our latest IR21 attached.

looking forward your confirmation
I signed the CLA.

regards

**Comment by NERTL** [comment] 2017-07-20 17:21
I signed the CLA.

**Comment by penmetsaa** [comment] 2017-07-21 12:26
This is duplicate of #1785

**Comment by keghani** [comment] 2017-07-21 12:34
#1785 is no longer open. I've re-opened this so we can have a focused discussion here and summarize again what we still need in order to support this range.

@NERTL please do one of the following:

*   Upload the IR.21 document to the RAEX (Roaming Agreement Exchange) repository at raextools.com/raextools.
*   Sign the CLA. I cannot see one signed for you. Please follow [these instructions](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-authoritative-evidence). When done, we'll add you to our mailing list and you can private share the IR.21 doc.

**Comment by NERTL** [comment] 2017-07-21 12:58
@keghani ,
i already the CLA, if you need, i can send it here.

**Comment by keghani** [comment] 2017-07-21 13:15
That won't work, I need to see it on the system.
Which CLA did you sign? It doesn't appear to be propagating properly.
Was it the corporate CLA?

**Comment by keghani** [comment] 2017-07-21 13:16
Note that if you signed the corporate CLA, [that page](https://cla.developers.google.com/about) says:

`After the agreement is electronically signed, it will need to be reviewed by someone at Google. [...] This normally takes a few days.`

**Comment by NERTL** [comment] 2017-07-21 14:38
Yes, i saw like need to be reviewed by Google, but yesterday i receive the pdf CLA file from Google.

**Comment by keghani** [comment] 2017-07-21 14:53
Please see the section titled "How do I add authorized contributors for my company?"

You will need to add the email address to your GitHub account so I can send an email there.

**Comment by NERTL** [comment] 2017-07-21 17:55
Hi,
i added the email adress on the Github account.
Thanks

**Comment by keghani** [comment] 2017-07-24 07:34
On the @NERTL GitHub account? I don't see it.

Please ensure you are set up correctly by following our instructions for [providing non-public
evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence). Go back and re-read everything and make sure you followed all the steps.

Without the correct setup, we cannot accept non-public evidence. We cannot provide additional support for CLA signing, we don't know any more than what's already in the documentation we linked to.

**Comment by NERTL** [comment] 2017-07-26 09:36
@keghani ,
i put my professionnal email adress, i added also for my others collegues.
or you i put my gmail adress mail?
Thanks,

**Comment by keghani** [comment] 2017-07-26 09:46
Hi @NERTL,

The information is in the instructions at https://cla.developers.google.com/about, which is linked from our CLA guidelines. Please see the part about "How do I add authorized contributors for my company?"

**Comment by NERTL** [comment] 2017-07-27 09:22
Dear @keghani,
i added the adress mail in the group gmail.
Thank you.

**Comment by NERTL** [comment] 2017-08-17 18:55
Dear @keghani ,
please can you check if there is any requirement, we are still waiting to share our document.
Thanks,

**Comment by keghani** [comment] 2017-08-18 12:16
Hi @NERTL,

My response from last time is still relevant. We don't have a CLA in our system for this username.
Please read https://cla.developers.google.com/about and follow the all instructions from there carefully. We cannot provide additional support, we don't know any more than what's already in this link.

If we don't get a CLA signature we'll close this as infeasible since we cannot accept private documents without it.

**Comment by NERTL** [comment] 2017-08-27 07:20
Hi @keghani , 
i write the Google support adress mail, to check out the issue of why CLA is not on the system.
i will come back.
Thanks

**Comment by NERTL** [comment] 2017-09-12 16:59
I signed the CLA.

**Comment by penmetsaa** [comment] 2017-09-14 09:58
@NERTL ,
I still cannot see one signed for you.
Please ensure you are set up correctly by following [our instructions](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-authoritative-evidence) for providing non-public
evidence. Please reopen the issue if you are able to see your CLA entry in below page.
https://cla.developers.google.com/clas

**Closed by penmetsaa** 2017-09-14 09:58 UTC

**Comment by NERTL** [comment] 2017-09-14 14:50
HI All, 
here is the screenshot.

**Comment by NERTL** [comment] 2017-09-14 15:40
Hi, looks like i'm not allowed to reopen.
i need to send you screenshot my CLA  from https://cla.developers.google.com/clas
Thanks,

**Comment by penmetsaa** [comment] 2017-09-15 06:46
Oh OK. Looks like GitHub no more allows general users of libraries to re-open the issues. Strange! You can still attach the screenshot by selecting "Attach files.." option, which is below the field where you enter your comments. Will reopen once everything looks good.

**Comment by keghani** [comment] 2017-09-15 09:14
We generally don't want to open files attached on GitHub. They should either be public or provided following the steps for [providing authoritative evidence](https://github.com/googlei18n/libphonenumber#java-code). But that requires a CLA signature.

@NERTL can you please see if there's someone with support capacity who can help you at the CLA links?
I'll try to find one as well.

**Comment by keghani** [comment] 2017-09-15 09:19
In the meantime:

@NERTL there is an alternative solution. Could you upload the IR.21 document to the RAEX (Roaming Agreement Exchange) repository at [raextools.com/raextools](raextools.com/raextools)? If you do, just ping this thread and we'll be able to view it.
