### ISSUE TITLE
Fixed-line currently showing as MOBILE 08xxxxxxxx (VN)

### ISSUE THREAD

**Issue by koyyew** [googlei18n/libphonenumber#2154] opened 2018-03-01 09:01 UTC
Country/region affected (e.g., "US"): VN

Example number(s) affected ("+1 555 555-1234"): 0888456168, 0886685558, 0888777378

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 08xxxxxxxx

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Fixed-line (currently showing as MOBILE, which is wrong)

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0888456168&country=VN)

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0886685558&country=VN)

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0888777378&country=VN)

http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000E40002PDFE.pdf

**Comment by kkeshava** [comment] 2018-03-01 10:00
@koyyew,
Thank you for taking the time to improve libphonenumber! For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

As per the ITU doc Pg 3/15, all the fixedline numbers starting with 8 was renumbered as 28 on 2017-6-17. So all the fixedline numbers start with 2 now. Mobile numbers starting with prefix 8 is added based on IR 21 docs from various carriers. Please check wikipedia link, all 88 series are assigned to Vinaphone 
https://en.wikipedia.org/wiki/Telephone_numbers_in_Vietnam#Mobile_telephone_numbers.

Closing this as working as intended; if you would like to reopen, please share any evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Closed by kkeshava** 2018-03-01 10:00 UTC
