### ISSUE TITLE
Australian mobile number range missing - +61484xxxxxx

### ISSUE THREAD

**Issue by doancaonghia** [googlei18n/libphonenumber#792] opened 2015-08-15 08:30 UTC
Please add the +61484xxxxxx number range.

e.g. +61484344260 is a valid mobile number in Australia.

Thanks 
Nghĩa

**Comment by roes** [comment] 2015-08-18 15:51
Thank you for your report, we had already been made aware of this and it will be part of the next release.

**Comment by roes** [comment] 2015-08-18 15:52
Duplicate of https://github.com/googlei18n/libphonenumber/issues/766

**Closed by roes** 2015-08-18 15:52 UTC
Labels: duplicate
