### ISSUE TITLE
Validation issue with +551999118778 (BR)

### ISSUE THREAD

**Issue by bromanov** [googlei18n/libphonenumber#1038] opened 2016-03-26 02:28 UTC
Country/region affected (e.g., "US"): BR

Example number(s) affected ("+1 555 555-1234"): +551999118778

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

Supporting evidence - https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B551999118778&country=BR)

**Comment by rzaryan** [comment] 2016-03-28 19:16
This may be related to https://github.com/googlei18n/libphonenumber/issues/1041

The issue is that the inclusion of the 9 between the 2-digit area code and 8-digit number is now being included on a larger range of numbers than before. 

Link to the context in wiki: https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil#Ninth_digit_for_mobile_numbers

**Comment by padmaksha** [comment] 2016-03-29 05:27
@bromanov

We can't connect to +551999118778 (10 digit number).
Since 2012, Brazil has been migrating from 10 to 11 digits by inserting a 9 before the
last 8 digits. For the range 19 this migration is complete . So numbers in  range 19 is 11 digits long. 
Though we can connect to number +5519 9 99118778 (11 digits)
We are closing this issue as working as intended as the fix is to insert the additional "9" as shown above. If this fix does not work for you, please describe your use case. Thank you!

**Closed by padmaksha** 2016-03-29 05:27 UTC

**Comment by fredguth** [comment] 2016-05-31 20:49
As it was explained, Brazil has been migrating to 11 digits since 2012. On May 29th 2016, the numbers from area codes 61, 62, 63, 64, 65, 66, 67, 68, 69 have completed this migration.
At this moment, +5561999213100 is a valid Number in Brazil but libphonenumber still validates it as a wrong number:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B5561999213100&country=55&geocodingLocale=br

Also, on November 6th 2016, the area codes 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 53, 54 and 55 will be migrated.

Here is the official post in Portuguese.
http://www.anatel.gov.br/setorregulado/index.php/perguntas-frequentes?catid=1

**Comment by lararennie** [comment] 2016-06-01 08:03
Hi Fred,

Your original post didn't have a 6 in it. With a 6 we validate it as
expected. Is this just a typo on your end? Do you want the 6 or not? (The
link you included shows we think it's valid too...)

Lara
31. mai 2016 10.50 p.m. skrev "Fred Guth" <notifications@github.com>:

**Comment by fredguth** [comment] 2016-06-01 11:37
Hi Lara,
Maybe I should have open in a new issue (I am not the original poster).  The original post didn't include the 61 area code (as the other 6x codes) because this migration is happening in different dates for different area codes. On May, 26th, 2016,  6x area codes changed. By the end of the year (November 6th) all Brazilian area codes will have completed the migration.

With the number  +55 61 999213100     I get ``isValidNumberForRegion()===false``.  I was expecting that to be true.

**Comment by keghani** [comment] 2016-06-01 12:12
We have a discussion on Brazil in the discussion group, please consider joining (I think you have to join to see the post): https://groups.google.com/forum/#!topic/libphonenumber-discuss/4AdkgJpuU6k

Basically we're aware of the Brazil renumbering changes and we have 3 kinds of mobile ranges.

1. Ranges which have completed transition: 1x
Once we consider a range to have completed transition it will only be considered valid with the 9th digit.
We have had this behavior for over a year and will not go back to considering the old (8-digit) 1x numbers valid.

2. Ranges which are undergoing transition: 2x, 3x, 6x, 7x, 8x, 9x
We consider both 8- and 9-digit numbers valid in these ranges (the old and new numbers).
We're aware that some of the old numbers are no longer connecting, but we're consciously supporting the entire ranges because some old numbers are actually still connecting, depending on the carrier. We will probably stop supporting the old numbers in the foreseeable future but this is not a high priority.

3. Ranges which are yet to start transition: 4x, 5x
As mentioned, these are not yet supported in Brazil with the 9th digit, so our library only considers the 8-digit numbers valid. We will add the 9-digit 4x and 5x numbers as valid before November 6th.

@fredguth Try entering BR as the region, that gives true for isValidNumberForRegion(): http://libphonenumber.appspot.com/phonenumberparser?number=%2B55+61+999213100&country=BR

**Comment by lararennie** [comment] 2016-06-01 12:15
This is because you don't have "BR" as the region, you have 55 which we
consider invalid. Try the demo with "BR" and it'll work.

(you should also read the javadoc about isValidNumber and
isValidNumberForRegion to understand the difference with these functions.)

2016-06-01 13:38 GMT+02:00 Fred Guth <notifications@github.com>:

**Comment by fredguth** [comment] 2016-06-02 10:35
Thanks a lot @keghani and @lararennie.
