### ISSUE TITLE
Support for US toll free numbers with area code 833

### ISSUE THREAD

**Issue by LewG02** [googlei18n/libphonenumber#1615] opened 2017-03-07 16:30 UTC
Hi! I'm not sure if this is in progress, but on April 22nd of this year the FCC plans to make 833 a valid area code for US toll free numbers.  I was wondering if there are plans to add this area code before, on, or after April 22nd.  Thanks!

**Comment by kkeshava** [comment] 2017-03-09 05:50
Hi,
Thanks for providing all the details we need! We've accepted this issue and as the reported change won't go into effect within the next couple of weeks, we will fix this in an upcoming release around the scheduled date for the change.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment] 2017-03-20 04:58
Fixed in release 8.3.3.

**Closed by kkeshava** 2017-03-20 04:58 UTC

**Comment by kkeshava** [comment] 2017-04-10 11:44
This is actually working as intended; 833 is already marked by our library as TOLL FREE. To check the latest behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B18332123456&country=US) (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
