### ISSUE TITLE
Validation issue with 097xxxxxxxxx (NL) mobile m2m numbers: TOO_LONG

### ISSUE THREAD

**Issue by adebree** [googlei18n/libphonenumber#1231] opened 2016-07-25 14:52 UTC
Country/region affected (e.g., "US"):
NL
Example number(s) affected ("+1 555 555-1234"):
097002801234
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):
097xxxxxxxxx
The type of the number(s) ("fixed-line", "mobile", "short code", etc.):
mobile m2m (machine-2-machine)
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
shared cost
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): 
097 + 9 digits are introduced in the Netherlands because of the shortage of the 'regular' mobile range starting with 06 + 8 digits. 097 number are intended for 'location independed machine to machine' purposes
https://www.t-mobile.nl/zakelijk/097-nummers
https://www.acm.nl/nl/onderwerpen/telecommunicatie/telefoonnummers/informatie-over-097--en-06-nummers/zorg-voor-het-juiste-gebruik-van-097-nummers/

**Comment by penmetsaa** [comment] 2016-07-26 09:09
@adebree ,
Thank you for taking the time to improve libphonenumber!
This issue is a duplicate of #680 . Closing this issue.
Please contribute on the existing issue to add to our understanding

**Closed by penmetsaa** 2016-07-26 09:09 UTC
