### ISSUE TITLE
Validation issue with +97335470144 ( )

### ISSUE THREAD

**Issue by bahtaxi** [googlei18n/libphonenumber#1168] opened 2016-06-20 09:08 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"):  

Example number(s) affected ("+1 555 555-1234"): +97335470144

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B97335470144&country=+)

**Comment by bahtaxi** [comment] 2016-06-20 09:09
hi , this is a valid number but twill dosnot verfiy it

**Comment by padmaksha** [comment] 2016-06-21 07:55
This issue is duplicate of  [#1166](https://github.com/googlei18n/libphonenumber/issues/1166) and will be tracked there . Closing this issue here.

**Closed by padmaksha** 2016-06-21 07:55 UTC
