### ISSUE TITLE
format international numbers with preferred Carrier code (dialing out of Brazil to another country)

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#503] opened 2014-12-03 20:42 UTC
Imported from [Google Code issue #503](https://code.google.com/p/libphonenumber/issues/detail?id=503) created by [kohangel](https://code.google.com/u/118014392314681731740/) on 2014-08-16T12:40:20.000Z:

---

<b>What steps will reproduce the problem?</b>
1.missing formatINTERNATIONALNumberWithPreferredCarrierCode() method for use to dial out of Brazil 
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

currently, there is a method formatNationalNumberWithPreferredCarrierCode, which works well for formatting Brazilian numbers, for dialing within Brazil.

however, there is no other method that we can use to add the preferred Carrier Code for International numbers.

<b>What version of the product are you using? On what operating system?</b>
geocoder 2.12, libphonenumber 6.1

<b>Please provide any additional information below.</b>

For example, to call the number 555-0123 in Washington, D.C. (area code 202), United States (country code 1), using TIM as the chosen carrier (selection code 41), one would dial 00 41 1 202 555 0123.

**Comment by keghani** [comment] 2017-07-19 17:02
Dupe of #245

**Closed by keghani** 2017-07-19 17:02 UTC
Labels: priority-medium, type-defect
