### ISSUE TITLE
Add new 7 series numbers in OMAN OM

### ISSUE THREAD

**Issue by dmsherazi** [googlei18n/libphonenumber#1341] opened 2016-09-15 15:28 UTC
There is a new mobile 7xxxxxxx number series along side 9xxxxxxx .

- Country/region   affected ("OM"):
- Example number(s) affected ("+968 7xxxxxxx"): 
- The phone number range(s) to which the issue applies ("+968 7xxxxxxx"):
- The type of the number(s) ( "mobile")

the numbers are 8 digit and the regex below will work
`"7[19]\\d{6}|7(?:0[1-9]|[1-9]\\d)\\d{5}"
`
http://libphonenumber.appspot.com/phonenumberparser?number=0096877775603&country=OM
should be valid which is currently not a valid number

- **Supporting evidence**
[News On the official website of telecom provider providing the numbers](http://ooredoo.om/Ooredoo/MediaCentre/PressReleases/Detail/tabid/1192/ArticleId/3318/Ooredoo-Launches-New-7-Series-Numbers.aspx)

**Comment by kkeshava** [comment] 2016-09-20 06:54
Hi,
Thank you for taking the time to improve libphonenumber!

We already support 71xxxxxx and 79xxxxxx as per the ITU doc https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200009F0003PDFE.pdf. However the ITU doc mentions that 71xxxxxx is assigned to Omantel and 79xxxxxx is assigned to Ooredoo, but the newspaper article mentions that both are assigned to Ooredoo, could you please clarify on this?

It seems that you want to expand this to cover the whole 7 series, as per your suggested reg-ex and the newspaper article but we are not able to find numbers for other prefixes (i.e 72, 73, 74, 75, 76, 77, 78)  online. Please share any working numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by dmsherazi** [comment] 2016-09-20 08:13
@kkeshava  the document you have should be considered the official one. The news report should not be considered as official. There is just one issue and that is that the 7 series numbers are not broken into 7xxx xxx pattern while the 9 series are

**Comment by dmsherazi** [comment] 2016-09-27 15:30
Although the numbers are added the parse function wont parse numbers so a number starting with 7 wont be split into two 4 digit numbers as is done with numbers starting with 9

**Comment by kkeshava** [comment] 2016-09-29 10:26
Hi,
Are you having a parsing or a formatting issue? It's not clear from the above description.

I can confirm that we parse the 71 and 79 numbers as valid and format them in groups of 4. Please see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=79000000&country=OM).

Maybe you need to provide the region code (OM) if you're passing in the raw input without a country calling code and a plus sign (+968).

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further. Please also see the [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#checklist-before-filing-an-issue) for how to check whether a number is working as intended.

**Closed by kkeshava** 2016-09-29 10:26 UTC
