### ISSUE TITLE
Validation issue with 9890008405 (IN)

### ISSUE THREAD

**Issue by sachinshelke** [googlei18n/libphonenumber#1180] opened 2016-06-28 14:36 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 9890008405

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=9890008405&country=IN)

**Given Number showing carrier as _`Airtel`_ however it is of _`Vodafone`_.**

As per the parent carrier, it is right. but number has been port before year but still it is showing Airtel.

**Comment by penmetsaa** [comment] 2016-07-01 06:16
@sachinshelke 
Thank you for taking the time to improve libphonenumber!

For the regions (like India) that support number portability, we return the original carrier for the supplied number. Information on porting of individual numbers is not be available in the library. You can check whether a region supports number portability or not using  method [isMobileNumberPortableRegion(regionCode)](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L3275)

Closing this issue as it is working as intended.

**Closed by penmetsaa** 2016-07-01 06:16 UTC
