### ISSUE TITLE
Avoiding NumberFormatException

### ISSUE THREAD

**Issue by egemenhamutcu** [googlei18n/libphonenumber#1777] opened 2017-06-07 10:31 UTC
Some SDKs give us country codes in lower case. I have to call .toUpperCase() to avoid NumberFormatException. This work around should be in the SDK.

```
try {
    PhoneNumber swissNumberProto = phoneUtil.parse(swissNumberStr, "us");
} catch (NumberFormatException e) {
    // catches the exception
}
```

**Comment by lararennie** [comment] 2017-06-07 21:23
Hi,

Yes, that's by design. Otherwise:
-- we have to make sure every single method in our API does this, and if we ever forget in one of them clients get very strange results
-- we have to do the upper-case work every time, whereas you can do it once and then you have an upper-case region code to use whenever you do something

We have long-term plans to use a class for the region code (similar to how we do for testing), and this would convert from a string regardless of its case, but we have other things on our plate so that will take a while to happen.

The parse exception you have to catch in any case, because the phone number might be bad input. In the case with the region code, you can do it on your side as a preventative check. Some SDKs might not give you a two-letter country code at all anyway.

We have documented this at the top of the Java and C++ files, so it shouldn't be too much of a surprise.

Closing this as WAI, but feel free to join the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by lararennie** 2017-06-07 21:23 UTC
