### ISSUE TITLE
Share-cost numbers (FR) validation issue

### ISSUE THREAD

**Issue by aguerin** [googlei18n/libphonenumber#1497] opened 2017-01-05 17:35 UTC
Hi there,

I've got an issue with some shared-cost services phone numbers in FR. More details :

Country/region affected : FR
Example number(s) affected : 0 812 10 10 10 - +338 12 10 10 10
The phone number range(s) to which the issue applies : +338-120-XX-XX-XX -> +338-180-XX-XX-XX
The type of the number(s) : It's shared-cost services numbers (paid services)
Supporting evidence :

[Failure Demo](https://libphonenumber.appspot.com/phonenumberparser?number=%2B33812+10+10+10)
[Phone Numbers in France](http://whitepages.fr/phonesystem) (and search "810" in it)
[Arcep informations](http://www.arcep.fr/index.php?id=8146&L=1#c9625) (in FR - not translated)

Thank you,
Best Regards,

**Comment by kkeshava** [comment] 2017-01-09 07:56
@aguerin,

Thanks for providing all the details we need! We will add 812 XX XX XX to 818 XX XX XX to shared cost. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment] 2017-01-17 05:11
Fixed in release 8.0.1.

**Comment by aguerin** [comment] 2017-01-17 08:18
Thanks, you're efficient :)

**Comment by kkeshava** [comment] 2017-01-31 10:43
@aguerin,
The numbering plan given in [Arcep](http://www.arcep.fr/index.php?id=8146&L=1#c9625) seems to be unclear. It does not differentiate between the numbers which are actually assigned and which are available. 
After verifying in http://www.arcep.fr/index.php?id=interactivenumeros&no_cache=1, we found that only 812 XX XX XX is assigned but other prefixes i.e 81[3-8] XX XX XX are not yet assigned.

We had faced few similar cases in the past, so we decided to support only those numbers for which we get an authoritative detailed source and at least one diallable number. 
Would it be possible for you to provide any working numbers for 81[3-8] XX XX XX ranges?

**Comment by aguerin** [comment] 2017-01-31 17:38
@kkeshava Hi, I'm sorry I don't have any working numbers for the range 81[3-8], perhaps there is a phone operator around this post who can help ^^, more seriously, the only phone number we've needed to validate was +33810101010 and we saw that all the range 81[2-8] was unvalidate too, we just suppose that they are available working phone without checking all of them.. but we're wrong apparently. (and I don't find any working french phone number in the range 81[3-8], but it's possible that my research was wrong too)

**Comment by kkeshava** [comment] 2017-02-01 11:36
@aguerin,
Thanks for checking :) We could not find any working number in the range 81[3-8] so we will support only 812 for now.

**Comment by SumathiSundara** [comment] 2017-02-06 05:29
Fixed in release 8.2.0

**Closed** 2017-02-06 06:22 UTC
