### ISSUE TITLE
+1 470 NPA XXXX

### ISSUE THREAD

**Issue by kputland** [googlei18n/libphonenumber#1530] opened 2017-01-26 22:42 UTC
Country/region affected (e.g., "US"): US/Atlanta
Example number(s) affected ("+1 555 555-1234"): +1 470 NPA-XXXX
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):+1 470 NPA-XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.):
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): http://www.allareacodes.com/470

**Comment by kkeshava** [comment] 2017-01-30 05:50
Duplicate of #1527.

**Closed by kkeshava** 2017-01-30 05:50 UTC
