### ISSUE TITLE
    PhoneNumber numberProto = phoneUtil.parse("#0015128178842",""); throwing numberparseexception

### ISSUE THREAD

**Issue by Yavdhesh** [googlei18n/libphonenumber#1840] opened 2017-07-06 06:35 UTC
I am getting this issue:-

 NumberParseException was thrown: Error type: INVALID_COUNTRY_CODE. Could not interpret numbers after plus-sign.

**Comment by penmetsaa** [comment] 2017-07-06 13:16
@Yavdhesh,

Thank you for using libphonenumber!

Library is working as intended here. It throws "Error type: INVALID_COUNTRY_CODE. Missing or invalid default region.". https://libphonenumber.appspot.com/phonenumberparser?number=%230015128178842

This is because while calling the parse method, you have passed empty string for default region. This is the region from where the number is dialled from. Unless the input number is in E.164 format (Ex: +1 12345 67890), library relies on default region to know to which country the numbers belongs to. Only after the right region is computed the parse() API can do further processing. You can check below page for sample code:
https://github.com/googlei18n/libphonenumber/blob/master/README.md#quick-examples

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by penmetsaa** 2017-07-06 13:16 UTC
