### ISSUE TITLE
Formatting fails for mobile prefix 151 in German numbers

### ISSUE THREAD

**Issue by beriedel** [googlei18n/libphonenumber#1158] opened 2016-06-13 09:21 UTC
Hi,

Country/region affected: Germany
Example number(s) affected: +49 1511910397
The phone number range(s) to which the issue applies: +49 151 xxxxxxxxxxx
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
Supporting evidence/description:
When formatting number to NATIONAL the format-method returns "1511910397" instead of 
"0151 1910397". "151" is a valid mobile prefix and should therefore be recognized as one. This worked as desired until version 5.5.

http://libphonenumber.appspot.com/phonenumberparser?number=1511910397&country=DE&geocodingLocale=de

https://en.wikipedia.org/wiki/List_of_dialling_codes_in_Germany

**Comment by penmetsaa** [comment] 2016-07-13 09:22
@beriedel 
This issue is blocked on your or other GitHub contributors' input. Please help
us find evidence that 151 (10 digit range) is valid, or provide an example number from a
business website or similar. Otherwise we don't have enough information to
fix the issue and may have to close it as infeasible.

**Comment by beriedel** [comment] 2016-07-13 17:56
Hi,

it took me some time to find out where the number originated. As it turned out, it was in fact an invalid number that somehow ended up in our database (well, at least the original number that brought up the issue did, not the pseudonymized example in the threat ;-) ). Sorry for the inconvenience and thanks for quick response.

**Comment by penmetsaa** [comment] 2016-07-15 04:07
@beriedel 
Thanks for checking this. :) 
As per below official document, numbers starting with 15 can only be 11 digits long.
(not less or more) http://www.bundesnetzagentur.de/SharedDocs/Downloads/EN/BNetzA/Areas/Telecommunications/NumberManagement/MobileServices/Mobileservices_Numbering%20Plan200913.pdf?__blob=publicationFile&v=1
Closing this issue as working as intended.

**Closed by penmetsaa** 2016-07-15 04:07 UTC
