### ISSUE TITLE
Validation issue with 491622897306 (DE)

### ISSUE THREAD

**Issue by mattdarwin** [googlei18n/libphonenumber#1374] opened 2016-09-30 14:04 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): DE

Example number(s) affected ("+1 555 555-1234"): 491622897306

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 
The affected range is probably "491[67].*"
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 
MOBILE
The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

This is my friend's number, and he lives in Germany!

When parsing the number "491622897306" for Germany, it comes up as FIXED_LINE (also CountryCodeSource is FROM_DEFAULT_COUNTRY when I think it should be FROM_NUMBER_WITHOUT_PLUS_SIGN) 

By contrast, a similar number in UK format: "447717512961" works fine. 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=491622897306&country=DE)

**Comment by mattdarwin** [comment] 2016-09-30 14:26
`PhoneNumberUtil pnu = PhoneNumberUtil.getInstance();
		PhoneNumber pn = pnu.parse("447717512961", "GB");	//passes
		assertEquals(PhoneNumberType.MOBILE, pnu.getNumberType(pn));	//pass
		pn = pnu.parse("491622897306", "DE");
		assertEquals(PhoneNumberType.MOBILE, pnu.getNumberType(pn));	//fails
                pn = pnu.parse("01622897307", "DE");
		assertEquals(PhoneNumberType.MOBILE, pnu.getNumberType(pn));	//pass`

**Comment by lararennie** [comment] 2016-10-03 12:00
This is the same as #1335, which itself is a dupe of #750 and probably many others.
Short version: add "+" if you *know* you are starting with a country code. If you give it to us without the +, it is not clear to the library whether the plus is missing, or the 0, so we prefer the local option of the two ways of parsing it.

**Closed by lararennie** 2016-10-03 12:00 UTC
Labels: duplicate

**Comment by giggsey** [comment] 2016-10-03 13:09
@lararennie Can this be added to an FAQ?

**Comment by lararennie** [comment] 2016-10-03 13:22
Yes! Great idea. Will do.
