### ISSUE TITLE
Possible exception in loading/parsing metadata.

### ISSUE THREAD

**Issue by Mortimer2013** [googlei18n/libphonenumber#1249] opened 2016-08-04 10:58 UTC
I encountered the error below in Android N several times not 100% occurence.
The version 7.0.11.
Does any one know something about this?

java.lang.RuntimeException: cannot load/parse metadata: /com/android/i18n/phonenumbers/data/PhoneNumberMetadataProto_LC
	at com.android.i18n.phonenumbers.MultiFileMetadataSourceImpl.loadMetadataFromFile(MultiFileMetadataSourceImpl.java:128)
	at com.android.i18n.phonenumbers.MultiFileMetadataSourceImpl.getMetadataForRegion(MultiFileMetadataSourceImpl.java:80)
	at com.android.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:1985)
	at com.android.i18n.phonenumbers.PhoneNumberUtil.getRegionCodeForNumberFromRegionList(PhoneNumberUtil.java:2082)
	at com.android.i18n.phonenumbers.PhoneNumberUtil.getRegionCodeForNumber(PhoneNumberUtil.java:2072)
	at com.android.i18n.phonenumbers.PhoneNumberUtil.getNumberType(PhoneNumberUtil.java:1911)
	at com.android.i18n.phonenumbers.geocoding.PhoneNumberOfflineGeocoder.getDescriptionForNumber(PhoneNumberOfflineGeocoder.java:262)
	...
Caused by: java.util.zip.ZipException: invalid block type
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:170)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2316)
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2800)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:302)
	at com.android.i18n.phonenumbers.MultiFileMetadataSourceImpl.loadMetadataFromFile(MultiFileMetadataSourceImpl.java:110)
	... 96 more

**Comment by keghani** [comment] 2016-08-09 15:10
Thanks for reporting @Mortimer2013!

Looking at the stack trace it's being thrown here: https://github.com/googlei18n/libphonenumber/blob/libphonenumber-7.0.11/java/libphonenumber/src/com/google/i18n/phonenumbers/MultiFileMetadataSourceImpl.java#L128

The IOException is happening when constructing the ObjectInputStream in line 110. We don't want to recover from it so we throw the RuntimeException, that much is working as intended.

I don't know why the `in = new ObjectInputStream(source);` call is resulting in a ZipException only sometimes. My guess is it's transient, dependent on the system load. Hopefully with the [recent refactoring](https://github.com/googlei18n/libphonenumber/commit/bff8c8ca8d689738f3d567a78f6b5988114c1991) we killed this issue if it was a threading problem in the library.

Do you have other ideas? Anything else we can do to fix this in the library?

**Comment by keghani** [comment] 2016-08-09 15:12
Please also report with the relevant product, they could have an issue on their side (e.g. something overwriting the stream while another thread tries to access it).

**Comment by cuihuawei1981** [comment] 2016-08-14 13:32
HI keghani 
 I don't think it is caused by multi-thread process, the data will only to load in first used,it would not to be loaded by  multi-thread. is it ?

**Comment by keghani** [comment] 2016-08-15 08:21
Multiple threads could attempt to read simultaneously before the data has been loaded (and after, though this is less likely to cause problems).

Since this is not an issue in the current library we can't fix it. I'll close the issue and I would suggest that the app look into debugging this (e.g. start by logging more information when this error occurs) to see how to fix it on the app side. The library is working as intended when it does not recover from an IOException.

**Closed by keghani** 2016-08-15 08:21 UTC
