### ISSUE TITLE
A PhoneNumber parsed with parse() returns wrong CountryCodeSource

### ISSUE THREAD

**Issue by alexeiarshavin** [googlei18n/libphonenumber#1218] opened 2016-07-19 03:32 UTC
Example: 
`PhoneNumberUtil.getInstance().parseAndKeepRawInput("04671 2718", "DE").getCountryCodeSource()`

returns `FROM_NUMBER_WITH_PLUS_SIGN`
This is wrong, there was no plus sign.

It took me a while to figure out what to do.

 I see a couple of issues here, and offer some suggestions what can be done.
1. The PhoneNumberUtil.parse() method does not mention this. If the behavior going to stay, put it in the Javadoc.
2. I vote for a change. Return null or Optional.absent() if the information is not available. Personally I don't see why it's not available, somewhere along the way the method finds it out anyway. Also hasCountryCode() returns true, which again is wrong.
3. Point to the parseAndKeepRawInput() method which produces a PhoneNumber that then handles getCountryCodeSource() correctly.
4. Document on getCountryCodeSource() that it might return a default, depending on how the number was created. Also for hasCountryCode(), the returned true can be wrong.
5. Document on http://libphonenumber.appspot.com/ which Version of the library it is using. That's good for other use cases also "why does it work there but not in my code". Also write there which API code it uses. It probably goes for parseAndKeepRawInput() and not the more intuitive parse().
6. Consider creating a separate class called PhoneNumberParser (and a PhoneNumberMatcher, and a PhoneNumberValidator, ...)

**Comment by lararennie** [comment] 2017-06-30 14:43
Sorry about taking so long to reply, this slipped through the cracks.

So actually it does *not* return FROM_NUMBER_FROM_PLUS_SIGN. I can't reproduce this: it returns FROM_DEFAULT_COUNTRY. I imagine that you mean you called parse() and got that, not parseAndKeepRawInput() (which would be a much more serious bug!!).

1/3. I will change the documentation of parse to mention the fields it doesn't fill in, and what the alternative is.

2. You say "hasCountryCode" -> this is intended, because it has one (49 for Germany). I presume you mean hasCountryCodeSource(). This already returns false, which is correct. We could have an enum of UNSPECIFIED though if you call getCountryCodeSource() without checking whether it is there or not. We don't want to store the real value because then you can't compare two parsed phone numbers easily, because they would differ if they were parsed from different input originally.

4. I think you are confused. hasCountryCode != hasCountryCodeSource. Will look at if there is anything that needs to be done documentation-wise if we add another enum though.

5. Anyone can see the code for the demo, but we could make it more user-friendly by explicitly saying what methods are being used. Will make an update. Documenting what version of the lib it is using is annoying as we would have to update that every release; we currently have opted for updating the readme.md instead which now has the version number.

6. We would like to do this, but a big library rewrite isn't in scope right now.

**Comment by keghani** [comment] 2017-07-18 15:46
Was fixed in 8.6.0.

**Closed by keghani** 2017-07-18 15:46 UTC
