### ISSUE TITLE
Validation issue: German numbers are at least 7 digits on mobiles (DE)

### ISSUE THREAD

**Issue by sokke90** [googlei18n/libphonenumber#1264] opened 2016-08-12 13:37 UTC
Country/region affected (e.g., "US"): DE
Example number(s) affected ("+1 555 555-1234"): starting from all two-digit numbers except "00"
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): This is no valid number

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=45&country=DE)

In German (DE) country code setting, all short numbers (starting from 2 digits, except "00") were flagged as Possible Number, even if they are not possible. 

Of course, there are some short numbers, and it should be detected as short number and not as possible number:

Shortest possible numbers in Germany are, as wikipedia also states:

> 110 - Police
> 112 - Fire brigade, ambulance, rescue services (also the universal emergency number in the EU)
> 115 - Civil services; requests are either answered directly or forwarded to the competent authority.
> 116 xxx - Harmonised services of social value
> 118 xx - Directory assistance
> 19 222 - Non-emergency medical transports. This number is not an emergency number but a local number assigned uniformly in all geographic area codes. This requires dialling the area code from mobile phones or other non-geographic lines.

Those numbers should be validated like 911 in US:
http://libphonenumber.appspot.com/phonenumberparser?number=911&country=US

and not like this:
http://libphonenumber.appspot.com/phonenumberparser?number=112&country=DE

Also, wikipedia states:

> There used to be no fixed lengths for either area codes or subscriber telephone numbers, meaning that some subscriber numbers may be as short as two digits. 

I could not find any other resource supporting this, so I assume this is not a correct statement - but, I suspect, somebody took it for granted and implemented it.

In official German document [2], p.33 you can find the following:

The shortest possible dialable number (except the special numbers) is 5 digits

> Teilnehmerrufnummer (5-9 Stellen)
> But - importantly - this only comes to effect if you call from a landline AND are in the same local region ("Ortsnetz"); if you are calling from a mobile, you have to call for a landline:
- prefix 0 (1 digit)
- Ortsnetzkennzahl (local prefix) (2-5 digits)
- Teilnehmerrufnummer (subscriber number) (5-9 digits)

which makes the whole number at least 8 digits long - as said - from mobile phone.

Historically, there might be some shorter numbers left (as said in [2], too), mostly in the format:
- prefix "0"
- Ortsnetzkennzahl (local prefix) (2 digits)
- big company special number, e.g. "123" + extension, e.g. "0"
  this would be 030 123-0.

so this makes a total of 7 digits, which I would recommend as the least digits to detect a phone number.

Shorter numbers may be available, but I cannot find any information about this and according to [2], you cannot get them any more.

So, probably, you have to divide between landline and mobile phone.
Let's say, we have a number 34 56 78, which _can_ be a valid number; but only on a landline phone and never on a mobile phone. I suspect that this tool is primaily used for mobile phones (Android), so you can be sure that this number will never be valid on a mobile device.

"34 56 78" validates as
http://libphonenumber.appspot.com/phonenumberparser?number=34+56+78&country=DE

Why all of this? Because Android even detects a time; like every message like "lets meet at 12:30" is detected as two phone numbers: "12" and "30", which is annoying. 

Also in Google Calendar, some dates were marked as Phone numbers, like "Birthdays on 12. August", and the "12" is clickable as phone number.

This affects all of the recent (around 3 years) android phones in Germany language setting.

Sources:
[1] [Wikipedia: Telephone numbers in Germany](https://en.wikipedia.org/wiki/Telephone_numbers_in_Germany)
[2] [Official document from Bundesnetzagentur](http://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Nummerierung/Nummerierungskonzept/Nummerierungskonzept2014.pdf;jsessionid=875070E686F3B176DBF601DCF3A8B87C?__blob=publicationFile&v=1)

**Comment by padmaksha** [comment] 2016-08-22 05:29
@sokke90 

Thank you for taking the time to improve libphonenumber!

According to our research local numbers in Germany (where it is dialed without area code) can be minimum two digits in length. If you look at [ITU](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000510002PDFE.pdf)  doc. for Germany , page 5  you can see [this](https://screenshot.googleplex.com/JTcTR5SHoHL) , which is 2103 area code, plus 2 digit local number (minimum). 
You can also find three digit local numbers online.
Phone number annotations in Android / Google Calendar etc. don't solely depend on libphonenumber. The teams responsible for these things either already use or are considering techniques to reduce the rate of positives, such as using other annotators (time, date, ISBN, ...).
Also can you please let us know where do you see in "lets meet at 12:30" annotated with 2 phone numbers. Is it in Gmail or Hangouts ? Is the text actually in German (e.g. "Treffen wir uns um 12:30"?) and is the UI language set to German?

**Comment by sokke90** [comment] 2016-08-23 16:17
Thank you for your response!

First, I cannot use the link (https://screenshot.googleplex.com/JTcTR5SHoHL), as I seem to be stuck in a Google login loop.
Second, on the [ITU](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000510002PDFE.pdf) link, I find on page 5 for 2103 area code: min: 6; max: 11

Still, even if you have some legacy numbers as short as 2 digits (which I have never heard of in my life, living in Germany, and which I cannot find in the ITU document or on the sources from my original post), the local numbers cannot be dialed on mobile phones without dialling the area code, which assumes that every non-short number has to start with an area code or mobile code, which have to be preceded with a "0" or with the country code ("+49").
You can only dial local (landline) numbers without area code from a landline, when both landlines are in the same area code.


On the ITU doc, also on the first page on "General Survey", you can find that the least amount of digits is "3"; which, I guess, refers to special numbers (112, 115), or not? I'm actually not sure.

Because this document is also a little confusing, as it does not seem to take into account the leading "0". A mobile number in Germany looks e.g. like this: 0176 123 456 78 (12 digits) or like this: +49 176 123 456 78 (same number of digits as my number, but of course, not the same number). The ITU documents will tell you that this number has exacly 11 digits, and does not seem to count the leading "0" in (see page 3).

Find some screenshots from Hangouts, Signal, Messenger (Google) and Calendar here:
https://drive.google.com/open?id=0B6rjtplUST0xZTNzVjZJT1NWM2M

Issue not present in Inbox or Gmail, I guess they display HTML mails.

I am always talking about German (Germany) language setting on Android. Not reproducible with German (Austria), German (Suisse) and German (Liechtenstein). Good that I checked, I will use those language settings now. Not as annoying as German (Germany) setting.

**Comment by lararennie** [comment] 2016-08-23 16:59
Note Gmail uses our library to detect phone numbers, but they look for
valid numbers, not possible.

I don't know if hangouts even use us or why they use possible mode; in most
locales that doesn't make sense.

01 shouldn't be possible though I don't think; I feel we should fix that.

23. aug. 2016 6.18 p.m. skrev "sokke90" <notifications@github.com>:

Thank you for your response!

First, I cannot use the link (https://screenshot.googleplex.com/JTcTR5SHoHL),
as I seem to be stuck in a Google login loop.
Second, on the ITU
<https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000510002PDFE.pdf> link,
I find on page 5 for 2103 area code: min: 6; max: 11

Still, even if you have some legacy numbers as short as 2 digits (which I
have never heard of in my life, living in Germany, and which I cannot find
in the ITU document or on the sources from my original post), the local
numbers cannot be dialed on mobile phones without dialling the area code,
which assumes that every non-short number has to start with an area code or
mobile code, which have to be preceded with a "0" or with the country code
("+49").
You can only dial local (landline) numbers without area code from a
landline, when both landlines are in the same area code.

On the ITU doc, also on the first page on "General Survey", you can find
that the least amount of digits is "3"; which, I guess, refers to special
numbers (112, 115), or not? I'm actually not sure.

Because this document is also a little confusing, as it does not seem to
take into account the leading "0". A mobile number in Germany looks e.g.
like this: 0176 123 456 78 (12 digits) or like this: +49 176 123 456 78
(same number of digits as my number, but of course, not the same number).
The ITU documents will tell you that this number has exacly 11 digits, and
does not seem to count the leading "0" in (see page 3).

Find some screenshots from Hangouts, Signal, Messenger (Google) and
Calendar here:
https://drive.google.com/open?id=0B6rjtplUST0xZTNzVjZJT1NWM2M

Issue not present in Inbox or Gmail, I guess they display HTML mails.

I am always talking about German (Germany) language setting on Android. Not
reproducible with German (Austria), German (Suisse) and German
(Liechtenstein). Good that I checked, I will use those language settings
now. Not as annoying as German (Germany) setting.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/libphonenumber/issues/1264#issuecomment-241788813>,
or mute the thread

**Comment by sokke90** [comment] 2016-08-24 11:45
@lararennie 
Thank you for your response.

I thought that Android is using that library for detecting phone numbers.
I have to add: all numbers I described are *not* possible numbers. There are no numbers on mobile devices that are possbile when they have less than 7 digits (except short numbers, but they were not marked in Android, as I checked). 

Also, I want to take your attention to this number again:
http://libphonenumber.appspot.com/phonenumberparser?number=34+56+78&country=DE
... getting the formatting result...
Formatting Results
E164 format +49345678
Original format	 345 678
National format 0345 678
International format	+49 345 678

I can tell you that from 345678 number it is not possible to switch to +49 345678 number! It is not interchangeable. 0345 678 and +49 345678 is interchangeable! The "original format" and the "national format" are *not* interchangeable. They are completely different numbers!
In original format, it is a local landline number; only dialable from a landline, and only within that region. The national format, is, as the tool states correctly, a number in "Halle Saale". From the original format you cannot conclude the region the phone number is in; because it depends on the region your landline phone is in.

So I can safely say that this parsing result is wrong.

**Comment by penmetsaa** [comment] 2017-07-26 04:22
I'll close this issue as it is working as intended as per the evidences we have. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.  If there is something specific we should fix see [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) for how to report. 

To answer some questions:

Yes, 345678 might be connecting to local network here if 345 is not a valid area code. This is a valid national fixed-line number as per the ITU doc. https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000510004PDFE.pdf (page 24). So 345 678 is interchangeable with +49345678 unless it is mandatory to place national prefix (0) OR the country code (+49) when dialing a fixed-line number (of other area) from fixed-line phone. Do you think so ? If not, how are fixed-line telephone networks in Germany figuring out to check the national network (not the local network) when 345678 is dialled ? 

In case for formating a number for mobile dialing you can use APIs like [PhoneNumberUtil.formatNumberForMobileDialing()](https://github.com/googlei18n/libphonenumber/blob/e24208e0c63fd06d5cf9da26bb885d2977453c46/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L1374)

>> I suspect that this tool is primarily used for mobile phones (Android), so you can be sure that this number will never be valid on a mobile device.

Libphonenumber is not intended for only mobile phones usage but for all products that deal with phone numbers in general. So this is the reason why we made 2 digit local only phone numbers are possible earlier. This includes cases like fixed-line to fixed-line local dialing as well. If you use [PhoneNumberUtil.isPossibleNumberWithReason()](https://github.com/googlei18n/libphonenumber/blob/e24208e0c63fd06d5cf9da26bb885d2977453c46/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2590) it returns the enum which mentions the reason as well.

As we are not able to find subscriber numbers less than 3 digits, we have increased possible number length to 3 digits from 2 digits. The numbers like 12 will not longer will be reported as valid numbers.
https://www.qiagen.com/ca/about-us/press-and-media/contact-m/: +49 2103 29 0

**Closed by penmetsaa** 2017-07-26 04:22 UTC
