### ISSUE TITLE
+2491 numbers in Sudan

### ISSUE THREAD

**Issue by ArtemTkachuk** [googlei18n/libphonenumber#1554] opened 2017-02-06 13:12 UTC
This is a mobile numbers, not fixed-line. Contacted with the provider, 6mln of users in Sudan. Nexmo confirmed information. http://libphonenumber.appspot.com/ provides wrong information.

![unnamed](https://cloud.githubusercontent.com/assets/25585615/22648280/eef78632-ec86-11e6-994b-6bb53c0409f0.png)
![unnamed-1](https://cloud.githubusercontent.com/assets/25585615/22648285/f494b326-ec86-11e6-8c83-39ce8ea59786.png)
![unnamed-1](https://cloud.githubusercontent.com/assets/25585615/22648287/f61319ae-ec86-11e6-92dc-0c101593f98e.png)

Please, unmark numbers starting with +2491 as fixed line numbers

**Comment by SumathiSundara** [comment] 2017-02-07 10:27
Thank you for taking the time to improve libphonenumber! 

We believe that numbers beginning with 1 are fixed-line due to the official ITU [Communication of 31.III.2015](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000C40002PDFE.pdf).

If you think these are mobile numbers please share any official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by ArtemTkachuk** [comment] 2017-02-07 11:40
Thank you for answering. 

Official ITU says that NDCs 93 and 03 are fixed lines only. In our case we talk about +249 1 numbers. 

We are able to send text messages to these numbers, which wouldn't possible in case these numbers were fixed line (see screenshots in the previous messages).

Numbers starting with +2491 belong to sudani.sd provider.

**Comment by SumathiSundara** [comment] 2017-02-08 03:49
Please refer to second page of official ITU [Communication of 31.III.2015](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000C40002PDFE.pdf).

It states that "Service Type Identifier (1 for fixed lines, 9 for mobile)".

**Comment by SumathiSundara** [comment] 2017-02-13 12:01
Thank you for using libphonenumber!

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by lararennie** [comment] 2017-02-13 13:00
I'd also like to point out that some fixed-line phones can receive sms in some way, e.g. by transcribing them and reporting them as voicemail...

**Comment by ArtemTkachuk** [comment] 2017-02-13 13:03
Thank you. 
Will try to contact Ministry of Communication in Sudan and clarify the issue one more time.

**Comment by ArtemTkachuk** [comment] 2018-01-25 07:51
Hello team!

Finally I achieved to get a letter from Sudatel Telecommunication Group Co. LTD stating that numbers starting with 

+24910
+24911
+24912

are mobile phone numbers in Sudan. Please, check attachment. Hope, this clarifies.
![sudatel letter](https://user-images.githubusercontent.com/25585615/35376797-b34baf1c-01bd-11e8-8883-75b40252854a.jpg)

**Comment by penmetsaa** [comment] 2018-01-25 10:43
@ArtemTkachuk,
Thank you for taking the time to improve libphonenumber!

Please see our guidelines for [providing evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

In particular, we request a publicly available URL or that you sign the CLA and
(after getting whitelisted) share non-public evidence with the mailing list only
readable by core team members.

**Comment by penmetsaa** [comment] 2018-02-01 06:56
@ArtemTkachuk,
Please sign the CLA. Ensure you are set up correctly by following our instructions for [providing non-public evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence). Without the correct setup, we cannot accept non-public evidence.

**Comment by ArtemTkachuk** [comment] 2018-02-01 07:35
Hi!

Thank you for the guidance. I did create a group and made a post https://groups.google.com/forum/#!topic/mobile-phone-numbers-in-sudan/91ZaRDqNcg4

Hope, this is what is needed

**Comment by penmetsaa** [comment] 2018-02-05 09:43
No, this is not the right setup. Please ensure you are set up correctly by following our instructions for [providing non-public evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by ArtemTkachuk** [comment] 2018-02-07 08:36
**I signed the CLA. Anything posted here is made public**

Please accept my previous evidence supporting the fact that the starting with

+24910
+24911
+24912

are mobile phone numbers in Sudan.

**Comment by penmetsaa** [comment] 2018-02-07 10:23
@ArtemTkachuk,
We could not find your CLA signature. Please ensure you are set up correctly by
following our instructions for [providing non-public evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

Without the correct setup, we cannot accept non-public evidence. We cannot
provide additional support for CLA signing, we don't know any more than what's
already in the documentation we linked to.

It looks like this step is the instructions is not done. Could you please check it once?
>> If the email address you use in the Individual CLA is not already associated with that GitHub account, add it.

**Comment by ArtemTkachuk** [comment] 2018-02-07 12:37
I added dev@multibrains.org to my account. I used this one while signing CLA. Please, check it out now.

Sorry for bothering, it is first time I'm making commit to the repository.

**Comment by penmetsaa** [comment] 2018-02-09 10:13
@ArtemTkachuk,
We are still not able to find your signed CLA. Could you please check the instructions from the start? So that you have not missed anything. Thanks :)

**Comment by penmetsaa** [comment] 2018-02-12 07:58
@ArtemTkachuk,
As we are not able to find the signed CLA, we will be not able to consider the attached scanned copy as evidence. We will be adding support to 10 XXX XXXX phone numbers as we are able to find valid phone numbers online.

For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

**Comment by penmetsaa** [comment] 2018-02-13 10:00
Hi,

This issue will be fixed in an upcoming release.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch
the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified
when we publish the new release notes there.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Closed by penmetsaa** 2018-02-13 10:00 UTC
