### ISSUE TITLE
Nigeria - new prefix

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#786] opened 2015-08-12 09:54 UTC
Etisalat Nigeria is now using +234 908. Example number: +234908174536x

**Comment by roes** [comment] 2015-08-19 14:39
Awaiting supporting documentation.

**Comment by pblv** [comment] 2015-10-22 15:41
I can confirm this. Please also check:
https://en.wikipedia.org/wiki/Telephone_numbers_in_Nigeria

**Comment by mihaelacr-google** [comment] 2015-10-23 07:54
Hi!

Do you have any other source of documentation apart from Wikipedia? A government/carrier website  or a newspaper? Thanks!

**Comment by pblv** [comment] 2015-10-23 08:01
http://www.ncc.gov.ng/index.php/index.php?option=com_content&view=article&id=113&Itemid=102

**Comment by mihaelacr-google** [comment] 2015-10-23 08:04
This seems to be a duplicate of https://github.com/googlei18n/libphonenumber/issues/863.

**Comment by andyst** [comment] 2015-10-26 14:57
Closing this as duplicate of
https://github.com/googlei18n/libphonenumber/issues/863

**Closed by andyst** 2015-10-26 14:57 UTC
Labels: duplicate
