### ISSUE TITLE
List of 36 timezones (of NANPA countries) are returned for Trinidad and Tobago phone number

### ISSUE THREAD

**Issue by akfernun** [googlei18n/libphonenumber#1964] opened 2017-10-14 16:57 UTC
When pulling timezone information for a number in Trinidad and Tobago, it returns many timezones, some of which do not seem feasible. Please see http://libphonenumber.appspot.com/phonenumberparser?number=%2B18687804765&country=TT. 

You'll see that it is returning 36 different results for timezone information. I believe that the correct result should be "America/Port_of_Spain". 

Please let me know if any more information is needed.

**Comment by penmetsaa** [comment] 2017-10-24 09:10
@akfernun,
Thank you for taking the time to improve libphonenumber!
We accept this issue. As it is duplicate of #991, closing this issue. We will update #991 once it is fixed.

**Closed by penmetsaa** 2017-10-24 09:10 UTC
