### ISSUE TITLE
Validation issue with +18766139137

### ISSUE THREAD

**Issue by serargz** [googlei18n/libphonenumber#2030] opened 2017-11-27 21:12 UTC
Country/region affected (e.g., "US"): JM

Example number(s) affected ("+1 555 555-1234"): +1 876 613-9137

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +1 876 613-XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): landline

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 
- http://realtorsjamaica.org/nmcms.php?snippet=search&p=broker&brokerid=268
- http://www.visitjamaica.com/cellar-8
- https://www.universityandcollegeambassadors.com/contact-uca

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B18766139137)

**Comment by SumathiSundara** [comment] 2017-11-28 07:01
We can't connect to +1 876 613 9137, 876-613-3684, (876) 613-5934 and 6134200. 

Here is our official evidence: https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200006C0001XLSE.xls prefix 613 is missing. 

Closing this as working as intended; if you would like to reopen, please share
any working numbers or evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by serargz** [comment] 2017-11-28 20:28
@SumathiSundara The prefix 613 is definitely valid. I've made phone calls to all the 4 phone numbers. I hear the ring tones in all of them and got answers:

+1 876 613 9137
+1 876 613-3684
+1 876 613-5934
+1 876 613-4200

I've not been able to find an "official" document including the prefix, but I'm unsure about how updated is the one you shared above (it says **Commmunication of 26.IX.2006**). Plus, the web is full of references to phone numbers with the 613 prefix. More examples below:

- +1 876 613-0902, +1 876-613-0903 (http://gastoncorporation.com/contact-us)
- +1 876 613-0166 (https://www.findyello.com/Jamaica/Partners-Interventional-Centre-of-Jamaica/profile)
- +1 876 613-4101, +1 876-613-6392 (https://www.popajamaica.com/contact-us)
- +1 876 613-6465 (http://www.strictlyeventsjamaica.com/template.php?p=contactus)
- +1 876 613-0007 (http://www.sotcargoja.com/services/)
- +1 876 613-3110 (http://enchantedvillasjamaica.com/contact-us/)
- +1 876-613-5934 (https://www.facebook.com/cellar8kgn)

**Comment by SumathiSundara** [comment] 2017-11-29 06:35
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by keghani** [comment] 2017-12-01 13:09
This will be fixed in the next release.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish the new release notes there.

**Closed by keghani** 2017-12-01 13:09 UTC
