### ISSUE TITLE
Validation issue with 0860004000 (FR)

### ISSUE THREAD

**Issue by Zehir** [googlei18n/libphonenumber#1510] opened 2017-01-16 10:31 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): FR

Example number(s) affected ("+1 555 555-1234"): 0860004000 (+33 860004000)

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 
0806XXXXXX to 0809XXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line

The cost, if applicable ("toll-free", "premium rate", "shared cost"): same as fixed-line

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 
http://www.neopost-services.fr/sites/neopost-services.fr/files/files/cnx-ols-ij-25-ha-sa.pdf
This number is the auto number for the autopost machine
http://www.telecom-infoconso.fr/les-numeros-08-et-les-numeros-courts/
Search: "Numéros spéciaux vocaux à tarification banalisée"

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0860004000&country=FR&geocodingLocale=fr-FR)

**Comment by penmetsaa** [comment] 2017-01-17 14:45
@Zehir,

Thank you for taking the time to improve libphonenumber!

The example number you provided (0860004000) does not fall under the range (0806XXXXXX to 0809XXXXXX) that you have mentioned.

We already support 0806XXXXXX to 0809XXXXXX phone numbers as valid UAN numbers.

As for 0860004000, according to the official evidence at http://www.arcep.fr/index.php?id=8789, 0860 and 0868 phone numbers are used for internet access. libphonenumber does not support internet access numbers - we will only add numbers with a human at the other endpoint.

I'll close this issue as it's working as intended. 
https://libphonenumber.appspot.com/phonenumberparser?number=0899123456&country=FR
https://libphonenumber.appspot.com/phonenumberparser?number=0809123456&country=FR

**Closed by penmetsaa** 2017-01-17 14:45 UTC
