### ISSUE TITLE
Validation issue with 2931666 (BM)

### ISSUE THREAD

**Issue by dleshem** [googlei18n/libphonenumber#1966] opened 2017-10-16 06:31 UTC
Country/region affected: BM

Example number(s) affected: 2931666

The type of the number: fixed-line

Within Bermuda, local (7-digit) numbers work. You don't need to enter the 441 area code -
 but Libphonenumber seems to require the area code.

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=2931666&country=BM)

**Comment by kkeshava** [comment] 2017-10-17 08:41
Hi,
The 7-digit numbers are diallable locally, and the library does consider them possible. However, they do not fit the definition of valid because without the area code it is not possible for the library to canonicalize these numbers.
I'll close this as it's not an issue with the library (it is working as intended). Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by kkeshava** 2017-10-17 08:41 UTC
