### ISSUE TITLE
Telefonica Costa Rica New Numbering Range not being validated

### ISSUE THREAD

**Issue by TelefonicaCR** [googlei18n/libphonenumber#1470] opened 2016-12-09 20:54 UTC
Movistar / Telefonica Costa Rica customers with number range 506 6400 2000 to 506 6500 1999 are not being able to activate new Twitter and other apps.  They receive error message that hte number is not valid for the country Costa Rica.

Kindly, please add this range to your library ASAP.
Yanci Alvarado

**Comment by kkeshava** [comment] 2016-12-12 10:18
Hi,

Thanks for providing all the details we need! We've accepted this issue; however, we are now in a release freeze period and may not be able to release this until the second week of January.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by TelefonicaCR** [comment] 2016-12-12 15:04
This is an urgent request, please be advised that we can not wait until January.  Kindly, please escalate this request to Giovanni Stella - CEO for Central America.

In addition, please advise what source for Numbering Plan for Costa Rica you are using as it is not update thus generating customer complaints as they can not activate google account and dowload apps or if app is downloaded can not activate new account as telephone number is not validated.

regards, Yanci Alvarado.  Interconnection Manager

**Comment by keghani** [comment] 2016-12-15 12:35
We apologize for the inconvenience that our end of year freeze has caused. This is to safeguard users against unexpected outages and other issues while we have less team coverage due to the winter holidays.

If you cannot wait until the next release in January and are able to make code changes to your product, you may be able to resolve this validation issue by having a more lenient check. isPossibleNumber() will quickly guess whether a number is possible by only using length information rather than actual number block information.

Note we had previously made an announcement a month ahead of this freeze.
To be notified of future announcements, please join our mailing list: https://groups.google.com/forum/#!forum/libphonenumber-discuss

**Comment by TelefonicaCR** [comment] 2017-01-09 19:33
Please provide status of numbering range update for Costa Rica: 506 6400 2000 to 506 6500 1999

**Comment by kkeshava** [comment] 2017-01-10 07:00
@TelefonicaCR,
We are planning to have a release this week. We will be updating the bug once it is fixed.

**Comment by TelefonicaCR** [comment] 2017-01-16 14:53
Please confirm the update has been made.  Thank you.

**Comment by kkeshava** [comment] 2017-01-17 05:08
Fixed in release 8.0.1.

**Closed by kkeshava** 2017-01-17 05:08 UTC
