### ISSUE TITLE
Brazilian Number Updates (Nov 6th)

### ISSUE THREAD

**Issue by kryan2288** [googlei18n/libphonenumber#1434] opened 2016-11-16 16:20 UTC
Issue: 
Need confirmation that 13 digits will be allowed when using Brazilian area code 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 53, 54 and 55.

Pre - Nov 6th validation was successful on mobile number 554164415481.
Post Nov 6th mobile number 554164415481 became 5541**9**64415481 and validation failed.

This additional 9 was added to the majority of Brazilian mobile numbers with the above prefixes and is causing validation to fail on any number this occurred to. MobileNumber format in Brazil now has all mobile numbers starting with nine and it is nessesary that regardless of prefix that these numbers pass validation.

**Comment by keghani** [comment] 2016-11-16 16:45
This is a duplicate of https://github.com/googlei18n/libphonenumber/issues/1217 and already fixed.

Please check the demo to see whether a number range is working as intended before filing an issue. See our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) for details.

**Comment by keghani** [comment] 2016-11-16 16:45
If a number is failing validation then the product should use the latest version of libphonenumber. This is fixed as of 7.7.4.

**Closed by keghani** 2016-11-16 16:45 UTC

**Comment by kryan2288** [comment] 2016-11-16 16:46
Thanks for the quick response I will look into this.

Kevin Ryan | Associate Product Manager
Office: 317-524-2832
Mobile: 440-829-2926
