### ISSUE TITLE
Validation issue with 767845175 (IN)

### ISSUE THREAD

**Issue by farooq82** [googlei18n/libphonenumber#2160] opened 2018-03-05 09:46 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 767845175

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=767845175&country=IN)

**Comment by penmetsaa** [comment] 2018-03-06 00:41
Thank you for taking the time to improve libphonenumber!

We can't connect to +91 767845175 We support 10 digit long numbers for the prefix 767X while the specified number is 9 digits long. Demo result: https://libphonenumber.appspot.com/phonenumberparser?number=7678451750&country=IN

We are not able to find 9 digit numbers with this prefix online. Closing this as working as intended; if you would like to reopen, please share any working numbers or official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Closed by penmetsaa** 2018-03-06 00:41 UTC
