### ISSUE TITLE
INVALID_COUNTRY_CODE for BR trying to parse a DDI number

### ISSUE THREAD

**Issue by rromeroar** [googlei18n/libphonenumber#1979] opened 2017-10-23 09:29 UTC
INVALID_COUNTRY_CODE when using a correct Brazil one (BR) when trying to parse a valid DDI

http://libphonenumber.appspot.com/phonenumberparser?number=005521967506838&country=BR

Using other region code works as usual

**Comment by penmetsaa** [comment] 2017-10-23 11:25
@rromeroar,

Thank you for taking the time to improve libphonenumber!

We support 0055 as international dialling prefix for Brazil. Below official page says that 55 carrier selection code is used for "Adyl Net Telecomu-nicações Ltda". And Wikipedia says that same carrier selection codes are used for national and international dialling. Ex: 0055 and 055
http://pesquisa.in.gov.br/imprensa/servlet/INPDFViewer?jornal=1&pagina=87&data=12/05/2015&captchafield=firistAccess.
https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil (See Long distance dialling and Internatonal calls sections)

We already support 21967506838 as valid BR mobile number. See our [demo result](https://libphonenumber.appspot.com/phonenumberparser?number=21967506838&country=BR). The issue here is with the dialling sequence. As per international dialling format, valid CC need to be placed after international prefix i.e 0055 in this case.

Do you think 55 is used as carrier selection code in Brazil? Are you able to connect to 21967506838 mobile number when dialling 00 55 21967506838? Please share any supporting evidences. See
our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by rromeroar** [comment] 2017-10-23 12:28
Hi @penmetsaa , thank you for your answers

I understand that dialing to call that number must be preceded by a carrier code to be a valid number for a call. 

But we are trying to use libphonenumber to check the validity of a number to send a SMS, and in that scenario afaik carrier code doens't apply. Does the libphonenumber library support that kind of checks? Can be used in that scenario? 

Thanks in advance

**Comment by penmetsaa** [comment] 2017-10-24 05:32
@rromeroar,
Yes, libphonenumber supports validity checks for the input number that is in international dialling format. In this case, the right defaultCountry(from which region the number is being dialled) has to be provided. Ex: input:005521967506838 , defaultCountry: IN works as international dialling prefix for India is 00.

International dialling Format: <international_dialling_prefix> + <country_code> + <national_subscriber_number>.

**Comment by rromeroar** [comment] 2017-10-24 07:21
@penmetsaa Yes, but using BR as country code the error reported is "INVALID_COUNTRY_CODE. Country calling code supplied was not recognised", that is, at least, misleading.

http://libphonenumber.appspot.com/phonenumberparser?number=005521967506838&country=BR

**Comment by penmetsaa** [comment] 2017-10-24 07:38
@rromeroar,
This is because 0055 is considered as one of the international dialing prefix in BR along with other carrier codes. Ex: In India it is 00. As mentioned above, after international dialling prefix, a valid country code need to be present. More details in above comments. Can you please answer the question in my first comment? Without these details, library is working as intended.

About international prefix: See [phonemetadata.proto](https://github.com/googlei18n/libphonenumber/blob/master/resources/phonemetadata.proto#L182)

**Comment by keghani** [comment] 2017-10-24 07:39
I think maybe this FAQ might clear up some confusion? [Why wasn't 00 parsed the same as +?](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-wasnt-00-parsed-the-same-as-)

**Comment by penmetsaa** [comment] 2017-10-25 11:08
@rromeroar,
Do you say that 00 is a valid international prefix in Germany?

**Comment by penmetsaa** [comment] 2017-10-27 05:55
@rromeroar,
This issue is blocked on your or other GitHub contributors' input. Please help
us find evidence if you think that 00 is a valid international prefix in Brazil.
Otherwise we don't have enough information to fix the issue and may have to
close it as infeasible.

**Comment by rromeroar** [comment] 2017-10-30 12:22
Hi @penmetsaa 

I'll show the use case (maybe the libphonenumber library is not for the purposse we want)
--

Currently in Brazil mobile network, the SIMs has an application that, when activated, it shows a dialog to request the default carrier code to be used in case of a DDD or DDI call without it:

https://www.mrsimcard.com/tips/images/vivo2.jpg
http://brazilianexperience.com/english-what-is-ddd-and-ddi/

If user dials a number like 005411XXXXXXXX , then if prefered carrier code 11 is used, then the call is going to be placed via 00115411XXXXXXXX

Also the destination calling 00115411XXXXXXXX and 00155411XXXXXXXX is the same, but using a different carrier code

--

Imagine some user has a contact saved with a number and he is using is to call and also he wants to send SMS to him. 

For our case, we want to know which contacts has valid numbers to send sms and with provider example it doesnt work.

**Comment by penmetsaa** [comment] 2017-11-03 16:43
@rromeroar,

Thanks so much for explaining the use case in detail.

The reported phone number (5411XXXXXXXX) is not a valid one in BR.
https://libphonenumber.appspot.com/phonenumberparser?number=541101234567&country=BR

0011 is not considered as right carrier selection code. Or is it just a sample number that you have provided?

If user number is saved with right carrier selection code (or national prefix i.e 0) followed by valid number libarary WAI. See: 
https://libphonenumber.appspot.com/phonenumberparser?number=04240123456&country=BR
https://libphonenumber.appspot.com/phonenumberparser?number=02140123456&country=BR

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by penmetsaa** 2017-11-03 16:43 UTC
