### ISSUE TITLE
Validation issue with +8801868502015 (88)

### ISSUE THREAD

**Issue by jahidp** [googlei18n/libphonenumber#1809] opened 2017-06-24 18:23 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 88

Example number(s) affected ("+1 555 555-1234"): +8801868502015

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B8801868502015&country=88)

**Comment by kkeshava** [comment] 2017-06-27 05:21
@jahidp,
Thank you for using libphonenumber!
For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

This is actually working as intended; +8801868502015 is already marked by our library as Mobile number in Bangladesh (+880). We do not have any country having country code as 88. 
To check the latest behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B8801868502015&country=88) (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)). Thus we don’t see this as a validation issue. The number is already considered valid. 

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by kkeshava** 2017-06-27 05:21 UTC
