### ISSUE TITLE
Kenya - new mobile prefixes

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#816] opened 2015-09-11 12:37 UTC
79[0-2] - Safaricom
77[67] - Telekom Kenya

**Comment by mihaelacr-google** [comment] 2015-09-11 14:31
Can you please provide us with some official documentation? Carrier docs, government docs or other official sources are OK.

**Comment by andyst** [comment] 2015-09-11 19:56
79 (Safaricom) is already handled, will be in next release.

That part is a dupe of: https://github.com/googlei18n/libphonenumber/issues/804.

For 77[67] we need evidence, as requested by @mihaelacr-google .

**Comment by alecx** [comment] 2015-09-11 20:46
Already sent documentation for all tickets.

**Comment by andyst** [comment] 2015-09-12 09:05
No docs received. We received an email but it's got an empty body and no attachments.

**Comment by andyst** [comment] 2015-09-14 08:18
Got it, thanks.

**Comment by penmetsaa** [comment] 2017-03-22 07:37
This is fixed.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B254+777+010+000

**Closed by penmetsaa** 2017-03-22 07:37 UTC
