### ISSUE TITLE
Validation issue with  +31 70 189 147

### ISSUE THREAD

**Issue by jianping-roth** [googlei18n/libphonenumber#1178] opened 2016-06-28 01:18 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 

Example number(s) affected ("+1 555 555-1234"):  +31 70 189 147

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=+%2B31+70+189+147)

**Comment by penmetsaa** [comment] 2016-06-28 14:27
Thank you for taking the time to improve libphonenumber!
This issue is a duplicate of #1177. Closing this issue.

**Comment by lararennie** [comment] 2016-06-28 15:24
Just checking: I don't know that it is a duplicate, that issue started with "60" in the national number, this starts with "70"? I assume the intention is to be a different number?

Jianping, if you did indeed mean to file this bug separately, we need more information from you.

Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by jianping-roth** [comment] 2016-06-28 20:21
This is not a real phone number. I looked up http://dialcode.org/Europe/Netherlands/ and found 70 is a valid city code and a Dutch phone number can be either 6 or 7 digits in length.

**Comment by penmetsaa** [comment] 2016-06-30 04:10
@jianping-roth 

We support 9 digit 70 (fixed-line range) numbers for Netherlands. 
Below official evidence also confirms same.
http://wetten.overheid.nl/BWBR0010198/2015-07-15 (The official evidence counts the national prefix 0 in the length)

We are not able to find 8 digit 70 range numbers online. Please provide online references of any working numbers or official evidence that mentions this range and length.

**Comment by penmetsaa** [comment] 2016-07-05 03:37
@jianping-roth ,
I'm closing this issue as per your confirmation in #1177. 8 digit 70 range is not valid phone number range in Netherlands.

**Closed by penmetsaa** 2016-07-05 03:37 UTC
