### ISSUE TITLE
New Number Ranges for Reliance Jio

### ISSUE THREAD

**Issue by DeepakGuptaRelianceJio** [googlei18n/libphonenumber#2088] opened 2018-01-15 05:31 UTC
Dear All

Please update the new number ranges for Jio in your systems. Updated IR21 document attached alongwith
[IR21INDJX_2018-01-11-RJIL_IR21-Document..pdf](https://github.com/googlei18n/libphonenumber/files/1630480/IR21INDJX_2018-01-11-RJIL_IR21-Document.pdf)

**Comment by andyst** [comment] 2018-01-15 09:15
This issue / contributions is blocked on the CLA check. Please read through the instructions. It's supposed to be self-service.
Please let us know if there is an issue with the CLA process. Thanks.

**Comment by andyst** [comment] 2018-01-15 09:30
Actually, the 2018-01-11 Reliance Jio IR.21 is already in RAEX. The issue is no longer blocked then.

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347),
which we're currently testing.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss)
to be notified of the Maven release's completion, or watch the GitHub repository
at https://github.com/googlei18n/libphonenumber to be notified when we publish
the new release notes there.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by andyst** [comment] 2018-01-15 10:29
The issue will be fixed in the next release (probably by end of next week).

Closing the issue now. You can track the releases as described in my previous comment.

**Closed by andyst** 2018-01-15 10:29 UTC
