### ISSUE TITLE
12xx in Italy

### ISSUE THREAD

**Issue by Raffaele74** [googlei18n/libphonenumber#1892] opened 2017-08-07 09:50 UTC
Hi.
With number 12xx I view in ITU-Table (you use it) lenght 4 digit.
It is right (exemple http://www.1254.it/)
But I received from Parser Demo (I don't know how it is) a 7 digit lenght.

![1254 itu](https://user-images.githubusercontent.com/24221053/29021564-36008ee8-7b66-11e7-914c-6329c4c17452.png)

![screenshot_2017-08-07-11-15-54](https://user-images.githubusercontent.com/24221053/29021645-8245908c-7b66-11e7-88a5-c7f98bc8b470.png)

**Comment by kkeshava** [comment] 2017-08-08 08:44
@Raffaele74,

Thank you for contributing to libphonenumber! For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

This is actually working as intended; 1254 is already marked by the demo as a valid *short* number, see shortnumber results column in [demo](http://libphonenumber.appspot.com/phonenumberparser?number=1254&country=IT). The Javascript version does not support short-codes at this point..

As per last comment, when you entered 4 digit short code 1254 did you receive 7 digit length number i.e 1254111 from parser demo? We are unable to reproduce this issue. Could you please tell the steps to achieve this issue?

**Comment by Raffaele74** [comment] 2017-08-08 09:38
Hi.
Parser: I tried with 4, 5 and 6 digits and I had a negative response. Trying with 7 I got the positive answer.

**Comment by kkeshava** [comment] 2017-08-08 10:10
@Raffaele,
When you tried with 7 digit number isValidNumber() method is returning false which means that it is invalid number, you have not got a positive answer :) And isPossibleNumber() = true only because in Italy the length of the phonenumber starting with prefix 1 can be 6 to 11 digits, so when you input 7 digit number it results as true.

**Comment by Raffaele74** [comment] 2017-08-08 10:20
Thanks!

**Comment by kkeshava** [comment] 2017-08-08 10:39
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by kkeshava** 2017-08-08 10:39 UTC
