### ISSUE TITLE
Validation issue with +353 2fg0 917 4350

### ISSUE THREAD

**Issue by haseeb-heaven** [googlei18n/libphonenumber#1936] opened 2017-09-19 16:22 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 

Example number(s) affected ("+1 555 555-1234"): +353 2fg0 917 4350

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B353+2fg0+917+4350)

**Comment by penmetsaa** [comment] 2017-09-20 06:01
@haseeb-heaven
Thank you for taking the time to improve libphonenumber!

Please let us know what is the issue here. See our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by dracos** [comment] 2017-10-01 08:51
+353 20 917 4350 (without the "fg"?) is a drama code in the Republic of Ireland (source https://www.comreg.ie/csv/downloads/ComReg0804.pdf )

**Comment by penmetsaa** [comment] 2017-10-03 05:34
@dracos,

Thanks for sharing the official doc.

In this doc, it is mentioned that these are for "Drama use" and no further details are provided. We are not sure to which category these belong to. Ex: toll-free, fixed-line..etc. 

And we can't connect to phone number that you have shared (Response: "The number is disconnected and no longer in service"). Please share any working number and also details about the category along with supporting evidence. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by dracos** [comment] 2017-10-03 07:21
I know it's not a working number, it's for drama use as you say, ie. a telephone number to be used in television/film/etc. So I was providing evidence it should not be a number matched by libphonenumber (unless you wish to start recording drama use numbers, which I would find useful but I understand if you wouldn't). You don't match UK landline drama use numbers, for example.

**Comment by penmetsaa** [comment] 2017-10-03 09:34
Thanks for your inputs here. :) We do not support such numbers. 

Based on OFCOM's numbering plan, 121 is Birmingham's area code in GB.
https://www.ofcom.org.uk/__data/assets/pdf_file/0013/102613/national-numbering-plan-june-2017.pdf (Page 27). So we support 121 496 0620 as fixed-line number. I also see some valid number online. Ex: http://www.colliers.com/en-gb/birmingham/about/contact-us

Do you think that some part of them (subranges) are for "Drama use".
Please provide any valid official evidence for same. See our ["provide supporting evidence guidelines"](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence)

Note: You can take a look at our [FAQ page](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers) as well.

**Comment by dracos** [comment] 2017-10-03 09:46
Would you like a new ticket for that? You currently support US drama numbers when there's an area code (#1393), so I assume the UK is the same issue as that. The official list of UK drama numbers are given at https://www.ofcom.org.uk/phones-telecoms-and-internet/information-for-industry/numbering/numbers-for-drama

**Comment by penmetsaa** [comment] 2017-10-03 10:07
Thanks for sharing all the range details specific to drama numbers in GB. Yes, please create a separate issue specific to GB.

As mentioned by Lara in [other issue](https://github.com/googlei18n/libphonenumber/issues/1393#issuecomment-257519519), fixing GB issue will take some time to do. Our priority is to making sure valid numbers are marked as such.

These do not fit into any of our present categories and it is not worth maintaining a separate one as the use case is very limited.

>> We don't require that a number to be supported by the library has a human at the other end since we already accept premium rate services and they might go to an automated system instead. But to date we only accept ranges that a human might call or send an SMS to.

See https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers

Closing this as working as intended as there is no validation issue with origina IE number reported.

**Closed by penmetsaa** 2017-10-03 10:07 UTC

**Comment by giggsey** [comment] 2017-10-03 10:14
Related issue for the GB drama discussion: #341

**Comment by dracos** [comment] 2017-10-03 10:36
Opened #1948 for GB numbers passing, thanks.

**Comment by penmetsaa** [comment] 2017-10-03 10:45
@giggsey and @dracos,
Thanks for sharing all the details. :)
