### ISSUE TITLE
German Voicemail Access Numbers

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#439] opened 2014-12-03 20:34 UTC
Imported from [Google Code issue #439](https://code.google.com/p/libphonenumber/issues/detail?id=439) created by [cfkoch](https://code.google.com/u/108438119205599918600/) on 2014-03-21T21:53:37.000Z:

----
See also Issue #&nbsp;359 

Infix operators for 015X are clarified: inthe Bundesnetzagentur documentation that lararen... linked to.
( http://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Nummerierung/Rufnummern/Mobile%20Dienste/NummernplanMobileDienste.pdf?__blob=publicationFile&amp;v=8 )
They explictly state that for mobile phone numbers, between the Prefix and the Assigned Number there can be an infix. (section 2.5)

So far in the metadata, only 0177 99 is accounted for.

0150 00 ZZXXXXXX *****
0151 13 ZXXXXXXX
0151 13 ZZXXXXXX
0152Z 55 XXXXXXX VOICEMAIL
0152Z 50 XXXXXXX FAX
0153 00 ZZXXXXXX *****
0154 00 ZZXXXXXX *****
0155 00 ZZXXXXXX *****
0156 00 ZZXXXXXX *****
0157Z 99 XXXXXXX
0158 00 ZZXXXXXX *****
0159Z 33 XXXXXXX
0160 13 XXXXXXX(X)
0170 13 XXXXXXX(X)
0171 13 XXXXXXX(X)
0172 55 XXXXXXX(X) VOICEMAIL
0172 50 XXXXXXX(X) FAX
0173 55 XXXXXXX(X) VOICEMAIL
0173 50 XXXXXXX(X) FAX
0174 55 XXXXXXX(X) VOICEMAIL
0174 50 XXXXXXX(X) FAX
0175 13 XXXXXXX(X)
0176 33 XXXXXXX(X)
0177 99 XXXXXXX(X)
0178 99 XXXXXXX(X)
0179 33 XXXXXXX(X)

*** The document lists 00 as the Infix, but does not qualify whether that's a holding number for the document, or the planned service infix.  These were only available for assignment for a few months now; none are yet in service that I know of.

**Comment by keghani** [comment] 2016-04-22 14:35
We recently did a sweep of current voicemail numbers in Germany so Germany is fixed, e.g. http://libphonenumber.appspot.com/phonenumberparser?number=0150+00+00000000&country=DE

The first Swiss number mentioned is also supported: http://libphonenumber.appspot.com/phonenumberparser?number=%2B41+860+66+555+44+33&country=CH

I don't understand about the other numbers and whether they're working as intended. Since the original reporter doesn't seem to be on GitHub and the last comment is out of scope of the original report, I'll close this issue as there's no more we can do here. If anyone knows about German/Swiss/Austrian/other voicemail ranges that are not correct in the library please open a new issue (one per region). See [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Closed by keghani** 2016-04-22 14:35 UTC
Labels: priority-medium, type-defect
