### ISSUE TITLE
+90561XXXXXXX new Turkey GSM Area Code

### ISSUE THREAD

**Issue by ahmetkarakaya** [googlei18n/libphonenumber#1323] opened 2016-09-07 17:44 UTC
New GSM area code has been  released at Turkey ,it has following format
+90561XXXXXXX
 
I have prepared new API by adding "61" as following.

Could you plan to add this new area code in your next release? Thanks.

<mobile>
        
        <nationalNumberPattern>
          5(?:
            0[1-7]|
            22|
            [34]\d|
            5[1-59]|
            9[246]|
			**61**
          )\d{7}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>5012345678</exampleNumber>
      </mobile>

**Comment by kkeshava** [comment] 2016-09-14 11:43
Hi,
Thank you for taking the time to improve libphonenumber!

We can't find official evidence for the actual ranges that are valid. We need context about the prefix that makes them valid.
Please share any supporting evidence (for example, a national numbering plan, announcements from mobile carriers, news articles) so that we can update the carrier details as well. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by jaimefrites** [comment] 2016-09-21 18:01
Hi. Hope these articles prove existence of the phone numbers.

News article on the site of turkish mobile Turkcell.

http://medya.turkcell.com.tr/trabzonlular-ozel-numara-istedi-turkcellden-561li-hat-geldi-bulten_9331.html

News article on the site of turkish soccer team Trabzonspor. Looks like Turkcell promotes the phone numbers for Trabzonspor's fans.

http://www.trabzonspor.org.tr/tr/haberler/guncel-haberler/taraftarlarimizin-yeni-hatti-61cell-9-8-2016

An article on the site of turkish daily newspaper.

http://www.yeniakit.com.tr/haber/trabzonlular-ozel-numara-istedi-turkcellden-561li-hat-geldi-210295.html

**Comment by kkeshava** [comment] 2016-09-22 09:20
Hi,

We were unable to connect to 0561 610 00 00 given in the sites provided by you however we found IR 21 doc from Turkcell which confirms the validity of these numbers. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment] 2016-09-28 10:33
This is fixed in release 7.7.1: https://libphonenumber.appspot.com/phonenumberparser?number=%2B90+561+610+0000

**Closed by penmetsaa** 2016-09-28 10:33 UTC
