### ISSUE TITLE
ilibphonenumber: Missing area codes for UAE mobile

### ISSUE THREAD

**Issue by Ashwini-12** [googlei18n/libphonenumber#1927] opened 2017-09-11 11:34 UTC
*   Country: **United Arab Emirates**
*   Example number(s) and/or range(s): **area code 54 and 58**
*   Number type ("fixed-line", "mobile", "short code", etc.): **mobile**
*   For short codes, cost and dialing restrictions:
*   Where or whom did you get the number(s) from: **Wikipedia**
*   Authoritative evidence (e.g. national numbering plan, operator announcement):
*   Link from demo (http://libphonenumber.appspot.com) showing error:

**Comment by kkeshava** [comment] 2017-09-12 06:52
@Ashwini-12,
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)). 

This is actually working as intended; prefixes 54 and 58 are already marked by our library as Mobile. 
54 - http://libphonenumber.appspot.com/phonenumberparser?number=540000000&country=AE
58 - http://libphonenumber.appspot.com/phonenumberparser?number=589999999&country=AE

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by kkeshava** 2017-09-12 06:52 UTC

**Comment by kkeshava** [comment] 2017-09-12 06:55
This issue is a duplicate of #1925.

**Comment by Ashwini-12** [comment] 2017-09-12 11:20
Issue #1925 was not resolved and was closed. What is the resolution to add UAE area codes 54 and 58. For official reference you may look at following link on Wikipedia:
https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Arab_Emirates

**Comment by kkeshava** [comment] 2017-09-12 11:48
Hi Ashwini-12,
As mentioned in #1925 and also in my earlier comment, prefixes 54 and 58 are already marked by our library as Mobile. To check the latest behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=<REPORTED_NUMBER>)(instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
This was fixed in 7.7.4 verison of libphonenumber library #1412. We have already released 8.8.1 version now. Please upgrade to the latest release

**Comment by Ashwini-12** [comment] 2017-09-12 11:57
Are these area codes in a database or hardcoded in the code? I am just using a wrapper around the libphonenumber in my .net application. If they are validated against a database the wrapper class should automatically get validated.

**Comment by Ashwini-12** [comment] 2017-09-12 12:08
Is there a latest release(.dll) of libphonenumber that we can download for using with a .Net application?

**Comment by kkeshava** [comment] 2017-09-13 05:55
@Ashwini-12,

May be you can check this at https://github.com/aidanbebbington/libphonenumber-csharp

We do not maintain this third party port of libphonenumber, and it's not an issue with our version.

We encourage you to reach out to the third party port owner, which can be found in our section on
[Third Party Ports](https://github.com/googlei18n/libphonenumber#third-party-ports).
