### ISSUE TITLE
Validation issue with +421 909 [^0]xx xxx (SK)

### ISSUE THREAD

**Issue by sukihub** [googlei18n/libphonenumber#1140] opened 2016-06-01 14:11 UTC
Country/region affected: SK
Example number(s) affected: +421 909 123 456
The phone number range(s) to which the issue applies: +421 909 [^0]xx xxx
The type of the number(s): mobile

According to the official documents (http://www.teleoff.gov.sk/data/files/22411.pdf - in slovak language, but look for string `mobilné verejné telefónne siete`) all NDCs 901 - 919 are valid mobile phone numbers. Except for 9090 which is reserved for pagers, but 909[1-9] are valid mobile numbers again.

All NDCs 940 - 959 are also valid mobile numbers (just to be complete).

Same thing says this http://kt.uniza.sk/ktam2/download/Studijne_materialy/Projektovanie_sieti/cisl-plan.pdf (bottom of page 29) and also article on Wikipedia https://sk.wikipedia.org/wiki/Slovensk%C3%A9_telef%C3%B3nne_predvo%C4%BEby (everything unfortunately only in slovak language).

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=+421909123456&country=SK)

**Comment by penmetsaa** [comment] 2016-06-03 07:24
@sukihub,

Thanks for reporting this issue.

We have recently updated Slovakia phone numbers considering http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000BD0002PDFE.pdf (Aug 2015). As per this ITU doc 9091-9099 are reserved prefixes but not yet assigned to any carrier, unlike other prefixes mentioned in the document. This is the reason why we have not added this range.

As per same ITU doc, not all 940-959 ranges are assigned to carrier. Ex: 
940: It is assigned to O2 carrier. Libphonenumber returns it as valid.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B421+940+123+456
941-943: It is reserved. Libphonenumber returns it as invalid.

The evidences provided by you are older than the ITU doc.
We are not able to find any new official evidence saying that these numbers are assigned / any sample numbers of these ranges which are callable.

To support any of the missing ranges, we need to have any working numbers / latest evidence saying these are assigned to specific carriers. If you can find any, we will look at updating our metadata to reflect this.

**Comment by sukihub** [comment] 2016-06-03 07:57
As of Feb 2016 prefixes 9091-9099 are being used by the new carrier Juro (technically just a part of Telekom (T-Mobile is the old name, they are called Telekom now - http://www.t-mobile.sk). This number should work, it's supposed to be hotline of the new company: 0909 909 909 (they should be available on workdays from 6:00 to 18:00 GMT).

Yes, some prefixes are not being used yet, and I see why you do not want to mark them as valid, but if I understand it correctly, they can start being used (almost) anytime.

**Comment by sukihub** [comment] 2016-06-03 08:04
Not really a proof, but here is newspaper article saying that new carrier uses 909 prefix: http://www.etrend.sk/firmy/juro-novy-operator-od-telekomu-ma-volania-i-sms-za-polovicu-ako-4ka-s-hacikom.html

You might already know this, but in Slovakia, it is possible to migrate phone number from one carrier to another and keep the old prefix. Prefixes therefore can not be used to identify carrier.

**Comment by penmetsaa** [comment] 2016-06-03 10:58
@sukihub,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Yes, we understand [number portability across carriers in Slovakia](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L21174). We return the original carrier for the supplied number.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment] 2016-06-16 10:51
Fixed in release 7.4.3.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B421+909+123+456

**Closed by penmetsaa** 2016-06-16 10:51 UTC
