### ISSUE TITLE
Support 0508\d{6} as valid in PM

### ISSUE THREAD

**Issue by fmunch** [googlei18n/libphonenumber#1060] opened 2016-04-04 11:55 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): PM

Example number(s) affected ("+1 555 555-1234"): 0508411010

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +508 XX XX XX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line and mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

Both number 05 08 41 10 10 from Saint Pierre and Miquelon (SPM) and from France, and +508 41 10 10 refer to the same phone number, according to :
http://www.profilspm.fr/fr/en-details/les-infrastructures-sociales-et-economiques/les-infrastructures-de-communications.html
In french (SPM Telecom website), but it basically says that 05 08 XX XX XX is used to call SPM from France, and +508 XX XX XX from another country
Other links showing 10 digits numbers:
http://www.outre-mer.gouv.fr/?adresse-utiles-saint-pierre-et-miquelon.html
http://www.tourisme-saint-pierre-et-miquelon.com/

It might be related to #274 (last comment).

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0508411010&country=PM)

**Comment by penmetsaa** [comment] 2016-04-06 09:19
@fmunch

Thanks for reporting this issue.

It looks like you have a PM number in French format so that you can dial it from France.

In these cases(Territories of France), there is no way libphonenumber knows the country to which the number belongs, unless you specify the number in international format with plus and  country calling code or specify the “Default Country” - where the number is being dialled from - correctly. This is the reason why demo site says the phone number is too long for input 0508411010 with PM as default country. 

Number 411010 is already supported as valid "Saint Pierre and Miquelon" landline number. 
It all depends on the region from where you are calling it from.
[FR number demo](https://libphonenumber.appspot.com/phonenumberparser?number=05+08+41+10+10&country=FR)
[International format demo link](https://libphonenumber.appspot.com/phonenumberparser?number=+508411010&country=PM)
[National format demo link](https://libphonenumber.appspot.com/phonenumberparser?number=0411010&country=PM)
[Local format demo link](https://libphonenumber.appspot.com/phonenumberparser?number=411010&country=PM)

As you have rightly mentioned, this is the same as issue #274

**Comment by fmunch** [comment] 2016-04-06 13:23
Thank you for your feedback.

Maybe "05 08 XX XX XX" should be a `possibleNumberPattern`? Since I am pretty sure that both XX XX XX and 05 08 XX XX XX work when calling SPM from SPM: the [town hall website of Saint-Pierre](http://www.mairie-stpierre.fr/fr/66-contacts.php) uses both formats.
I think that 05 08 XX XX XX should be recognized as a valid number for SPM (without speaking of France, even if it is a french number format).

**Comment by penmetsaa** [comment] 2016-04-20 13:23
Thanks for bringing this case to our attention!
We successfully dialled a +508xxxxxx number internationally, but +508508xxxxxx did not connect.  This tells us that 0508xxxxxx is not actually "valid" as defined by the library.
I will close this issue as the library is working as intended.

**Closed by penmetsaa** 2016-04-20 13:23 UTC
