### ISSUE TITLE
IsValidPhone  number is incorrect return  for 7042094906

### ISSUE THREAD

**Issue by ashishgupta-kiwi** [googlei18n/libphonenumber#1200] opened 2016-07-13 09:38 UTC
Hi 
i am windows phone developer when i am using this number with IN locale 
but this api is giving wrong autntication please help this is my code

 public static bool ValidatePhoneNumber(string strphonenumber, string locale)
        {
            bool isValid = false;
            try
            {
                PhoneNumberUtil phoneUtil = PhoneNumberUtil.GetInstance();
                PhoneNumber swissNumberProto = phoneUtil.Parse(strphonenumber, locale);
                isValid = phoneUtil.IsValidNumber(swissNumberProto);
            }
            catch (Exception ex)
            {
            }
            return isValid;
        }

but is retun false

**Comment by penmetsaa** [comment] 2016-07-13 09:51
@ashishgupta-kiwi ,
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

Closing this issue as library is working as intended.
https://libphonenumber.appspot.com/phonenumberparser?number=7042094906&country=IN

**Closed by penmetsaa** 2016-07-13 09:51 UTC

**Comment by ashishgupta-kiwi** [comment] 2016-07-13 12:04
Hi 

I am using this library from nuget. I think this is latest library but this library function isValidNumber return false for locale "IN" and phonenumber 7042094906.

Please help.

Thanks
Ashish Kumar Gupta

![libphonenumber](https://cloud.githubusercontent.com/assets/3992685/16802708/b845bca4-491f-11e6-8a50-950bbba4fddb.png)

**Comment by penmetsaa** [comment] 2016-07-15 04:03
@ashishgupta-kiwi 
We do not maintain the csharp port of libphonenumber. 
You can contact actual owners of the library that you are using:
https://www.nuget.org/packages/libphonenumber-csharp.unofficial/
