### ISSUE TITLE
Validation issue with +51990315422 (PE)

### ISSUE THREAD

**Issue by Leydi23** [googlei18n/libphonenumber#1791] opened 2017-06-14 16:51 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): PE

Example number(s) affected ("+1 555 555-1234"): +51993061806

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B51993061806&country=PE)

**Comment by SumathiSundara** [comment] 2017-06-15 05:02
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by SumathiSundara** [comment] 2017-06-15 09:34
Sure Keghani,

I used canned response
https://g3doc.corp.google.com/i18n/phonenumbers/g3doc/team-internal/canned-responses.md?cl=head#non-issue-questions
I see both the numbers provided are working
http://libphonenumber.appspot.com/phonenumberparser?number=%2B51990315422
http://libphonenumber.appspot.com/phonenumberparser?number=%2B51993061806&country=PE

Shall I use this response
https://g3doc.corp.google.com/i18n/phonenumbers/g3doc/team-internal/canned-responses.md?cl=head#wai-metadata-issues
  ?

**Comment by lararennie** [comment] 2017-06-15 09:42
2017-06-15 11:34 GMT+02:00 SumathiSundara <notifications@github.com>:

> Sure Keghani,
>
> I used canned response
> https://g3doc.corp.google.com/i18n/phonenumbers/g3doc/team-
> internal/canned-responses.md?cl=head#non-issue-questions


That says "Respond, ideally by pointing to existing documentation, then end
with:" [canned response]

You didn't respond first :)

It's supposed to be for actual questions, like "how do I get x or y
working?" or "why is z like it is?"


>
> I see both the numbers provided are working
> http://libphonenumber.appspot.com/phonenumberparser?number=%2B51990315422
> http://libphonenumber.appspot.com/phonenumberparser?number=%
> 2B51993061806&country=PE
>
> Shall I use this response
> https://g3doc.corp.google.com/i18n/phonenumbers/g3doc/team-
> internal/canned-responses.md?cl=head#wai-metadata-issues
> ?
>
> On Thu, Jun 15, 2017 at 2:41 PM, Keghani Kouzoujian <

**Comment by keghani** [comment] 2017-06-15 09:52
Hi @Leydi23, thanks for using our library!

We were slightly confused not knowing what needed to be fixed here, sorry for the unrelated comments (since deleted).

What do you think should be fixed here? The demo does say +51990315422 (from the issue title) is valid and MOBILE for PE, as is +51993061806 (from the issue description).

If you meant for us to validate these numbers, they're already working as intended in the latest version of the library. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) to file a comprehensive report so we can take action quickly if there's a metadata issue with the latest version.

In the meantime since it's not clear there's an issue, I'll close this. Again, thanks for using libphonenumber!

**Closed by keghani** 2017-06-15 09:52 UTC
