### ISSUE TITLE
Validation issue with 07000011564653 (FR)

### ISSUE THREAD

**Issue by Zehir** [googlei18n/libphonenumber#1495] opened 2017-01-05 14:46 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): FR

Example number(s) affected ("+1 555 555-1234"): 07000011564653 (random number in tested range)

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 
National plan:
07000020000000	07000029999999
07000010000000	07000019999999
07000030000000	07000039999999
07000000000000	07000009999999

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 
[Official numbering plan](https://extranet.arcep.fr/portail/OpérateursCE/Numérotation.aspx) ([direct link to xls file](https://extranet.arcep.fr/portail/LinkClick.aspx?fileticket=PBA1WK-wnOU%3d&tabid=217&portalid=0&mid=850))

[General news post about this change
](https://lafibre.info/4g/telephonie-mobile-des-numeros-a-14-chiffres-en-2017/)
[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=07000011564653&country=FR&geocodingLocale=fr-FR)

**Comment by penmetsaa** [comment] 2017-01-06 10:34
@Zehir,
Thank you for using libphonenumber!

As per below official docs these 13 to 14 digit 700 numbers are extended length mobile numbers that are used for M2M communications.
http://www.arcep.fr/uploads/tx_gsavis/12-0855.pdf
http://www.arcep.fr/index.php?id=8146

libphonenumber presently do not support M2M numbers. But we are checking on the options on how to support M2M numbers.
Please take a look at below pages.
[What about m2m machine to machine numbers](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers)
[Support M2M numbers](https://github.com/googlei18n/libphonenumber/issues/680)

This issue is actually duplicate of [French Prefix 0700](https://github.com/googlei18n/libphonenumber/issues/1098).
If you think that these are not M2M numbers, please feel free to reopen and provide your inputs.

**Closed by penmetsaa** 2017-01-06 10:34 UTC

**Comment by Zehir** [comment] 2017-01-06 21:17
Sorry I dont see the duplicate issues.
Thank
