### ISSUE TITLE
Error: Could not find method compile()

### ISSUE THREAD

**Issue by chintansoni202** [googlei18n/libphonenumber#1343] opened 2016-09-16 10:18 UTC
I want to add libphonenumber library to my Android Studio project.

So, I added below line in my build.gradle(Module:app):

`compile 'com.googlecode.libphonenumber:libphonenumber:7.6.1'`

But this gives me error as below:

```
Error:Could not find method compile() for arguments [com.android.support:support-v4:24.2.1] on DefaultExternalModuleDependency{group='com.android.support', name='appcompat-v7', version='24.2.1', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.

Please install the Android Support Repository from the Android SDK Manager. Open Android SDK Manager
```

Does anyone know the reason and solution ?

**build.gradle(Project:xxx):**

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0-rc2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
**build.gradle(Module:app):**

```
apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"
    defaultConfig {
        applicationId "com.xxx.android"
        minSdkVersion 17
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        vectorDrawables {
            useSupportLibrary = true
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

def SUPPORT_LIBRARY = "24.2.1"
def BUTTER_KNIFE_LIBRARY = "8.4.0"
def GLIDE_LIBRARY = "3.7.0"
def OK_HTTP_VERSION = "3.4.1"
def RETROFIT_VERSION = "2.1.0"
def GSON_VERSION = "2.7"
def FIREBASE_VERSION = "9.4.0"

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile "com.android.support:appcompat-v7:$SUPPORT_LIBRARY"
    compile "com.android.support:support-v4:$SUPPORT_LIBRARY"
    compile "com.android.support:design:$SUPPORT_LIBRARY"

    compile "com.jakewharton:butterknife:$BUTTER_KNIFE_LIBRARY"
    apt "com.jakewharton:butterknife-compiler:$BUTTER_KNIFE_LIBRARY"

    compile "com.github.bumptech.glide:glide:$GLIDE_LIBRARY"

    compile "com.squareup.okhttp3:okhttp:$OK_HTTP_VERSION"
    compile "com.squareup.okhttp3:logging-interceptor:$OK_HTTP_VERSION"
    compile "com.squareup.retrofit2:retrofit:$RETROFIT_VERSION"
    compile "com.squareup.retrofit2:converter-gson:$RETROFIT_VERSION"
    compile "com.google.code.gson:gson:$GSON_VERSION"

    compile "com.google.firebase:firebase-messaging:$FIREBASE_VERSION"
    compile "com.google.firebase:firebase-crash:$FIREBASE_VERSION"
}

apply plugin: 'com.google.gms.google-services'
```

Note: I ended up adding jars to libs folder from here (which I didn't wanted to do). If anyone knows how to accomplish this with using gradle ?

I have posted question on [stackoverflow](http://stackoverflow.com/questions/39528091/android-studio-add-libphonenumber-library-to-project) as well at

**Comment by keghani** [comment] 2016-09-16 10:28
This looks like a duplicate of https://github.com/googlei18n/libphonenumber/issues/1306.
Does it work when you add javanano dependencies?

If so, if you can wait until the next release (ETA Monday) you may not need to add javanano dependencies at all. If all goes well we will remove the need for these.

**Comment by chintansoni202** [comment] 2016-09-16 10:31
That sounds good, ma'am... I am alright with waiting till Monday.. Thank you ma'am. :+1:

**Comment by keghani** [comment] 2016-09-19 09:25
@chintansoni202 I thought about this some more and it doesn't look like an issue with our library. As recommended on stackoverflow (and mentioned in the error message) I think you should just install the Android Support Repository.

I'll close this as it's not an issue with the library. Please consider joining
the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.

**Closed by keghani** 2016-09-19 09:25 UTC

**Comment by chintansoni202** [comment] 2016-09-19 09:39
@keghani ma'am could you please tell me the reason for reverting back to old support library. Also, if you sure that it is not the issue with your library, and it is with support library version i am using, then will you please show me where to post the issue for it ?

**Comment by keghani** [comment] 2016-09-19 09:41
I don't think it's an issue with the support library either. You need to look into your setup.
I don't know how to help you there, maybe consult an Android developer support group, or see the responses on stackoverflow.

**Comment by chintansoni202** [comment] 2016-09-19 09:43
@keghani Okay ma'am.. No problem. I will figure this out. If I can solve this issue, shall I post it here ?

**Comment by keghani** [comment] 2016-09-19 09:46
You can, but I think it's more interesting to Android developers, as it's not about libphonenumber :)

Also feel free to join the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) as mentioned earlier, these kinds of discussions are welcome there.
