### ISSUE TITLE
Add new NDC +22785 for Atlantique Telecom Niger (Moov)

### ISSUE THREAD

**Issue by NERTL** [googlei18n/libphonenumber#1845] opened 2017-07-12 10:52 UTC
Dear Colleague,
please we request to implement our new NDC: +22785 as per out latest IR21 attached.
looking forward your confirmation

Regards
Ms. Ramatou H
[Latest IR21 NERTL_May, 30 2017.pdf](https://github.com/googlei18n/libphonenumber/files/1141732/Latest.IR21.NERTL_May.30.2017.pdf)

**Comment by kkeshava** [comment] 2017-07-12 11:13
Hi,
Thank you for taking the time to improve libphonenumber!

This issue is a duplicate of #1785. As mentioned there please sign the CLA and reopen the original bug. Closing this issue.

**Closed by kkeshava** 2017-07-12 11:13 UTC
