### ISSUE TITLE
Validation issue with +22588377453

### ISSUE THREAD

**Issue by NeverMindNever** [googlei18n/libphonenumber#1353] opened 2016-09-20 14:05 UTC
Country/region affected (e.g., "US"): Ivory Coast

Example number(s) affected ("+1 555 555-1234"): +22588377453

The phone number range(s) to which the issue applies : +225 58 

The type of the number: Fixed line

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): http://www.artci.ci/images/stories/pdf/numerotation/plan_de_numerotation_2014.pdf

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B22588377453)

**Comment by penmetsaa** [comment] 2016-09-21 06:44
Thank you for taking the time to improve libphonenumber!

We were able to connect to +225 883 77453 but we can't find official evidence for the actual ranges that are valid. The evidence you have provided do not mention any details of 8 digit phone numbers that start with 8. 

It looks like some  of the phone numbers that start with 8 are mobile.
87: http://fr.wikipedia.org/wiki/Liste_des_indicatifs_téléphoniques_en_Côte_d’Ivoire
89: http://www.goafricaonline.com/ci/62403-polymed-equipements-medicaux-abidjan-cote-ivoire

We can't support single numbers, we need context about the prefix (like 88 in this case) that makes them valid and also type of the number i.e fixed line or mobile. 

Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by Ry4an** [comment] 2016-11-29 18:31
FWIW I've seen four of these 88 numbers in the wild, so they're definitely being handed out.  I can't find any published reference to 88 in 225 though. ☹️

**Comment by penmetsaa** [comment] 2016-11-30 05:45
@Ry4an,
Thanks for checking this issue. We agree that these 88 (8 digit) numbers are valid but we need to know what is the type (fixed-line / mobile..) of these numbers. Wikipedia states that 08 and 87 are mobile numbers. Do 88 numbers also belong to mobile? If you have any online references, please share them.

**Comment by Ry4an** [comment] 2016-11-30 22:11
We've seen four examples of 88 numbers and they're mobile.  I'm trying to figure out which carrier.

**Comment by penmetsaa** [comment] 2016-12-01 08:59
@Ry4an,
Thanks so much for the update. As we are able to connect to the 88 numbers online and prefix (88) is close to mobile ranges (08, 87, 89) in Ivory Coast, we will go ahead and support this range as mobile range.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by Ry4an** [comment] 2016-12-01 14:20
Excellent, much appreciated!

**Comment by kkeshava** [comment] 2016-12-13 10:37
Fixed in release 8.0.0.

**Closed by kkeshava** 2016-12-13 10:37 UTC
Labels: help wanted
