### ISSUE TITLE
Validation issue with +917458000000

### ISSUE THREAD

**Issue by conradolega** [googlei18n/libphonenumber#1352] opened 2016-09-20 02:11 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 

Example number(s) affected ("+1 555 555-1234"): +917458000000

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +917458XXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): Unknown

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

We've sent messages to this number before and the owner has received them. We've also checked with a PhoneID service that this is an Airtel number.

Also checking Google:
https://www.google.co.in/#q=%22%2B91+7458%22

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B917458000000)

**Comment by penmetsaa** [comment] 2016-09-20 07:39
@conradolega 
Thank you for taking the time to improve libphonenumber!

As per below latest official doc it looks like only 7458[089] xxxxx ranges are assigned to Airtel. http://www.dot.gov.in/sites/default/files/u75/2016_03_02%20TBID-AS-IIII.pdf. 
Please share any evidence that says whole 74580 xxxxx range is valid. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by conradolega** [comment] 2016-09-20 12:08
Ah yes, I meant 74580 xxxxx.

**Comment by penmetsaa** [comment] 2016-09-21 05:15
Oh ok. Thanks for the confirmation. :)
We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by SumathiSundara** [comment] 2017-03-21 11:01
Fixed in 7.7.4

**Closed by SumathiSundara** 2017-03-21 11:01 UTC
