### ISSUE TITLE
Formatting issue with +263 775 099 790 (Zimbabwe mobile carrier formatting wrong)

### ISSUE THREAD

**Issue by okandas** [googlei18n/libphonenumber#2003] opened 2017-11-10 09:30 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 

Example number(s) affected ("+1 555 555-1234"): +263 775 099 790

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B263+775+099+790)

![screen shot 2017-11-10 at 11 24 30 am](https://user-images.githubusercontent.com/26438624/32651482-d6d5e49c-c609-11e7-9807-7cc38b7e477d.png)

the national format for zimbabwe is wrong we usually format on each third number, for example
the national format is currently being parsed as 077 509 9790 but here we write our number like this 0775 099 790 if the leading zero is missing we write in like this 775 099 790, for example in the internation format currently being parsed as 

International format | +263 77 509 9790

we write it as 

International format | +263 775 099 790

can this be changed to fit this ?

**Comment by SumathiSundara** [comment] 2017-11-14 10:19
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by SumathiSundara** [comment] 2017-11-17 05:26
We haven't received a response from you yet about official evidence.
Would it be possible for you to provide an update in order for us to move
forward with fixing this issue?

**Comment by okandas** [comment] 2017-11-17 06:32
@SumathiSundara apologies hectic few days in zimbabwe .. will get you the information by the end of the day ..

**Comment by SumathiSundara** [comment] 2017-11-23 08:52
This issue is blocked on your or other GitHub contributor's input. Please help
us find evidence. Otherwise we don't have enough information to
fix the issue and may have to close it as infeasible.

**Comment by okandas** [comment] 2017-11-23 18:41
*   Country: Zimbabwe
*   Example number(s) and/or range(s): 0775099790
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   For short codes, cost and dialing restrictions:
*   Where or whom did you get the number(s) from: personal number
*   Authoritative evidence (e.g. national numbering plan, operator announcement): https://www.potraz.gov.zw/images/documents/ZIMBABWE%20NATIONAL%20NUMBERING%20PLAN%202012%20Rev%203.pdf
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=0775099790&country=ZW

this is a format issue and the proper format should be rendered as follows - 0775 099 790 not 077 509 9790

**Comment by SumathiSundara** [comment] 2017-11-24 08:21
Thanks for providing all the details we need! We've accepted this issue. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment] 2017-11-30 10:55
@okandas,
The  official doc that you have shared do not have any statement supporting to change mobile numbers format from XX XXX XXXX to XXX XXX XXX.

As per our policy, we need very conclusive evidence to change the format. Please go through this FAQ. https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#when-does-formatting-in-a-country-change

Online results are also in line with format XX XXX XXXX
- XXX XXX XXX: 605 results
https://www.google.co.in/search?q=site%3AZW+call+"0712+100..999+100..999"&
- XX XXX XXXX: 1,030 results
https://www.google.co.in/search?q=site%3AZW+call+"0712+100..999+100..999"&

Closing this as working as intended; Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by penmetsaa** 2017-11-30 10:55 UTC
