### ISSUE TITLE
Validation issue with 00596696526470 (SE)

### ISSUE THREAD

**Issue by lucky2915** [googlei18n/libphonenumber#1480] opened 2016-12-15 22:06 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): SE

Example number(s) affected ("+1 555 555-1234"): 00596696526470

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=00596696526470&country=SE)

**Comment by kkeshava** [comment] 2016-12-16 05:28
Thank you for taking the time to improve libphonenumber!

This issue is a duplicate of #1479. Closing this issue.

**Closed by kkeshava** 2016-12-16 05:28 UTC

**Comment by kkeshava** [comment] 2017-01-17 05:48
@lucky2915,
Could you please help us by answering the questions given in #1479. This will help us in resolving the issue faster.
