### ISSUE TITLE
Augment target descriptions in java build.xml

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#522] opened 2014-12-03 20:44 UTC
Imported from [Google Code issue #522](https://code.google.com/p/libphonenumber/issues/detail?id=522) created by [lewis.mcgibbney](https://code.google.com/u/113441186710894791768/) on 2014-09-22T12:51:49.000Z:

---

<b>What steps will reproduce the problem?</b>
1. Navigate to libphonenumber/java and execute build.xml -projecthelp

<b>What is the expected output? What do you see instead?</b>
2. View the output... it is extremely primative. This is not helpful and it is a direct result of the &lt;target description=&quot;...&quot;&gt; attribute not being present for many targets. The attached patch augments target descriptions so that the following information is nowpresent

lmcgibbn@LMC-032857 /usr/local/jpl/memex/libphonenumber/java(master) $ ant -projecthelp
Buildfile: /usr/local/jpl/memex/libphonenumber/java/build.xml

Main targets:

 build-alternate-metadata   Builds the Additional Phone Number Formatting information, containing alternative formats that are commonly used when writing phone numbers in certain countries.
 build-carrier-data         Builds the Phone Carrier data based largely on Wikipedia and communication with Carriers
 build-carrier-test-data    Builds the Phone Carrier test data based largely on Wikipedia and communication with Carriers
 build-geo-data             Builds data relating to geocoding e.g. mapping numbers to areas
 build-geo-test-data        Builds test data relating to geocoding
 build-js-metadata          Builds Metadata on Phone Number Plan and formatting rules for the JavaScript component
 build-phone-metadata       Builds the full Metadata on Phone Number Plan and formatting rules
 build-short-metadata       Short build of the Metadata on Phone Number Plan and formatting rules
 build-test-metadata        Builds the full Metadata on Phone Number Plan and formatting rules for testing purposes
 build-timezones-data       Builds timezone data
 build-timezones-test-data  Builds timezone test data
 clean                      Remove generated files.
 clean-build                Removes both generated files and the associated jar artifact
 compile                    Compile Java source.
 jar                        Compiles the Java code and generates a jar artifact
 junit                      Builds the test jar artifact and runs the test suite
 junitreport                Generates JUnit XML reports for all tests
 test                       Builds the test jar artifact and runs an individual test
 test-jar                   Builds everything required to execute tests as well as the data required for tests
 testname                   Runs an individual test N.B. should be invoked with -Dtest=TestName
Default target: compile

<b>What version of the product are you using? On what operating system?</b>
lmcgibbn@LMC-032857 /usr/local/jpl/memex/libphonenumber(master) $ svn info
Path: .
Working Copy Root Path: /usr/local/jpl/memex/libphonenumber
URL: http://libphonenumber.googlecode.com/svn/trunk
Relative URL: ^/trunk
Repository Root: http://libphonenumber.googlecode.com/svn
Repository UUID: ee073f10-1060-11df-b6a4-87a95322a99c
Revision: 702
Node Kind: directory
Schedule: normal
Last Changed Author: lararennie@google.com
Last Changed Rev: 702
Last Changed Date: 2014-09-22 06:19:28 -0400 (Mon, 22 Sep 2014)

<b>Please provide any additional information below.</b>

**Comment by keghani** [comment] 2017-07-19 17:28
We don't have visibility into the patch anymore, and it's not clear whether a CLA was signed (since we moved to GitHub in the meantime).

It's not clear to me what the issue is, so I'm going to close this. If you have ideas and can contribute a patch please do so!

**Closed by keghani** 2017-07-19 17:28 UTC
Labels: priority-medium, type-defect
