### ISSUE TITLE
Validation issue with +49176 2039721  (DE)

### ISSUE THREAD

**Issue by Neffes1987** [googlei18n/libphonenumber#1443] opened 2016-11-22 17:10 UTC
Hi! I have problem with code 0176 for germany. The function isValidNumber return false, how can i add this code by the library?

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=01762039721+&country=DE)

**Comment by kkeshava** [comment] 2016-11-24 10:43
Hi,

Thank you for taking the time to improve libphonenumber!

+49176 2039721 is not assigned. Did you have a typo and forget the last digit? We do support 11-digit mobile numbers starting with 176, see  a working example on the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B49176+20397211&country=DE).
This is probably working as intended. If you disagree, please share an actual 10-digit number or range evidence so we can support 10-digit German numbers beginning with 176, or whatever the range may be. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by kkeshava** [comment] 2016-12-08 07:39
Hi,
This issue is blocked on your clarification about the digit length. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by Neffez** [comment] 2016-12-08 13:38
I have 2 valid (verified by calling) german numbers starting with +49176. One has 7, the other has 9 following digits. isValidNumber() returns false on both. If I add or remove a digit (making it 8 digits), isValidNumber() returns true. Same goes for a 152 number I have.

10-digit 176 numbers are not that rare in germany (seems like they are from before 2002). Not sure about 12-digit numbers though.

Sorry that I can't share those numbers for data privacy reasons.

**Comment by kkeshava** [comment] 2016-12-14 11:38
Hi,

We do not need you to share the numbers, but evidence as per our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

Please check the link, as without evidence we do not have enough information and may have to close this issue as infeasible.

We would like to have either official evidence that says 10-digit & 12-digit 176 and 152 numbers are valid or we need online references of working numbers.

**Comment by cryptomilk** [comment] 2016-12-18 12:39
https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Nummerierung/Nummerierungskonzept/Nummerierungskonzept2014.pdf?__blob=publicationFile&v=1

**Nummernteilbereich (0)15

Präfix    Rufnummer für Mobile Dienste
0                         (11 Ziffern)**

Numbers for (0)15 should have 12 digits. This is probably because of the block sizes they assign since 2014.


If you scroll a bit down:

**Nummernteilbereiche (0)160, (0)162, (0)163 und (0)17
Präfix    Rufnummer für Mobile Dienste
0                         (10 oder 11 Ziffern)**

So for those prefixes numbers have 11 or 12 digits.

**Comment by cryptomilk** [comment] 2016-12-18 12:50
The document is from 2014 and tells how number should be done from from 2014 into the future. Shorter number at least for (0)160, (0)162, (0)163 and (0)17 are possible.

+49 170 1234567

is a valid number. The older the number the shorter it can be. I do not see a official document which shows the blocks which have been assigned.

**Comment by cryptomilk** [comment] 2016-12-18 12:52
+49 176 2039721 (from the subject of that bug has 10 digits and is a valid number)

**Comment by kkeshava** [comment] 2017-01-03 10:07
Hi,

We were able to dial +49176 2039721 now. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment] 2017-01-17 05:14
Fixed in release 8.0.1.

**Closed by kkeshava** 2017-01-17 05:14 UTC
