### ISSUE TITLE
Format error for ES mobile range

### ISSUE THREAD

**Issue by Jsuareza** [googlei18n/libphonenumber#1729] opened 2017-05-04 18:47 UTC
Hello Support,

File: PhoneNumberMetadata.xml
Country: ES
Example number(s) and/or range(s): 7489999999
Number type ("fixed-line", "mobile", "short code", etc.): Mobile

In "ES" territory for <mobile><nationalNumberPattern> one of your comments reads "Added 78 range based on user bug reports" (issue #1450).

When you added range 78 I think that you made a mistake. Right now the number pattern you have configured is: 
  (?:6\d{6}|7[1-48]\d{5}|9(?:6906(?:09|10)|7390\d{2}))\d{2}

But this includes this range: from 710000000 to 7489999999. 

Number 710000000 is correct, but 7489999999 includes 10 digit numbers that are not supported for that territory (<possibleLengths national="9"/>).

You should change from:
  7[1-48]\d{5}
to:
  7([1-4]|8)\d{5}

Correct full number patter would be:
  (?:6\d{6}|7([1-4]|8)\d{5}|9(?:6906(?:09|10)|7390\d{2}))\d{2}

That includes this ranges for numbers starting in 7:
  From 710000000 to 749999999
  From 780000000 to 789999999

Best Regards,

  Jorge

**Comment by lararennie** [comment] 2017-05-04 19:21
Thanks for the report!
I think actually it's fine. You'll notice on our demo that http://libphonenumber.appspot.com/phonenumberparser?number=7489999999&country=ES is not valid (too long).

7[1-48]\d{5} means 7 followed by 1, 2, 3, 4 or 8, followed by 5 digits.
7([1-4]|8)\d{5} is the same.

Did you have any particular example number that we are validating as valid that we shouldn't be?

**Comment by Jsuareza** [comment] 2017-05-05 07:17
No particular example. Just a wrong parser. Thank you for the tip, you can close or delete this thread

**Comment by penmetsaa** [comment] 2017-05-05 07:31
@Jsuareza ,
Thanks for the confirmations. Closing this bug as working as intended.

**Closed by penmetsaa** 2017-05-05 07:31 UTC
