### ISSUE TITLE
Toll free numbers shown "United States" for Canada as well

### ISSUE THREAD

**Issue by Franklin1980** [googlei18n/libphonenumber#586] opened 2015-01-19 14:27 UTC
Toll free numbers are parsed as "United States" for Canadian banks/services numbers as well. Please consider to include Canada as "United States/Canada"

This is noticed from Android Kitkat. Sometimes, Canadian bank will dial user for follow up with customer and the incoming call number are shown as "United States". Thus most of customer will not answer the call because they consider the call as spam. Same behavior can be found for outgoing call. When user calls bank or carrier customer service toll free numbers, device UI will show "United States" due to i18n lib implementation.

**Comment by dlyongemallo** [comment] 2015-01-19 15:08
Thanks for the report.

This is fixed in our open-source release, which you can verify here (with, e.g., "+18005551234" and no region code): http://libphonenumber.appspot.com

You'll see that the PhoneNumberOfflineGeocoder result is empty, which is the expected result for a number which can geocode to more than one country.

Android KitKat is probably using an old version of the library. We have no control over this. If you want it fixed in KitKat, you should probably file a bug against AOSP.

**Closed** 2015-01-19 15:21 UTC

**Comment by Franklin1980** [comment] 2015-01-19 15:39
Thank you for your reply. The issue can also be found on Lollipop 5.0 as well.

**Comment by Franklin1980** [comment] 2015-04-21 16:28
When using the tool http://libphonenumber.appspot.com to check following numbers:
RBC (Bank): 1-800-769-2511
TD (Bank): 1-866-222-3456
Rogers: 1-888-764-3771
Step2 uses CA and step3 uses en-CA and get the region US now. Is it updated again?

**Comment by dlyongemallo** [comment] 2015-04-21 16:38
I see an empty PhoneNumberOfflineGeocoder result for all three numbers. What do you mean by "step 2" and "step 3"?

**Comment by Franklin1980** [comment] 2015-04-21 17:49
For the Phone Number Parser Demo: 

Phone Number entered: +18007692511
defaultCountry entered: CA
Language entered: en (CA)

Parsing Result 
country_code 1 
national_number 8007692511 
extension   
country_code_source FROM_NUMBER_WITH_PLUS_SIGN 
italian_leading_zero false 
raw_input +18007692511 

Validation Results 
Result from isPossibleNumber() true 
Result from isValidNumber() true 
Result from isValidNumberForRegion() true 
Phone Number region US  --------------This is the problem. 
Result from getNumberType() TOLL_FREE

**Comment by dlyongemallo** [comment] 2015-04-22 10:13
That's the result of getRegionCodeForCountryCode, which returns one region (the main region associated with the prefix). For +1-800 numbers, this will be "US". There is no way to distinguish, based on a string of digits starting with +1-800, whether a number is coming from the US or Canada. These numbers can be re-assigned between the countries, and we do not maintain a database of actual assignments.

Note that if you want to geocode a number, you should be using PhoneNumberOfflineGeocoder. In this case, it returns an empty result, indicating that the number cannot be geocoded as the prefix is shared between multiple regions. If you want to get the list of regions for the prefix, you can call getRegionCodesForCountryCode on the country code.

Everything appears to be working as intended from the library. If some software is not calling the geocoder and is just using the region code, it's not using the API correctly and you need to file a bug against them.
