### ISSUE TITLE
Validation issue with +2547713478557 (KE)

### ISSUE THREAD

**Issue by EsoftsLimited** [googlei18n/libphonenumber#1101] opened 2016-05-03 15:17 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected : KE

Example number(s) affected : +2547713478557

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +254770 - +254775

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): premium rate

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 
https://en.wikipedia.org/wiki/Telephone_numbers_in_Kenya#Mobile_phone_numbers

Please update new Service providers using the above list

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B2547713478557&country=KE)

**Comment by penmetsaa** [comment] 2016-05-05 06:03
@EsoftsLimited,

Thank you for taking the time to improve libphonenumber!
The input provided is 10 digit number. 

As per [official doc](http://www.ca.go.ke/images/downloads/NUMBERING/Telecommunication%20Numbering%20Plan%20For%20Kenya%20Feb%202016.Pdf), mobile numbers in Kenya are of 9 digit length. [Wiki](https://en.wikipedia.org/wiki/Telephone_numbers_in_Kenya#Mobile_phone_numbers) mentions same.
All 9 digit mobile numbers mentioned in wiki are already supported by our library.
I am able to find only 9 digit 771 range mobile numbers online.  

Please share any official evidence or working numbers for 771 XXX XXXX range. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by EsoftsLimited** [comment] 2016-05-05 06:21
Thank you for this, i had not noted

**Comment by penmetsaa** [comment] 2016-05-05 06:38
@EsoftsLimited
As library is working as intended, closing this issue.

**Closed by penmetsaa** 2016-05-05 06:38 UTC
