### ISSUE TITLE
Format as you type not working at all

### ISSUE THREAD

**Issue by buddyackerman** [googlei18n/libphonenumber#802] opened 2015-08-24 20:23 UTC
From issue #801 (which was closed prematurely).  From the demo page (output shown below) the format is correct but the AsYouTypeFormatter results are not formatted. Why is there a difference between the "regular" formatter and the AYT formatter? 

*Parsing Result:*
{"country_code":49,"national_number":5555555555,"raw_input":"5555555555","country_code_source":20,"preferred_domestic_carrier_code":""}

*Validation Results:*
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: DE
Result from getNumberType(): FIXED_LINE

*Formatting Results:* 
E164 format: +495555555555
Original format: 5555 555555
National format: 05555 555555
International format: +49 5555 555555
Out-of-country format from US: 011 49 5555 555555
Out-of-country format from Switzerland: 00 49 5555 555555

*AsYouTypeFormatter Results*
Char entered: 5 Output: 5
Char entered: 5 Output: 55
Char entered: 5 Output: 555
Char entered: 5 Output: 5555
Char entered: 5 Output: 55555
Char entered: 5 Output: 555555
Char entered: 5 Output: 5555555
Char entered: 5 Output: 55555555
Char entered: 5 Output: 555555555
Char entered: 5 Output: 5555555555

**Comment by mihaelacr-google** [comment] 2015-08-25 14:40
Hi!

This seems to be a duplicate of issue 732: https://github.com/googlei18n/libphonenumber/issues/732.

If you add a + to your number then the as your type formatter works as expected: 
```
****AsYouTypeFormatter Results****
Char entered: + Output: +
Char entered: 5 Output: +5
Char entered: 5 Output: +55 
Char entered: 5 Output: +55 5
Char entered: 5 Output: +55 55
Char entered: 5 Output: +55 55 5
Char entered: 5 Output: +55 55 55
Char entered: 5 Output: +55 55 555
Char entered: 5 Output: +55 55 5555
Char entered: 5 Output: +55 55 5555-5
Char entered: 5 Output: +55 55 5555-55
```

As mentioned in issue 732: the AsYouTypeFormatter has certain constraints due to its online nature (has to be very fast + make decisions "as you type", without having the complete number).

**Closed by mihaelacr-google** 2015-08-25 14:40 UTC
