### ISSUE TITLE
Validation issue with some GB numbers 

### ISSUE THREAD

**Issue by Zroyal** [googlei18n/libphonenumber#2150] opened 2018-02-25 13:57 UTC
some phone numbers in GB with "115" prefix are invalid.
here is the list of 3 affected numbers:
+44115697194
+44115697162
+44115697125

These numbers are valid but the library detects them as invalid numbers.

**Comment by giggsey** [comment] 2018-02-25 20:07
Your numbers are a digit too short.

+44 1156 97 xxx was allocated to Gamma in Jan 2017, and is formatted at 3+7. Your numbers are only 9 digits long, not 10.

Source: http://static.ofcom.org.uk/static/numbering/index.htm#geog1

**Comment by kkeshava** [comment] 2018-02-26 05:13
Hi,
Thank you for taking the time to improve libphonenumber!

We can't connect to any of the numbers provided by you. Did you have a typo?

As mentioned by @giggsey, prefix 115 has a length of 10 digits. Please see Ofcom website which is the official source for GB http://static.ofcom.org.uk/static/numbering/. 

Closing this as working as intended; if you would like to reopen, please share any working numbers or evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Closed by kkeshava** 2018-02-26 05:13 UTC
