### ISSUE TITLE
Finnish Phone number flagged as invalid

### ISSUE THREAD

**Issue by cgalaiya** [googlei18n/libphonenumber#1912] opened 2017-08-24 16:46 UTC
Hi,

Our project previously used libphonenumber 7.4.2 and we recently upgraded to 8.7.1 We noticed the following Finnish number 4248381 is now flagged as invalid. I wanted to understand what prompted the change and whether it would be possible to mark this number again as valid? 

Thanks,
Chiraag

**Comment by keghani** [comment] 2017-08-25 09:09
Hi @cgalaiya,

I don't know what prompted the change, but it would help if you could do some investigation upfront and let us know why this should be changed.

You can see where the behavior changed by e.g. checking the versioned JS demo. For instance, the input (4248381, FI, <empty>) is still valid at 7.6.0: https://rawgit.com/googlei18n/libphonenumber/libphonenumber-7.6.0/javascript/i18n/phonenumbers/demo-compiled.html

Once you see the version number where this changed, you can see if there was a GitHub issue asking for this, e.g. search for "7.6.0" in issues which would be https://github.com/googlei18n/libphonenumber/issues?utf8=%E2%9C%93&q=7.6.0%20

If this doesn't answer your question, or if you think it was wrong of us to make this change, please see the [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) for the information we need to investigate further.

Thanks for using the library!

**Comment by keghani** [comment] 2017-08-25 09:18
In this case it looks like it might have been our update for the ITU communication of 1.XII.2016, currently at
https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000490002PDFE.pdf

Our update was released in v8.4.3.

A lot of Finnish numbers became invalid after that update, because we tightened up granularity to match that in the ITU doc.

This seems to be working as intended and not an issue, so I'll close as infeasible.
Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to discuss further if there are no issues.

To report issues though, do see the contribution guidelines I linked above, and file a new issue or re-open this one if you are reporting, so we pick it up. Thanks!

**Comment by jonbom** [comment] 2017-09-01 03:19
Could it be that the ITU documents N(S)N Max/Minimum Lengths is the total length?
In that case it would mean that e.g. Leading "1 0 1" with max 10 digits actually means "101"+max 7 digits...
Just speculating.

**Comment by jonbom** [comment] 2017-09-01 08:29
@keghani 
If I  I understand this document correctly, it says "NUMBERING PLAN", and nothing about the current state of implementation.
Since some Finnish numbers does not fulfill this plan, but are still valid phone numbers in use, I do not understand the value of following it.
Enlighten me.

**Comment by penmetsaa** [comment] 2017-09-06 03:41
@cgalaiya,

Thank you for taking the time to improve libphonenumber!

We were able to connect to +358 424 8381, but we can't find official evidence
for the actual ranges that are valid. We already support 8 to 10 digit 42 range
phone numbers in Finland. However this is a 7 digit number. 
Please share any evidence you may have about the type (Mobile, Fixed-line..) 
of this number. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by penmetsaa** [comment] 2017-09-27 08:48
Thank you for taking the time to improve libphonenumber!

We were able to connect to +358 424 8381, but we can't find official evidence
for the actual ranges that are valid. We can't support single numbers, we need
context about the prefix that makes them valid. 

I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.

**Comment by cgalaiya** [comment] 2017-11-02 19:27
To add on here, according to this document from the Finnish government: https://www.viestintavirasto.fi/attachments/muutpaatokset/Suomen_numerointisuunnitelma.pdf it seems mobile numbers follow the format of 42 XXXXX and should be considered valid. Can we accommodate the rules into the validation?

**Comment by penmetsaa** [comment] 2017-11-03 05:16
@cgalaiya,
The doc (Page 3) mentions that 8 to 10 digit 4[0-8] phone numbers are valid. The reported number(+358 424 8381) is 7 digits. If you think that this is a valid mobile number in Finland, please share evidence you may have about the type (Mobile, Fixed-line..) and length of this number. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence). Please re-open if you respond so we pick up on it.

**Closed** 2017-11-03 05:16 UTC
