### ISSUE TITLE
Can't get the full description for a number

### ISSUE THREAD

**Issue by motis10** [googlei18n/libphonenumber#1957] opened 2017-10-10 12:19 UTC
When i called that function:
PhoneNumberOfflineGeocoder.getInstance().getDescriptionForNumber(phoneNumber, defaultLocale);
The number **+1-(228)-201-1234** return: "Mississippi,"
While any other source in the internet return at least city+country (Pascagoula, Mississippi).

I attached an example of few numPrefix result from libphonenumber function(getDescriptionForNumber) vs another source.

**Country | prefix | getDescriptionForNumber(new) vs other sources in the internet(old)**
1 | 228201 | new: Mississippi, old: Pascagoula, Mississippi
1 | 228202 | new: Mississippi, old: Pascagoula, Mississippi
1 | 228205 | new: Mississippi, old: Pascagoula, Mississippi
1 | 228206 | new: Gulfport, MS, old: Gulfport, Mississippi
1 | 228207 | new: Biloxi, MS, old: Biloxi, Mississippi
1 | 228208 | new: Mississippi, old: Biloxi, Mississippi
1 | 228209 | new: Mississippi, old: Biloxi, Mississippi
1 | 228210 | new: Mississippi, old: Pascagoula, Mississippi
1 | 228212 | new: Mississippi, old: Biloxi, Mississippi
1 | 228213 | new: Mississippi, old: Gulfport, Mississippi
1 | 228214 | new: Gulfport, MS, old: Gulfport, Mississippi
1 | 228215 | new: Mississippi, old: Ocean Spgs, Mississippi
1 | 228216 | new: Mississippi, old: Bay Saint Louis, Mississippi

**Comment by penmetsaa** [comment] 2017-10-13 05:56
@motis10,

Thank you for taking the time to improve libphonenumber! We would like to know the source of these geocoding details.

Please see our guidelines for [providing evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by motis10** [comment] 2017-10-15 08:39
[This is the source](http://usa-base.com/directory/228201
)
It can give you some more information for each city level

**Comment by penmetsaa** [comment] 2017-10-18 03:54
@motis10,
Looks like usa-base.com is not an official or authoritative evidence such as official government or public carrier documents.  Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by motis10** [comment] 2017-10-19 11:26
I can find the same at NANPA official website.
@penmetsaa I write you here exactly how to find the location for most of the cities you don't have in libphonenumber.

1. Go to [nanpa website](https://www.nationalnanpa.com/reports/reports_cocodes_assign.html)
2. Go to **CO Code (Prefix) Status - Excel Spreadsheet Files** and download the zip files.
3. Unzip the files and enter to the CenCodes.xls file
4. Go to MS sheet (Means Mississippi)
5. Take a look at each of my example in my question and find its place.
For example 1-228201:
The sheet name is MS like Mississippi and the city is in the excel column RateCenter like PASCAGOULA

**Comment by penmetsaa** [comment] 2017-10-23 06:01
@motis10,

Thanks for providing all the details we need! We've accepted this issue but please be
advised that validation metadata updates are top priority and considering our
large backlog we may take a while to get to this. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker] (http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment] 2017-10-23 11:33
@motis10,
Thanks for raising the issue at new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347) Closing this issue as it is duplicate of http://issuetracker.google.com/68118853. We will update that bug about the progress.

**Closed by penmetsaa** 2017-10-23 11:33 UTC

**Comment by motis10** [comment] 2017-10-23 11:35
Great. We all waiting for it 👍
