### ISSUE TITLE
AsYouTypeFormatter Behavior 

### ISSUE THREAD

**Issue by gety9** [googlei18n/libphonenumber#2086] opened 2018-01-12 21:39 UTC
Is it possible to make AsYouTypeFormatter behavior resemble the final phone number.

For example if i know that this is USA phone number and final result must have following format (XXX)XXX-XXXX

Is it possible to make it type like this:
****AsYouTypeFormatter Results****
Char entered: X Output: (X
Char entered: X Output: (XX
Char entered: X Output: (XXX)
Char entered: X Output: (XXX)X
Char entered: X Output: (XXX)XX
Char entered: X Output: (XXX)XXX
Char entered: X Output: (XXX)XXX-X
Char entered: X Output: (XXX)XXX-XX
Char entered: X Output: (XXX)XXX-XXX
Char entered: X Output: (XXX)XXX-XXXX

Instead of
****AsYouTypeFormatter Results****
Char entered: X Output: X
Char entered: X Output: XX
Char entered: X Output: XXX
Char entered: X Output: XXX-X
Char entered: X Output: XXX-XX
Char entered: X Output: XXX-XXX
Char entered: X Output: XXX-XXXX
Char entered: X Output: (XXX) XXX-XX
Char entered: X Output: (XXX) XXX-XXX
Char entered: X Output: (XXX) XXX-XXXX

p.s. I am planning to use javascript version of the library on our website.

**Comment by andyst** [comment] 2018-01-15 08:40
For the US this is working as intended because some users dial XXX-XXXX (local number without area-code). If they continue entering digits, it's switching to the standard national format with area-code in parenthesis.

Generally AsYouTypeFormatter (AYTF) tries to stay as close to standard phone number formatting as done by PhoneNumberUtil.

You could always customize the formatting rules in the metadata (.xml) but then you have to deal with keeping your patches up to date.

I'll close this issue for now. Feel free to re-open if you'd like to continue the discussion.

**Closed by andyst** 2018-01-15 08:40 UTC
