### ISSUE TITLE
Validation issue with number containing multiple "+" 

### ISSUE THREAD

**Issue by zotop** [googlei18n/libphonenumber#1005] opened 2016-03-14 16:05 UTC
"+++46 70 000 00 00"

Is considered to be a valid phone number, shouldn't it throw a NumberParseException?

**Comment by padmaksha** [comment] 2016-03-16 06:17
The parser is quite lenient and looks for a number in the input text. To do this, it ignores punctuation and white-space, as well as any text before the number (e.g. a leading “Tel: ”).
The parser searches for and in this case finds a number in e164 format in the given text, trims the non-number bits (two leading ‘+’ symbols) and then interpretation of the number takes place.

**Comment by padmaksha** [comment] 2016-03-16 06:19
Closing the issue as working as intended.

**Closed** 2016-03-16 06:21 UTC
