### ISSUE TITLE
Not validating service numbers of India

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#334] opened 2014-12-03 20:22 UTC
Imported from [Google Code issue #334](https://code.google.com/p/libphonenumber/issues/detail?id=334) created by [nayak.chandra1](https://code.google.com/u/103360693919767078519/) on 2013-08-06T11:15:54.000Z:

---

<b>What steps will reproduce the problem?</b>
1. Go to &quot;Phone Number Parser Demo&quot; page, under &quot;Demo&quot; section.
2. Give any emergency numbers like 100(local police), 101(fire service) etc
3. Result shows Invalid Number.

<b>What is the expected output? What do you see instead?</b>
1. It should show the given number as a valid one.
2. The getNumberType() should be EMERGENCY.

<b>What version of the product are you using? On what operating system?</b>

<b>Please provide any additional information below.</b>

**Comment by keghani** [comment] 2016-04-22 15:19
We have recently done many India updates from the dot.gov.in website and have more coming up so the docs from 2003 were either covered in the meantime or are out of scope. The short number results are working as intended.

**Comment by lararennie** [comment] 2016-04-22 15:48
Actually we will add some more short-code support to India. Will leave this open to track this.

**Comment by SumathiSundara** [comment] 2017-03-29 10:17
Fixed in release 8.4.0

**Closed by SumathiSundara** 2017-03-29 10:17 UTC
Labels: bug, priority-medium
