### ISSUE TITLE
findNumbers() returns false positive

### ISSUE THREAD

**Issue by lsun2sc** [googlei18n/libphonenumber#1701] opened 2017-04-20 23:53 UTC
Hi,
I'm using "US" as default region. 
Just wondering why findNumbers() will return text like "666-1111" as phone number? I think US number should have 10/11 digits. 

Thanks!

**Comment by penmetsaa** [comment] 2017-04-24 09:44
Hi lsun2sc@

Thank you for using libphonenumber!

"666-1111" is a possible local only number in US i.e without area code. 
Can you share your client code, so we can see what exact method you are calling and the leniency level?

**Comment by lsun2sc** [comment] 2017-04-24 16:22
Hi @penmetsaa my code looks like:
```
Iterable<PhoneNumberMatch> m = PhoneNumberUtil.getInstance().findNumbers(text, Local.getDefault().getCountry(), Leniency.POSSIBLE, Long.MAX_VALUE);
```
Is it possible to only return 10/11 digit numbers as phone number?

**Comment by penmetsaa** [comment] 2017-04-25 09:15
@lsun2sc,

Thanks for sharing the client code.

If you would like to fetch only valid (10/11 digit) numbers, you can use Leniency.VALID while calling ```findNumbers(number, defaultRegion, leniency, maxTries)``` API. This is also the default leniency level when you call the other overloading API ```findNumbers(number, defaultRegion) ```.

Please go though the [java doc](https://github.com/googlei18n/libphonenumber/blob/09519ab/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L478) to know more about these leniency levels.

**Comment by penmetsaa** [comment] 2017-04-25 09:49
@lsun2sc,
Closing this issue as the library is working as intended here. Please feel to reopen if you think otherwise.

**Closed by penmetsaa** 2017-04-25 09:49 UTC
