### ISSUE TITLE
Validation issue with Pakistan number (Contains alphabets)

### ISSUE THREAD

**Issue by zeeshan-ks** [googlei18n/libphonenumber#1511] opened 2017-01-17 06:31 UTC
`try { 
String numberStr = "923419005ba521";
            PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
            PhoneNumber numberProto = phoneUtil.parse(numberStr, "PK");
            boolean isValid = phoneUtil.isValidNumber(numberProto);
            System.out.println("number:" + numberProto + " isValid:" + isValid);
        } catch (NumberParseException e) {
            System.err.println("NumberParseException was thrown: " + e);
        }`

Gives output
"number:Country Code: 92 National Number: 3419005521 isValid:true"

Expected Output:
Since number contains alphabets, it should throw exception

**Comment by penmetsaa** [comment] 2017-01-17 11:13
@zeeshan-ks,

Thank you for taking the time to improve libphonenumber!

This issue is duplicate of #328 and #1199 issues.

Summary:
1. We remove letters because parse() method is doing its best to extract a phone number out of the given text. 
2. If there is three or more alphabetical characters in input number then we consider it as possible "alpha-numeric" number and convert them to numbers accordingly. If there are two or less alphabetical characters then we consider it irrelevant characters around the number and drop them (in the same way as we drop punctuation or whitespace).
Ex: 3419005bac521 https://libphonenumber.appspot.com/phonenumberparser?number=3419005bac521&country=PK
Please take a look at the [java doc of parse() method](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2792)
To avoid the later case you can use PhoneNumberUtil.findNumbers() to extract numbers and then parse it.

**Closed by penmetsaa** 2017-01-17 11:13 UTC

**Comment by zeeshan-ks** [comment] 2017-01-17 11:16
@penmetsaa Thank you 👍
