### ISSUE TITLE
Validation issue with 07624 123456 (GB)

### ISSUE THREAD

**Issue by jlasley** [googlei18n/libphonenumber#1745] opened 2017-05-16 22:34 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): GB

Example number(s) affected ("+1 555 555-1234"): 07624 123456

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):  +44 07624 XXXXXX, +44 07924 XXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.):  07624 mobile and paging, 07924 mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

The region code is evaluated incorrectly for +44 07624 and +44 07924.  These are currently returning as GB, they should return as mobile numbers with IM as country code. 

https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom#Isle_of_Man

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=07624+123456&country=GB)

**Comment by penmetsaa** [comment] 2017-05-17 08:11
@jlasley,

Thanks for using libphonenumber.

As per below official doc from http://static.ofcom.org.uk/static/numbering/, all 7624X pager numbers (except 76242 which belongs to Isle of Man) are assigned to GB. http://static.ofcom.org.uk/static/numbering/S7.xls 

Looks like the Wikipedia that you have shared do not enough details to catch these cases of numbering allotment. Libphonenumber do support these ranges as per above official plan. 

This is the reason why input 07624+123456 (default input region: GB) is resulted as valid one in the demo. http://libphonenumber.appspot.com/phonenumberparser?number=07624+112345&country=GB

You can see that 07624+223456 (default input region: GB) is resulted as invalid one for GB (look at ```isValidNumberForRegion()``` result.). http://libphonenumber.appspot.com/phonenumberparser?number=07624+223456&country=GB

**Comment by penmetsaa** [comment] 2017-05-18 06:51
@jlasley,

We got it wrong earlier and added 7624[013-689] ranges to GB as region names are not mentioned in above S7.xls sheet. Now, we found that Manx Telecom is only available in Isle of Man. So we will support all 7624 (except 76247 as it is mentioned as protected) as pager numbers in Isle of Man and remove 7624[013-689] ranges from GB region. Wikipedia also confirms same.

We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment] 2017-05-24 07:20
This is fixed in release 8.5.0
https://libphonenumber.appspot.com/phonenumberparser?number=07624+123456&country=GB

**Closed by penmetsaa** 2017-05-24 07:20 UTC

**Comment by jlasley** [comment] 2017-05-24 17:30
Thanks for the fix.
