### ISSUE TITLE
Validation 

### ISSUE THREAD

**Issue by jillemoine** [googlei18n/libphonenumber#1992] opened 2017-10-31 01:29 UTC
Country:
*   Example number(s) and/or range(s):1
*   Number type ("fixed-line", "mobile", "short code", etc.):225
*   For short codes, cost and dialing restrictions:241-9509
*   Where or whom did you get the number(s) from:Allen Lemoine 
*   Authoritative evidence (e.g. national numbering plan, operator announcement):Verizon 
*   Link from demo (http://libphonenumber.appspot.com) showing error

**Comment by penmetsaa** [comment] 2017-10-31 02:37
@jillemoine,
Thank you for taking the time to improve libphonenumber!

Looks like library is working as intended. We already consider +1-225-241-9509 as valid US phone number. See [demo result](http://libphonenumber.appspot.com/phonenumberparser?number=1-225-241-9509&country=US&geocodingLocale=und). Please let us know what is the issue here. Do you say that all +1 225 XXX XXXX belong to Verizon?

We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by jillemoine** [comment] 2017-10-31 03:18
I want to make sure that phone number doesn’t have another secret number 


Sent from Yahoo Mail for iPhone


On Monday, October 30, 2017, 9:37 PM, penmetsaa <notifications@github.com> wrote:


@jillemoine,
Thank you for taking the time to improve libphonenumber!

Looks like library is working as intended. We already consider +1-225-241-9509 as valid US phone number. See demo result. Please let us know what is the issue here. Do you say that all +1 225 XXX XXXX belong to Verizon?

We need more information to fix this. Please see our contribution guidelines.

**Comment by penmetsaa** [comment] 2017-10-31 03:32
@jillemoine,
As library is working as intended. Closing this issue. 

Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by penmetsaa** 2017-10-31 03:32 UTC
