### ISSUE TITLE
Latest libphone library unable to recognize below numbers from Manx Telecom Provider.

### ISSUE THREAD

**Issue by kiranchakkilam** [googlei18n/libphonenumber#1613] opened 2017-03-07 10:30 UTC
One of our customer sent a request from this number:  4476243064XX.  Latest library sends the response as Invalid Mobile number.  But according to below website this number is valid mobile and belongs Manx Telecom. Please look in to his bug. 

https://www.textmagic.com/free-tools/carrier-lookup

**Comment by keghani** [comment] 2017-03-07 10:32
Greetings,

Thanks for using and helping improve libphonenumber!

What is the region code? We need more information to fix this, please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by kiranchakkilam** [comment] 2017-03-07 11:15
Please find updated  guildelines according to above document

Country/region affected (e.g., "US"):   UK 
*   Example number(s) affected ("+1 555 555-1234"):  447624306466
*   The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 
*   The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
*   The cost, if applicable ("toll-free", "premium rate", "shared cost"): 
*   Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):

**Comment by kkeshava** [comment] 2017-03-09 05:40
Hi,

This is actually working as intended; +447624306466 is marked by our library as a valid *pager* number. To check the latest behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B447624306466)  (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
It is validated as pager and not mobile as per UK’s official telecommunications website http://www.ofcom.org.uk/static/numbering/S7.xls - depending on your use case you may want to allow pagers in your app instead.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by chrisuk112** [comment] 2017-08-29 17:04
Sorry for reopening this issue. I wish to make this discussion easier by adding to existing knowledge.

The cited document above (http://www.ofcom.org.uk/static/numbering/S7.xls) is not in accordance with other Ofcom numbering documents. It is also not in accordance with practical reality in the telecom industry and has been criticised for this.*

If you check the Ofcom National Telephone Numbering Plan**, it reflects reality better by listing the 07624 range as being exempt from the 076 range's service type declaration as radiopaging-only:
"076 (except 07624 – see Part C5) Radiopaging Service"

Part C5 within the same document** explains as follows:
"07624 Radiopaging Service and Mobile Services (Isle of Man Communications Commission)."

This double classification of 07624 and the resulting confusion is a result of mixed-service usage after the UK's "Big Number Change" in the early 2000s. 
Modern technological trends without a doubt will effect a complete take-over of the 07624 range for Mobile Phone services, while Paging services lose popularity. This discussion will not disappear.

Personal context:
I work in the telco industry and our customers are unable to forward phone calls from our service to 07624 Manx Telecom mobile phone numbers due to its incorrect classification.

I hope this great library can be changed to be better than the standard, as the standard in this case is wrong.

*) e.g. here: https://jo808.files.wordpress.com/2010/10/20100930-ofcom.pdf (1.32)

**) https://www.ofcom.org.uk/phones-telecoms-and-internet/information-for-industry/numbering
https://www.ofcom.org.uk/__data/assets/pdf_file/0013/102613/national-numbering-plan-june-2017.pdf



[national-numbering-plan-june-2017.pdf](https://github.com/googlei18n/libphonenumber/files/1261025/national-numbering-plan-june-2017.pdf)

**Comment by kkeshava** [comment] 2017-08-31 06:06
@chrisuk112,
We are already supporting prefixes 7624[2-4] as Mobile numbers. This was fixed in release 8.6.0. Please see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B447624306412).

Thanks for providing all the details we need! We've accepted this issue and will fix the remaining prefixes i.e 7624[015-9] as Mobile in an upcoming release. 

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by chrisuk112** [comment] 2017-08-31 09:43
@kkeshava 
Thank you very much, looking forward to the update.

**Comment by penmetsaa** [comment] 2017-09-08 10:20
Fixed in 8.8.1

**Closed by penmetsaa** 2017-09-08 10:20 UTC
