### ISSUE TITLE
Validation of Numeric Ranges for Telefonica Panama

### ISSUE THREAD

**Issue by mariapovr** [googlei18n/libphonenumber#2009] opened 2017-11-13 20:49 UTC
Please validate that you have all the numeric ranges for Telefonica Panama updated in your platforms. Attached is the most recent IR21 versión 

Best regards,
[IR.21 Document - PANMS November 2017 Telefonica Moviles Panama.pdf](https://github.com/googlei18n/libphonenumber/files/1468424/IR.21.Document.-.PANMS.November.2017.Telefonica.Moviles.Panama.pdf)

**Comment by kkeshava** [comment] 2017-11-14 04:53
@mariapovr,
Thank you for using libphonenumber!

This is actually working as intended; all the ranges mentioned in the IR 21 doc is already marked by
our library as Mobile. To check the latest behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B50764912345) (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by kkeshava** 2017-11-14 04:53 UTC
