### ISSUE TITLE
+1 283 NPA XXXX (future Ohio)

### ISSUE THREAD

**Issue by kputland** [googlei18n/libphonenumber#1528] opened 2017-01-26 22:35 UTC
Country/region affected (e.g., "US"): US
Example number(s) affected ("+1 555 555-1234"): +1 283 NPA-XXXX
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +1 283 NPA-XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.):
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): http://www.prnewswire.com/news-releases/puco-announces-new-283-area-code-assignment-for-southwest-ohio-when-the-current-513-area-code-is-exhausted-75499417.html

**Comment by kkeshava** [comment] 2017-01-30 05:50
Duplicate of #1527.

**Closed by kkeshava** 2017-01-30 05:50 UTC
