### ISSUE TITLE
Update toll free metadata for Indonesia

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#64] opened 2014-12-03 19:48 UTC
Imported from [Google Code issue #64](https://code.google.com/p/libphonenumber/issues/detail?id=64) created by [power_of_s@yahoo.com](https://code.google.com/u/111134660273840925811/) on 2011-09-29T22:23:26.000Z:

----
<b>What steps will reproduce the problem?</b>

I am having issues with toll free numbers for several countries. 
phonenumber library after parsing fails to identify number as toll- 
free - 

Indonesia : 007 803 011 0397 (parsed as unknown) 
Referred as toll-free here: http://www.ibm.com/planetwide/id/, http://store.apple.com/id/help/contact 

<b>What is the expected output? What do you see instead?</b>

This should be identified as tollfree number after parsing.

<b>What version of the product are you using? On what operating system?</b>

v3.9

**Comment by keghani** [comment] 2016-04-22 10:30
Closing as the library is working as intended.

**Closed by keghani** 2016-04-22 10:30 UTC
Labels: priority-medium, type-defect
