### ISSUE TITLE
Australian numbers with 1300 prefix and more than 6 digits

### ISSUE THREAD

**Issue by tdeschamps** [googlei18n/libphonenumber#2148] opened 2018-02-23 10:32 UTC
*   Country: Australia
*   Example number(s) and/or range(s):
    * `+61 1300 3278 929`
*   Number type ("fixed-line", "mobile", "short code", etc.): "fixed-line", "shared cost"
*   For short codes, cost and dialing restrictions:
*   Where or whom did you get the number(s) from: https://www.fastway.com.au/sydney/
*   Authoritative evidence (e.g. national numbering plan, operator announcement):
    * These Australian numbers are called _smartnumbers_. They're supposed to start with `1300` followed by 6 digits. However, numbers can be longer, but only the 6 first digits will be taken into account. 
    * https://www.thenumberingsystem.com.au/#/about-smartnumbers
*   Link from demo (http://libphonenumber.appspot.com) showing error:
    * http://libphonenumber.appspot.com/phonenumberparser?number=%2B61+1300+3278+929

🙌 Many thanks for your help!! 🙌

**Comment by SumathiSundara** [comment] 2018-02-26 07:51
Thank you for taking the time to improve libphonenumber!

We support 10 digit long numbers for the prefix 13 while the specified number +61 1300 3278 929 is 11 digits long.

Here is our official evidence: https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200000D0001PDFE.pdf

We are not able to find 11 digit numbers with this prefix online.

Closing this as working as intended; if you would like to reopen, please share any working numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Closed by SumathiSundara** 2018-02-26 07:51 UTC

**Comment by JanMalte** [comment] 2018-03-08 09:57
I think I have the same issue. The phone number from this company is parsed as invalid.
https://beowulfbuilders.com.au/contact/
https://libphonenumber.appspot.com/phonenumberparser?number=1300+BEOWULF&country=AU
https://libphonenumber.appspot.com/phonenumberparser?number=1300+236+9853&country=AU
