### ISSUE TITLE
Number 358501422 from Finland get parsed into 358358501422

### ISSUE THREAD

**Issue by lightbringer1991** [googlei18n/libphonenumber#1193] opened 2016-07-05 22:52 UTC
Please copy this template into your report and answer the questions to the best of your ability.

    Country/region affected (e.g., "US"): FI
    Example number(s) affected ("+1 555 555-1234"): 358501422
    The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): N/A
    The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile number
    The cost, if applicable ("toll-free", "premium rate", "shared cost"): N/A

This number 358501422 is from Finland, and it is actually an international format.
Country code: 358
National number: 0501 422

However when I parse the number, it gets appended and becomes 358358501422

I have checked with the online demo
https://libphonenumber.appspot.com/phonenumberparser?number=358501422&country=FI
and compared it with another API here
https://www.twilio.com/lookup

The result seems to be different. Could you please take a look into this

**Comment by lararennie** [comment] 2016-07-06 08:45
This is a duplicate of #17 and more recently, #1179. We can't improve here unless we have more detailed information about the Finnish plan that rules out 358501422 as a viable number. For more details, see the response to #1179. If you know it is in international format, please prefix it with "+", which is the correct international format.

Since fixing this is infeasible, closing as WAI.

**Closed by lararennie** 2016-07-06 08:45 UTC
