### ISSUE TITLE
German Mobile Numbers Not Passing Validation

### ISSUE THREAD

**Issue by kryan2288** [googlei18n/libphonenumber#1876] opened 2017-07-31 20:09 UTC
MobileNumberLib is returning an invalid result for an active DTAG (T-Mobile) German mobile number. 

491755762074

**Actual**:
Number to use: 491755762074 
Locale: DE 
Results: Invalid, FIXED_LINE 

**Expected**
Number to use: 491755762074 
Locale: DE 
Result: Valid, MOBILE

**Comment by kkeshava** [comment] 2017-08-01 06:39
Hi,
Thank you for using libphonenumber! For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

This is actually working as intended; +491755762074 is already marked by our library as Mobile. Please see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B491755762074). In Germany 49 is both a country calling code and an area code, so it is safe to put a "+" in front to indicate this to the library. For more information, check out [this FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-wasnt-the-country-code-removed-when-parsing).

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by kkeshava** 2017-08-01 06:39 UTC
