### ISSUE TITLE
Validation issue with 0813189162 (CD)

### ISSUE THREAD

**Issue by zebreguy** [googlei18n/libphonenumber#1243] opened 2016-08-02 14:18 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): CD

Example number(s) affected ("+1 555 555-1234"): 0813189162

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0813189162&country=CD)

**Comment by padmaksha** [comment] 2016-08-05 09:11
@zebreguy 

This number 0813189162 and its range is already supported by our library. If you look at the demo (http://libphonenumber.appspot.com/phonenumberparser?number=0813189162&country=CD) you will find isValidNumber() is set to true. That means our library is correctly interpreting the number. 
As this is working as intended closing this issue. Please reopen the issue if you have any further questions.

Thanks

**Closed by padmaksha** 2016-08-05 09:11 UTC
