### ISSUE TITLE
Validation issue with +966563531111

### ISSUE THREAD

**Issue by MuhammadAdelA** [googlei18n/libphonenumber#1913] opened 2017-08-25 14:53 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 

Example number(s) affected ("+1 555 555-1234"): +966563531111

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B966563531111)

**Comment by hagbard** [comment] 2017-08-25 15:53
Can you provide more information.
What is it that's "wrong" with this number?
What do you think should be changed?

**Comment by MuhammadAdelA** [comment] 2017-08-27 13:33
sorry I posted the issue by mistake there is nothing wrong with it .. I'm so sorry

**Comment by penmetsaa** [comment] 2017-08-28 03:41
@MuhammadAdelA ,

Thanks for the confirmation. Closing this issue as working as intended.

For your next metadata issue, we invite you to file issues in Google's new
[Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

**Closed by penmetsaa** 2017-08-28 03:41 UTC
