### ISSUE TITLE
PhoneNumberUtil. getRegionCodeForNumber returning wrong ISO country code

### ISSUE THREAD

**Issue by yishai-glide** [googlei18n/libphonenumber#636] opened 2015-02-25 19:16 UTC
**steps to reproduce**
Either run [this android project](https://github.com/yishai-glide/libphonenumberTest), or follow the next steps:

1. Parse am E.164 Candian number like "+18882422100" 
2. Run PhonenumberUtil.getRegionCodeForNumber on that number.

**expected result**
Getting "CA" for Canada.

**What version of the product are you using? On what operating system?**
Running on version 7.0.2
OS is Android 4.4 (KitKat)

**Please provide any additional information below.**
This will happen to any NANPA number not from the US

**Comment by dlyongemallo** [comment] 2015-02-25 19:30
This appears to be a duplicate of issue #586. As in that issue, you'll see that the PhoneNumberOfflineGeocoder result for your number is empty. This is working as intended.

**Closed by dlyongemallo** 2015-02-25 19:30 UTC
