### ISSUE TITLE
Crashes with missing metadata in Android Application

### ISSUE THREAD

**Issue by rachitmishra** [googlei18n/libphonenumber#819] opened 2015-09-15 13:44 UTC
Getting `java.lang.IllegalStateException: missing metadata: /com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_IN` while trying to parse a number.

Using 
    `compileSdkVersion 23
    buildToolsVersion '23.0.0'`

and library version 7.0.10

**Comment by dlyongemallo** [comment] 2015-09-17 13:58
I think this may be a dup of issue #528.

**Comment by rachitmishra** [comment] 2015-09-18 16:17
@dlyongemallo no solution there. i guess gradle jar has issues

**Comment by mithrann** [comment] 2016-08-24 10:46
@rachitmishra  @dlyongemallo 
I am facing this in release mode that is after applying progaurd. Only recent change i did is updating the play services version from 9.0.0 to 9.4.0

Fatal Exception: java.lang.IllegalStateException: missing metadata: /com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_IN
       at com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.loadMetadataFromFile(SourceFile:103)
       at com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.getMetadataForRegion(SourceFile:79)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(SourceFile:1994)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(SourceFile:2844)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(SourceFile:2705)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(SourceFile:2695)

**Comment by keghani** [comment] 2017-01-19 18:39
This is a duplicate of #1249.

**Comment by keghani** [comment] 2017-01-19 18:39
(And no longer be an issue with the current code.)

**Closed by keghani** 2017-01-19 18:39 UTC

**Comment by keghani** [comment] 2017-03-01 09:39
Please take a look at our new [resource loading FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#how-do-i-load-libphonenumber-resources-in-my-android-app), the fix is probably to call `PhoneNumberUtil` API outside the main thread.
