### ISSUE TITLE
Country code should be case-insensitive.

### ISSUE THREAD

**Issue by akirashimosoeda** [googlei18n/libphonenumber#1897] opened 2017-08-08 16:41 UTC
Hi, as the title says, any country code should be case-insensitve.
In Java, for example, if you use `us` instead of `US` as the countryCode, you will receive null as the phone number. This is not right, because ISO 3166 states that country codes are [case-insensitve](http://www.wiley.com/legacy/compbooks/graham/html4ed/appe/iso3166.html)

**Comment by kkeshava** [comment] 2017-08-09 05:25
@akirashimosoeda,
Thank you for taking the time to improve libphonenumber! For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing. 

This is actually working as intended; You can use countryCode in lower/upper case and the library to validate the number. To check the behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=<REPORTED_NUMBER>)(instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by kkeshava** 2017-08-09 05:25 UTC

**Comment by akirashimosoeda** [comment] 2017-08-09 13:19
Strange, as PhoneNumberUtils provided by Android library uses this library inside their code and doesn't seem to work as expected.

**Comment by akirashimosoeda** [comment] 2017-08-09 13:37
I tested now and it clearly shows that this library is NOT case-insensitive in Java.

```java
try {
    proto = util.parse("0983506377", "ch"); // "ch" will call an exception
    String number = util.format(proto, PhoneNumberUtil.PhoneNumberFormat.E164);
    Log.d(TAG, "Phonenumber: " + number);
} catch (NumberParseException e) {
        e.printStackTrace();
}
```
This code does not work as expected. But if you change it to `"CH"`, it will work.

**Comment by andyst** [comment] 2017-08-11 08:03
Yes, it requires upper-case, as specified here:
https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L52

The demo accepts lower-case too:
https://github.com/googlei18n/libphonenumber/blob/e971aa0b4d11515aea7fadf2bc5e8ff7725a52b3/java/demo/src/com/google/phonenumbers/PhoneNumberParserServlet.java#L82

It's how the public API is defined. Long-term we're considering changes in this space (a different data type for regions instead of strings), but we don't have immediate plans to change this.
