### ISSUE TITLE
Consider +55 (73) 94102-0799 (renumbered) valid in Brazil

### ISSUE THREAD

**Issue by keghani** [googlei18n/libphonenumber#1086] opened 2016-04-21 16:37 UTC
Branched from https://github.com/googlei18n/libphonenumber/issues/1041

**Comment by penmetsaa** [comment] 2016-04-22 09:51
As the library is working as intended, closing this issue.

+55 73 4XXX XXXX looks like landline number as per below online pages.
http://www.espti.com.br/servicos
https://www.tripadvisor.in/Attraction_Review-g303262-d9454274-Reviews-Tenda_Teatro_Popular_de_Ilheus-Ilheus_State_of_Bahia.html

As per brazil numbering plan prefix 9 can be placed before the subscriber number (last 8 digits) only in mobile numbers.

This is the Brazil document about the 9th digit. It states clearly that the 9th digit applies only to mobile numbers.
http://www.anatel.gov.br/Portal/verificaDocumentos/documento.asp?numeroPublicacao=337603&filtro=1&documentoPath=337603.pdf 
(See page 2, number 5)

**Closed by penmetsaa** 2016-04-22 09:51 UTC
