### ISSUE TITLE
Validation issue with 43851268 (NO)

### ISSUE THREAD

**Issue by oikmar** [googlei18n/libphonenumber#2136] opened 2018-02-18 18:35 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): NO

Example number(s) affected ("+1 555 555-1234"): 43851268

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

4xx xx xxx: Mobile numbers (newer) should be valid mobile numbers.

https://en.wikipedia.org/wiki/Telephone_numbers_in_Norway#Mobile_numbers

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=43851268&country=NO)

**Comment by SumathiSundara** [comment] 2018-02-20 07:31
Thank you for taking the time to improve libphonenumber!

We can't connect to +47 43851268. There is a conflicting evidence due to this other source we found online which states prefix 43 is blocked: https://www.nkom.no/npt/numsys/E.164.pdf

Closing this as working as intended; if you would like to reopen, please share
any working numbers or evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Closed by SumathiSundara** 2018-02-20 07:31 UTC
