### ISSUE TITLE
AsYouTypeFormatter outputs trailing space for "001" in France

### ISSUE THREAD

**Issue by valeriyo** [googlei18n/libphonenumber#1906] opened 2017-08-16 18:07 UTC
The following test should be passing, but it fails, because there is a trailing whitespace "00 1 ", which shouldn't be there.. This is the only case that I found, where `AsYouTypeFormatter` outputs a trailing non-digit character, and it would effectively prevent Backspace from deleting "1" because the whitespace would immediately reappear after it's removed.

```
@Test public void testFrance001() {
    PhoneNumberUtil util = PhoneNumberUtil.getInstance();
    AsYouTypeFormatter formatter = util.getAsYouTypeFormatter("FR");
    formatter.inputDigit('0');
    formatter.inputDigit('0');
    assertEquals("00 1", formatter.inputDigit('1'));
}
```

**Comment by penmetsaa** [comment] 2017-08-18 04:04
This is the intended behavior, and we have no plans to change it.

AsYouTypeFormatter outputs a space after the calling code for all regions.
For example, try inputting `+41`, and there will be a space after the last
character.

If you would like to understand the library's behavior better, please take a
look at [AsYouTypeFormatter.java](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/AsYouTypeFormatter.java), and if you still have questions, consider
joining our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss).

I'll close this as it's not an issue with the library.

**Closed by penmetsaa** 2017-08-18 04:04 UTC

**Comment by valeriyo** [comment] 2017-08-18 06:39
@penmetsaa, thanks for the reply.

However, `+1` doesn't format with a trailing whitespace. Isn't that special?

Also, in `+41212345678` (which is formatted as `+41 21 234 56 78`) only the first space is output as trailing character:

`+41` -> `+41 ` (with trailing space)
`+4121` -> `+41 21` (no trailing space)
`+4121234` -> `+41 21 234` (no trailing space)
`+412123456` -> `+41 21 234 56` (no trailing space)

Anyway, since the workaround for this strange behavior is straightforward (i.e. strip the trailing whitespace) - I'm just going to stop right here.
