### ISSUE TITLE
Incorrect Location of Indian phone numbers

### ISSUE THREAD

**Issue by laurelsudeep** [googlei18n/libphonenumber#1482] opened 2016-12-21 04:44 UTC
Lot of the MSC Codes of Indian Telephone operators have changed over the past few years. 
Few of them have been relocated to new service providers. Eg. Jio has new set of MSC Codes for India. Others have been reassigned. 
Latest update MSC codes for India can be found on the following link
http://www.dot.gov.in/sites/default/files/u10/MSC%20Code%20as%20on%2011052015%20%284%29_0.xls(update: looks like the DOT has taken down the link)
Attaching the copy of it
[MSC Code as on 11052015 (4) (1).xls.zip](https://github.com/googlei18n/libphonenumber/files/665503/MSC.Code.as.on.11052015.4.1.xls.zip)

Due to this lot of phone numbers show incorrect location details on phones which show this data.
Eg. Xiaomi, [Huwaei](https://drive.google.com/open?id=0B6ZYUF6vJs_8LThQSDRtNi0xU28)
Sample
+918177817791 shows Belur, Karnataka - Incorrect
+918177817791 should show Maharastra - Correct
![screen shot 2016-12-21 at 10 13 51 am](https://cloud.githubusercontent.com/assets/9976790/21377659/402b2676-c766-11e6-89b4-5c87fcce2ae8.png)

Sudeep

**Comment by penmetsaa** [comment] 2016-12-22 10:39
@laurelsudeep ,
Thank you for using libphonenumber! Thanks for attaching the document as well :) http://www.dot.gov.in/sites/default/files/u10/MSC%20Code%20as%20on%2011052015%20%284%29_0.xls is working for us. We already have this document and wanted to add support to these India phone number ranges. We will prioritize this update (support for new ranges, not location updates for mobile numbers) and fix it in an upcoming release. 

Regarding location details of mobile numbers:
1. libphonenumber is not returning any location details for mobile number +918177817791. Please take a look at our demo site.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B918177817791
2. libphonenumber return location details only for fixedline numbers w.r.t India. 
3. There are some overlapping ranges between fixedline and mobile. Ex: 891 is STD code of Visahakapatnam and 8912 is Airtel's mobile range as per Airtel IR.21 doc.
4. Library returns location details for such FIXED_LINE_OR_MOBILE numbers. 
5. We would like to check on feasibility of adding location details for India mobile numbers. We need to have the data ready for most of the mobile ranges. 
Since we receive many feature requests with varying levels of impact and subsequent priorities, please help us help you by making us understand the impact here if possible. It helps us prioritizing the location updates.

We are now in a release freeze period and may not be able to release this until the second week of January. We will update this bug when fix is done.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by laurelsudeep** [comment] 2016-12-24 14:51
Thank you.

Regarding location details for mobile numbers, OEMs like Xiaomi and Huawei
show location details on their dialer app and SMS.

Eg: Check out attached pics.
Need to figure out how to get this corrected too.

Sudeep

On 22-Dec-2016 4:09 PM, "penmetsaa" <notifications@github.com> wrote:

@laurelsudeep <https://github.com/laurelsudeep> ,
Thank you for using libphonenumber! Thanks for attaching the document as
well :)
http://www.dot.gov.in/sites/default/files/u10/MSC%20Code%20as%20on%2011052015%20%284%29_0.xls
is working for us. We already have this document and wanted to add support
to these India phone number ranges. We will prioritize this update (support
for new ranges, not location updates for mobile numbers) and fix it in an
upcoming release.

Regarding location details of mobile numbers:

   1. libphonenumber is not returning any location details for mobile
   number +918177817791 <081778%2017791>. Please take a look at our demo
   site.

   https://libphonenumber.appspot.com/phonenumberparser?number=%2B918177817791
   2. libphonenumber return location details only for fixedline numbers
   w.r.t India.
   3. There are some overlapping ranges between fixedline and mobile. Ex:
   891 is STD code of Visahakapatnam and 8912 is Airtel's mobile range as per
   Airtel IR.21 doc.
   4. Library returns location details for such FIXED_LINE_OR_MOBILE
   numbers.
   5. We would like to check on feasibility of adding location details for
   India mobile numbers. We need to have the data ready for most of the mobile
   ranges.
   Since we receive many feature requests with varying levels of impact and
   subsequent priorities, please help us help you by making us understand the
   impact here if possible. It helps us prioritizing the location updates.

We are now in a release freeze period and may not be able to release this
until the second week of January. We will update this bug when fix is done.

Please note that you have submitted this information with the knowledge
that we may use, modify, reproduce, publicly display, and distribute the
information in accordance with our open source policies. Please let us know
if you did not intend to submit the information for such use.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/libphonenumber/issues/1482#issuecomment-268772912>,
or mute the thread

**Comment by laurelsudeep** [comment] 2017-02-20 08:52
Hey there

Any update on this bug??

Sudeep

**Comment by penmetsaa** [comment] 2017-03-03 06:36
@laurelsudeep,
Sorry for the delay in response.

The excel document that you have provided do not have geocoding details of fixed-line numbers in India. It has geocoding  details (state names) of the mobile numbers. We do support the number provided by you (81778 XXXXX) as mobile number of Telewings carrier. Libphonenumber do not return geocoding details for India mobile numbers as mentioned earlier.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B91+81778+17791

Might be the case that OEMs like Xiaomi and Huawei are using previous versions of the library. The respective brands should send updates to see latest behaviour (similar to the results of our demo website) on devices.

Regarding adding support to new mobile ranges in excel sheet: We have recently added support to new Jio mobile ranges in the libraray. We will check if we are missing anything from the excel sheet and update this bug accordingly.

**Comment by laurelsudeep** [comment] 2017-03-08 10:08
cool. thanks .. will check on the OEM end from my side.

**Comment by keghani** [comment] 2017-07-18 15:44
This is a duplicate of #578, so I'm closing this, and we'll update the status at #578.

**Closed by keghani** 2017-07-18 15:44 UTC
