### ISSUE TITLE
ZipException when load data file in different process

### ISSUE THREAD

**Issue by fyhuang117** [googlei18n/libphonenumber#1305] opened 2016-08-31 09:34 UTC
**[Lib version]: 7.0.2**
**[Platform]: Android 7.0 (N)**

**[Issue description]:**
When libphonenumber API called from different  process, it will encounter the ZipException in a very seldom ratio. And the refactoring in (https://github.com/googlei18n/libphonenumber/commit/bff8c8ca8d689738f3d567a78f6b5988114c1991) seems can only fix the multi thread within the same process, but can't fix the multi process issue.

I add some retry mechanism when encounter IOException and sometimes it works and sometimes it fails until max retry times reaches.
Should we handle IOException in this case or is there any suggestion about these issues?

**[Exception Backtrace]**
Issue1: ZipException when loading metadata
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl: cannot load/parse metadata: /com/android/i18n/phonenumbers/data/PhoneNumberMetadataProto_CN
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl: java.util.zip.ZipException: invalid block type
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl:     at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:170)
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl:     at java.io.FilterInputStream.read(FilterInputStream.java:133)
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl:     at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2316)
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl:     at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2329)
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl:     at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2800)
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl:     at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl:     at java.io.ObjectInputStream.<init>(ObjectInputStream.java:302)
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl:     at com.android.i18n.phonenumbers.MultiFileMetadataSourceImpl.loadMetadataFromFile(MultiFileMetadataSourceImpl.java:115)
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl:     at com.android.i18n.phonenumbers.MultiFileMetadataSourceImpl.getMetadataForRegion(MultiFileMetadataSourceImpl.java:82)
08-31 09:33:04.468505 17214 17214 E iFileMetadataSourceImpl:     at com.android.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:1982)

Issue2: Load config data fail which lead to the null pointer exception in MappingFileProvider
08-30 22:08:19.879401 12852 12852 W PrefixFileReader: java.util.zip.ZipException: invalid block type

08-30 22:08:19.943925   912 13093 D AES     : java.lang.NullPointerException: Attempt to get length of null array
08-30 22:08:19.943925   912 13093 D AES     :     at java.util.Arrays.binarySearch(Arrays.java:1893)
08-30 22:08:19.943925   912 13093 D AES     :     at com.android.i18n.phonenumbers.prefixmapper.MappingFileProvider.getFileName(MappingFileProvider.java:158)
08-30 22:08:19.943925   912 13093 D AES     :     at com.android.i18n.phonenumbers.prefixmapper.PrefixFileReader.getPhonePrefixDescriptions(PrefixFileReader.java:78)
08-30 22:08:19.943925   912 13093 D AES     :     at com.android.i18n.phonenumbers.prefixmapper.PrefixFileReader.getDescriptionForNumber(PrefixFileReader.java:133)
08-30 22:08:19.943925   912 13093 D AES     :     at com.android.i18n.phonenumbers.geocoding.PhoneNumberOfflineGeocoder.getDescriptionForValidNumber(PhoneNumberOfflineGeocoder.java:133)
08-30 22:08:19.943925   912 13093 D AES     :     at com.android.i18n.phonenumbers.geocoding.PhoneNumberOfflineGeocoder.getDescriptionForNumber(PhoneNumberOfflineGeocoder.java:192)

**Comment by keghani** [comment] 2016-08-31 09:37
This is a duplicate of https://github.com/googlei18n/libphonenumber/issues/1249.

**Closed by keghani** 2016-08-31 09:37 UTC
