### ISSUE TITLE
Validate Germany 1516\d{6} mobile numbers (DE, +49)

### ISSUE THREAD

**Issue by andreasbernhard** [googlei18n/libphonenumber#1517] opened 2017-01-20 12:23 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "DE"): 

Example number(s) affected ("+1 555 555-1234"): +491516022907

The phone number range(s) to which the issue applies ("+49 151 6XXXXXX"): 

The type of the number(s) ("mobile".): 

The cost, if applicable (""): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): https://www.teltarif.de/telekom-handynummer-01516/news/42170.html

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B491516022907)

**Comment by keghani** [comment] 2017-01-20 16:42
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by keghani** [comment] 2017-01-20 16:49
Actually we already validate 11-digit numbers beginning with 1516 as mobile, assigned to T-Mobile: http://libphonenumber.appspot.com/phonenumberparser?number=15161230000&country=DE

You're trying with a 10-digit number. I also couldn't connect to that number, so maybe you had a typo?

I think this is working as intended. Please re-open if I got that wrong.

**Closed by keghani** 2017-01-20 16:49 UTC
