### ISSUE TITLE
Getting many phone numbers identified as USA country code

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlei18n/libphonenumber#1902] opened 2017-08-15 07:26 UTC
Suppose I wish to get the country code prefix of a given, valid phone number, such as this one (from [**here**](https://www.bahamas.com/contact)) :

+1-242-302-2000

The code to do it is:

```
String phoneToCheck="+12423022000";
PhoneNumber internationalPhoneNumber = phoneNumberUtil.parse(phoneToCheck, "");
```

But when I call this function `internationalPhoneNumber.getCountryCode() ` , I get "1" .

This is wrong, because it is used for the USA:
http://www.worldatlas.com/aatlas/ctycodes.htm

There are plenty of other phone numbers that have this result.

How can I solve this?

**Comment by keghani** [comment] 2017-08-15 08:12
1 is indeed the country calling code.
I think what you may be referring to is leadingDigits which we have in our metadata file?
E.g. see the [metadata for Barbados](https://github.com/googlei18n/libphonenumber/blob/b58ef8b8a607074845534cb2ebe19b208521747f/resources/PhoneNumberMetadata.xml#L2192).

This looks like a duplicate of https://github.com/googlei18n/libphonenumber/issues/1796, so I'll close it.
To set expectations, we have other priorities for the foreseeable future so it may be a while before we get to feature requests.

**Closed by keghani** 2017-08-15 08:12 UTC

**Comment by AndroidDeveloperLB** [comment] 2017-08-15 08:19
How do I get the "leadingDigits" using the query of the phone number ?
Do I have to parse the file?

**Comment by keghani** [comment] 2017-08-15 10:17
It's not supported right now, hence the feature request in #1796. We'll post updates there.
The file is an internal implementation detail so it can go away or the format can change without notice.

**Comment by AndroidDeveloperLB** [comment] 2017-08-15 11:00
What is supported exactly that helps with this matter?
You said leadingDigits , but the prefix of the country to call it, which differentiate it from other countries, is not just "+1". It's longer.
