### ISSUE TITLE
Validation issue with 49(0)345279580 (DE)

### ISSUE THREAD

**Issue by tobias-trame** [googlei18n/libphonenumber#1067] opened 2016-04-06 15:29 UTC
The validation with `parse("49(0)345279580", "DE")` returns incorrect result `"+49490345279580"` instead of expected `"+49345279580"`. In comparison the same number with one more digit `"49(0)3452795800"` returns the correct expected result `"+493452795800"`

Country affected: DE
Example number affected: 49(0)345279580
The type of the number: fixed-line 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=49%280%29345279580&country=DE)

**Comment by giggsey** [comment] 2016-04-06 15:42
Have a look at https://github.com/googlei18n/libphonenumber/issues/705, which is the same problem.

**Comment by tobias-trame** [comment] 2016-04-06 15:53
not exactly, if you have 49 without a "+" but followed by "(0)", it should be clear that 49 is the country code and that 04903 was not the desired prefix number

**Comment by penmetsaa** [comment] 2016-04-13 14:36
@tobias-trame

Thanks for reporting.

The issue is that your input 49(0)345279580 is a valid German number. 
If you mean the 49 to be the country code, add a + to the front and the library should work as you intend.

This issue is more specific to Germany due to the variable length of German numbers and the country code (49) being the same as one of the area codes in fixed line numbers.
The library is working as intended when it treats 49 as part of the national number for input 49(0)345279580 (without +).
The library expects users to put + in front if they mean 49 as the country code.

See how the library treats +49 as country code: http://libphonenumber.appspot.com/phonenumberparser?number=%2B49345279580&country=DE
And how it treats 49 as area code for the same input without the plus: http://libphonenumber.appspot.com/phonenumberparser?number=49345279580&country=DE

Closing this issue as it is working as intended.

**Closed by penmetsaa** 2016-04-13 14:36 UTC
