### ISSUE TITLE
+1 681 NPA XXXX

### ISSUE THREAD

**Issue by kputland** [googlei18n/libphonenumber#1535] opened 2017-01-26 22:56 UTC
Country/region affected (e.g., "US"): US/West Virginia
Example number(s) affected ("+1 555 555-1234"):+1 681 NPA XXXX
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):+1 681 NPA XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.):
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):
http://www.allareacodes.com/681
http://www.theet.com/opinion/we-must-adapt-to-area-code-change/article_b88cb885-7cb2-5b99-8fcc-90949171f0de.html
https://en.wikipedia.org/wiki/Area_codes_304_and_681

**Comment by kkeshava** [comment] 2017-01-30 05:51
Duplicate of #1527.

**Closed by kkeshava** 2017-01-30 05:51 UTC
