### ISSUE TITLE
Validation issue with +18004563456

### ISSUE THREAD

**Issue by ki1023lou210** [googlei18n/libphonenumber#1607] opened 2017-03-05 16:26 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 

Example number(s) affected ("+1 555 555-1234"): +18004563456

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B18004563456)

**Comment by ki1023lou210** [comment] 2017-03-05 16:27
dari mohamed

**Comment by kkeshava** [comment] 2017-03-06 06:34
@ki1023lou210,
Thank you for using libphonenumber!
This is actually working as intended; +18004563456 is already marked by the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B18004563456) as a valid *TOLL FREE* number.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Closed by kkeshava** 2017-03-06 06:34 UTC
