### ISSUE TITLE
Denmark fixed line phone number marked as FIXED_LINE_OR_MOBILE

### ISSUE THREAD

**Issue by banngbt** [googlei18n/libphonenumber#960] opened 2016-01-29 02:25 UTC
How to reproduce the result?
Phone number 4598581xxx, where xxx can be any valid number eg. 111
The Result from getNumberType() function returned FIXED_LINE_OR_MOBILE

This number is confirmed a FIXED LINE phone number. In addition, from wikipedia, it shows the numbering set should be marked as FIXED LINE.

libphonenumber version used is 7.2.3

Why not libphonenumber apply the numbering list from wikipedia if that is valid?
https://en.wikipedia.org/wiki/Telephone_numbers_in_Denmark

**Comment by keghani** [comment] 2016-01-29 10:03
This is a duplicate of #953 - please see my response there,

**Closed by keghani** 2016-01-29 10:03 UTC
