### ISSUE TITLE
Ukraine phone formatting is incorrect

### ISSUE THREAD

**Issue by alexoviedo999** [googlei18n/libphonenumber#1668] opened 2017-03-29 23:13 UTC
When using the library for Ukraine telephone formatting, the number returned by phoneUtil.getExampleNumber(), "311234567", provides incorrect formatting (XXXX XXXXX instead of the correct XX XXX XXXX) when used with phoneUtil.format().  When using other example phone numbers the formatting returned is correct.  I used:
https://libphonenumber.appspot.com/
and
https://giggsey.com/libphonenumber/
to confirm my hypothesis.

**Comment by andyst** [comment] 2017-04-03 07:06
Thanks for raising the issue.

First, a **disclaimer:**
How phone numbers are formatted is sometimes a contested topic and we generally go with the predominant way to format a given phone number range. Further, if there's no clear / overwhelming evidence, we usually err on the side of not changing the formatting because we have to assume that there is a silent majority which didn't speak up over the last N years because they're fine with the current format and some of them might see a change as a regression.

Currently we have 3 formats for the Ukraine:

**Fixed-line:**

Nation format: 03112 34567
http://libphonenumber.appspot.com/phonenumberparser?number=311234567&country=UA

National format: 0692 450 000
http://libphonenumber.appspot.com/phonenumberparser?number=692450000&country=UA

**Mobile:**

National format: 071 336 0000
http://libphonenumber.appspot.com/phonenumberparser?number=713360000&country=UA

The format you suggest is currently only used for mobile numbers.

**Questions**

- What evidence is there to use the proposed format for fixed-line numbers starting with 311? 
- Do you suggest to change it only for fixed-line numbers starting with 311?

Please elaborate. This is not something we can change just based on a single business website. Official / authoritative sources (government websites) or statistics (demonstrating that most businesses / users format it a given way) e.g. based on web searches would help.

Thanks!

**Comment by kkeshava** [comment] 2017-06-08 05:55
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.

**Closed by kkeshava** 2017-06-08 05:55 UTC
