### ISSUE TITLE
Library returns invalid message for Australian number +6147395XXXX

### ISSUE THREAD

**Issue by Bhasuri** [googlei18n/libphonenumber#827] opened 2015-09-22 05:31 UTC
I am referring to this issue https://github.com/googlei18n/libphonenumber/issues/20 which is closed. Looks like the fix isn't working.

**Comment by bmarry** [comment] 2015-09-23 09:12
Hi 

What is the number you are trying to add that is causing the issue? 

In the linked bug it is reported as
"I'm unable to register my Australian mobile number +6148[...] as the recovery phone for my Gmail account - not sure if this fix/change is the cause behind that."

But in the subject line it is 
+6147395XXXX

When I test +6147395XXXX here( http://libphonenumber.appspot.com/)

It is returning valid, see below. 

Can you please clarify the issue? 

Brendan 

-----------------
Phone Number entered: +6147395XXXX
defaultCountry entered: 
Language entered: en
Parsing Result
country_code	61
national_number	473959999
extension	 
country_code_source	FROM_NUMBER_WITH_PLUS_SIGN
italian_leading_zero	false
raw_input	+6147395XXXX
Validation Results
Result from isPossibleNumber()	true
Result from isValidNumber()	true
Phone Number region	AU
Result from getNumberType()	MOBILE
Formatting Results
E164 format	+61473959999
Original format	+6147395XXXX
National format	0473 959 999
International format	+61 473 959 999
Out-of-country format from US	011 61 473 959 999
Out-of-country format from CH	00 61 473 959 999
AsYouTypeFormatter Results
Char entered: '+' Output:	+
Char entered: '6' Output:	+6
Char entered: '1' Output:	+61
Char entered: '4' Output:	+61 4
Char entered: '7' Output:	+61 47
Char entered: '3' Output:	+61 473
Char entered: '9' Output:	+61 473 9
Char entered: '5' Output:	+61 473 95
Char entered: 'X' Output:	+6147395X
Char entered: 'X' Output:	+6147395XX
Char entered: 'X' Output:	+6147395XXX
Char entered: 'X' Output:	+6147395XXXX
PhoneNumberOfflineGeocoder Results
Location	 
PhoneNumberToTimeZonesMapper Results
Time zone(s)	[Antarctica/Macquarie, Australia/Adelaide, Australia/Eucla, Australia/Lord_Howe, Australia/Perth, Australia/Sydney, Indian/Christmas, Indian/Cocos]

**Comment by Bhasuri** [comment] 2015-09-24 05:22
Hello,
+61473950XXX is the number I used. 
``
PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
		try
		{
			PhoneNumber toPhoneNumber = phoneUtil.parse("+61473950XXX", null);
			if (phoneUtil.isValidNumber(toPhoneNumber))
				return true;
		}
		catch (NumberParseException e)
		{
			//comes here
		}

**Comment by keghani** [comment] 2015-09-24 10:05
Hi @Bhasuri ,

To confirm whether the phone number library is working as intended in the latest release, please use http://libphonenumber.appspot.com/. In this case:
```
Step 1: +61473950000
Step 2: AU
```
gives a valid number.

Please sync to the latest release (7.0.11) and see if that solves your problem.

If not, please send a patch (e.g. on your own fork of the repository) so we can see exactly what your code looks like. For example, leaving XXXX in the phone number is unlikely to yield the result you need.

**Comment by keghani** [comment] 2015-10-09 12:49
Hi @Bhasuri ,

Any updates here?

**Comment by keghani** [comment] 2015-11-27 09:38
Closing as this is not an issue with the repository. If you still need help please re-open the issue.

**Closed by keghani** 2015-11-27 09:38 UTC
