### ISSUE TITLE
Validation issue with +38007334544 (UA)

### ISSUE THREAD

**Issue by Dmatafonov** [googlei18n/libphonenumber#2058] opened 2017-12-11 09:45 UTC
Country/region affected (e.g., "US"): UA
Ukraine

Example number(s) affected ("+1 555 555-1234"): +38007334544

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

**+380 073 XXXXX
+380 093 XXXXX
+380 063 XXXXX**

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 
Mobile

Supporting evidence 

073 code as well as 063 and 093 is in use by mobile operator Life **since 2014**.
Sorry no proof in english, but here is in russian: http://numbers.in.ua/articles.php?article_id=116

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B38007334544&country=UA)

**Comment by penmetsaa** [comment] 2017-12-11 11:13
@Dmatafonov,

Thank you for taking the time to improve libphonenumber!

We are not able to connect to +38007334544 or +3807334544 (without additional 0). All mobile ranges in Ukarine are 9 digits in length. We already support 9 digit 73, 063 and 093 Life's mobile ranges based on below ITU doc.
https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000DB0005PDFE.pdf

See our demo results: https://libphonenumber.appspot.com/phonenumberparser?number=%2B380733454412

Closing this as working as intended; if you would like to reopen, please share
any working numbers or evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Closed by penmetsaa** 2017-12-11 11:13 UTC
