### ISSUE TITLE
Validation issue with +254 715 874 189 (KE)

### ISSUE THREAD

**Issue by ondara** [googlei18n/libphonenumber#1491] opened 2017-01-03 08:24 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): US

Example number(s) affected ("+1 555 555-1234"): 234-567-8901 x123

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=234-567-8901+x123&country=US&geocodingLocale=en-US)

**Comment by penmetsaa** [comment] 2017-01-03 09:40
@ondara ,

Thanks for using libphonenumber.

Can you please let us know what is the issue here. Libphonenumber is able to validate both the numbers.
1. Input: +254 715 874 189, default country: KE (The one that is present in title) - 
https://libphonenumber.appspot.com/phonenumberparser?number=%2B254+715+874+189
2. Input: 234-567-8901 x123, default country: US (Which is entered in demo site)- http://libphonenumber.appspot.com/phonenumberparser?number=234-567-8901+x123&country=US&geocodingLocale=en-US

**Comment by keghani** [comment] 2017-01-19 19:14
There doesn't seem to be an issue here, closing.
As @penmetsaa mentioned, the title of the issue is unrelated to the content, and both numbers are considered valid.

**Closed by keghani** 2017-01-19 19:14 UTC
