### ISSUE TITLE
Validation issue with 7977884930 (IN)

### ISSUE THREAD

**Issue by RanjitPati** [googlei18n/libphonenumber#1426] opened 2016-11-08 13:25 UTC
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 7977884930

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=7977884930&country=IN)

**Comment by penmetsaa** [comment] 2016-11-08 13:42
@RanjitPati 
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by keghani** [comment] 2016-11-08 14:13
This looks valid in the demo, what is the scope of the issue?

**Comment by RanjitPati** [comment] 2016-11-10 08:47
Its an valid Indian Mobile Number, but  showing Land Line number.

**Comment by penmetsaa** [comment] 2016-11-10 11:45
@RanjitPati 
Yes, 7977 range is assigned to Reliance Jio mobile carrier recently.

But 10 digit 79xxx xxxxx range is assigned to Ahmedabad fixed-line phones.
https://www.google.co.in/#q=ahmedabad+std+code

Due to this overlapping, we updated support for 7977 numbers as 'fixed-line or mobile'.
This is done as part of todays release 7.7.4
https://libphonenumber.appspot.com/phonenumberparser?number=7977884930&country=IN

Please share us any valid evidence which clearly separates these ranges. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by RanjitPati** [comment] 2016-11-10 12:47
good. It seems like fixed. i am closing the issue for now as the fix is looking fine.

**Comment by RanjitPati** [comment] 2016-11-10 12:50
oops. jar still not released.

**Comment by lararennie** [comment] 2016-11-10 13:15
Yes it is. Please follow link from the github "releases" page- https://github.com/googlei18n/libphonenumber/releases

Takes you to here:
http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/7.7.4/

**Closed by lararennie** 2016-11-10 13:15 UTC
