### ISSUE TITLE
Phone number format is wrong for Turkey

### ISSUE THREAD

**Issue by georgeabrahamp** [googlei18n/libphonenumber#1253] opened 2016-08-08 20:37 UTC
Summary:
 Our linguists are claiming that the national number formatting returned by libphonenumber is incorrect. 

  Expected:  0xxx xxx xx xx
  Returned:  0xxx xxx xxxx

Adding email thread from libphonenumber-discuss group. 

> Hi Aravind,
> 
> I looked at the above links and the results are not definitive. The one proper source is the itu doc (from Information and Communication Technologies Authority of Turkey). I went to their website (http://www.btk.gov.tr/en-US/Pages/Contact / http://www.btk.gov.tr/tr-TR/Sayfalar/Iletisim) and the contact information shows the telephone ending in  xx xx format. Also the ITU directory for Turkey shows the same format (except for fax) https://www.itu.int/ITU-D/icteye/DisplayCountry.aspx?code=TUR. 
> 
> In any case - it looks like the generally accepted numbering format is the one that ends in XX XX.
> 
> Links reported under 3 are american websites - displaying US Numbers - not turkish numbers. 
> 
> For the google results - I am seeing both in some pages. Could the issue be that libphonenumber is used to format the numbers in the second set of results?
> 
> For instance for the top hit from: http://www.istanbulhomes.com/contact - the banner shows the right format
> 
> Inline image 1
> 
> whereas the body shows the libphonenumber format
> 
> Inline image 2
> 
> Do you guys have an authority on Turkey who can definitively answer this? Can anyone from Turkey chime in?
> 
> Thanks,
> /george
> 
> GEORGE ABRAHAM
> Senior Software Engineer  |  Customer Messaging Platform
> 
> On Fri, Aug 5, 2016 at 4:03 AM, 'Aravind Penmetsa' via libphonenumber-discuss libphonenumber-discuss@googlegroups.com wrote:
> Hi George,
> 
> We have done some more investigation on this.
> 
> Based on below findings, format XXX XXX XXXX is also widely used to mention Turkish numbers.
> 1. "+90 212 100..999 10..99 10..99": 14,800,000 results 
> "+90 212 100..999 1000..9999": 14,700,000 results
> 2. Official ITU doc recommends format XXX XXX XXXX
> https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000D60001MSWE.doc
> 3. Yellow page websites of Turkey also use XXX XXX XXXX
> http://www.turkishnyyellowpages.com/index.php?category=14&page=2
> http://www.411.com/business/valley-service-center-quitaque-tx
> 
> Both the formats are used equally. 
> Do you have any other evidence that the XX XX is preferred?
> 
> Sorry for not checking this earlier. :)
> 
> Thanks & Regards,
> Aravind
> 
> On Thu, Aug 4, 2016 at 1:23 PM, Aravind Penmetsa penmetsaa@google.com wrote:
> Yes, there isn't  a GitHub issue to track this yet. 
> I think it is better if you create the new GitHub issue (with all these details) so that you get proper notifications to your mailbox.
> 
> Thanks & Regards,
> Aravind
> 
> On Thu, Aug 4, 2016 at 12:15 AM, 'George Abraham' via libphonenumber-discuss libphonenumber-discuss@googlegroups.com wrote:
> Thanks Aravind.
> 
> Will there be an issue to track this? I couldn't find one on the github page. If you point me to the issue - I can follow it to get updated about when we can expect the fix.
> 
> Thanks again for your prompt response,
> /george
> 
> On Wednesday, August 3, 2016 at 4:08:42 AM UTC-7, Aravind Penmetsa wrote:
> @George,
> Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.
> 
> If the input number contains formatting already, such as spaces or brackets, AsYouTypeFormatter returns the result with no edits. 
> Ex: For input 0212 319 450 0, AsYouTypeFormatter returns same 0212 319 450 0.
> 
> If the input is not in any format, AYTF uses national formatting rules which are defined in metadata.
> Ex: For input 02123194500, AsYouTypeFormatter returns 0212 319 4500. 
> 
> We will correct Turkey national formatting rules as mentioned by you.
> Ex: 0212 319 45 00
> 
> On Fri, Jul 29, 2016 at 11:05 PM, 'George Abraham' via libphonenumber-discuss libphonenum...@googlegroups.com wrote:
> Hi All,
> 
> Our linguists are claiming that the national number formatting returned by libphonenumber is incorrect. 
> 
> Expected:  0xxx xxx xx xx
> Returned:  0xxx xxx xxxx
> 
> Basically they say that in Turkey the last 4 digits are split into two. See some examples at the following links:
> http://www.turkcell.com.tr/tr/hakkimizda/iletisim?place=footer
> http://www.mfa.gov.tr/contact-us.en.mfa
> http://www.citibank.com.tr/gcb/english/footer/contact_us.htm?
> Looking at the results it looks like the AsYouTypeFormatter is returning the right format but not the parse
> 
> http://libphonenumber.appspot.com/phonenumberparser?number=%280212%29+319+45+00&country=TR&geocodingLocale=en-TR
> 
> Formatting Results
> E164 format   +902123194500
> Original format   (0212) 319 4500
> National format   (0212) 319 4500
> International format  +90 212 319 4500
> Out-of-country format from US 011 90 212 319 4500
> Out-of-country format from CH 00 90 212 319 4500
> 
> AsYouTypeFormatter Results
> Char entered: '(' Output: (
> Char entered: '0' Output: (0
> Char entered: '2' Output: (02
> Char entered: '1' Output: (021
> Char entered: '2' Output: (0212
> Char entered: ')' Output: (0212)
> Char entered: ' ' Output: (0212)
> Char entered: '3' Output: (0212) 3
> Char entered: '1' Output: (0212) 31
> Char entered: '9' Output: (0212) 319
> Char entered: ' ' Output: (0212) 319
> Char entered: '4' Output: (0212) 319 4
> Char entered: '5' Output: (0212) 319 45
> Char entered: ' ' Output: (0212) 319 45
> Char entered: '0' Output: (0212) 319 45 0
> Char entered: '0' Output: (0212) 319 45 00

**Comment by georgeabrahamp** [comment] 2016-08-09 01:00
More cases where the number is formatted ending with xx xx. 

iPhone formats the number correctly 

![img_4778](https://cloud.githubusercontent.com/assets/6344144/17501247/d99e8c42-5d91-11e6-9efc-72fcdadc8059.PNG)

**Comment by penmetsaa** [comment] 2016-08-11 09:48
Hi George,

Thanks so much for all the details provided.

Yes, you are right regarding yellow page websites. These are referring to numbers in US.
I doubt that most of these websites (that uses format xxxx) use libphonenumber.

We generally follow ITU official documents.
Even though xxxx format is the official one, looks like format xx xx have slight edge in terms of usage. We can go ahead with the change (from xxxx to xx) as your linguists say.

You can also create your own custom [NumberFormat](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java#L8) and feed it to [PhoneNumberUtil.formatByPattern()](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L1127). But this is not recommended as you will miss the latest updates on formats for respective leading digits. You can always raise issues like this and update the library itself.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by georgeabrahamp** [comment] 2016-08-12 21:22
Thanks Aravind!

**Comment by georgeabrahamp** [comment] 2016-09-28 18:09
Hi Aravind,

Any updates on when this will be fixed?

**Comment by penmetsaa** [comment] 2016-09-29 04:42
Hi George,
As this is not a validation issue we have not prioritized it.
We will prioritize and fix this in an upcoming release.

**Comment by georgeabrahamp** [comment] 2016-09-29 22:53
Thanks

**Comment by keghani** [comment] 2017-01-19 19:07
Fixed in v7.7.3: http://libphonenumber.appspot.com/phonenumberparser?number=%2B902123194500

**Closed by keghani** 2017-01-19 19:07 UTC
