### ISSUE TITLE
Hong Kong shouldn't have area code 

### ISSUE THREAD

**Issue by maxterka** [googlei18n/libphonenumber#925] opened 2015-12-16 15:52 UTC
Hi, 
In Hong Kong there is no area code, only the country code (+852) and the direct phone number (e.g: 2854 4866), but the libphonenumber parse the first 4 digits into area code.

**Comment by keghani** [comment] 2015-12-16 16:17
How may I reproduce the issue using the [demo](http://libphonenumber.appspot.com/)?
When I enter "2854 4866" and "HK" I don't see anything about an area code.
Which part of this is unexpected?

![screenshot](https://cloud.githubusercontent.com/assets/9949289/11846406/c7a34812-a418-11e5-9a92-58869624f18e.png)

**Comment by keghani** [comment] 2015-12-16 17:00
Please help us understand this issue.

We added contribution guidelines at [CONTRIBUTING.md](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).
Please ensure you go through the checklist there and use the template so we have the information we need to fix this.

**Comment by keghani** [comment] 2016-04-21 15:50
Closing as we can't reproduce the issue. Please re-open if you have clarifications.

**Closed by keghani** 2016-04-21 15:50 UTC
