### ISSUE TITLE
Mexican number normalization

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#273] opened 2014-12-03 20:14 UTC
Imported from [Google Code issue #273](https://code.google.com/p/libphonenumber/issues/detail?id=273) created by [Elaaboudi.Meriem](https://code.google.com/u/115872363040026899124/) on 2013-05-14T15:58:49.000Z:

----
<b>What steps will reproduce the problem?</b>
1.Enter a normalized mexican phone number for example : 522941185211

<b>What is the expected output? What do you see instead?</b>
Expected Result from getNumberType() = MOBILE but was FIXED

<b>What version of the product are you using? On what operating system?</b>
libphonenumber demo

<b>Please provide any additional information below.</b>

In the file attached that comes from this site : http://dset01.cft.gob.mx/numeracion.exe/w_vip we can see that the number should be recognized as MOBILE.

**Comment by penmetsaa** [comment] 2015-12-18 04:30
Issue <a href="https://github.com/googlei18n/libphonenumber/issues/902">#902</a> has been merged into this issue.

**Comment by lararennie** [comment] 2016-10-05 15:37
Duplicate of issue #132

**Closed by lararennie** 2016-10-05 15:37 UTC
Labels: duplicate, priority-medium, type-enhancement
